<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>DASHDOT_LINE_LBL</source>
      <translation>DashDot</translation>
    </message>
    <message>
      <source>DASH_LINE_LBL</source>
      <translation>インデントを設定します。</translation>
    </message>
    <message>
      <source>SOLID_LINE_LBL</source>
      <translation>ソリッド</translation>
    </message>
    <message>
      <source>DOT_LINE_LBL</source>
      <translation>基準点</translation>
    </message>
    <message>
      <source>DAHSDOTDOT_LINE_LBL</source>
      <translation>DashDotDot</translation>
    </message>
    <message>
      <source>NONE_LINE_LBL</source>
      <translation>[なし]</translation>
    </message>
    <message>
      <source>DTRIANGLE_MARKER_LBL</source>
      <translation>下向きの三角形</translation>
    </message>
    <message>
      <source>UTRIANGLE_MARKER_LBL</source>
      <translation>三角形のトップ指向</translation>
    </message>
    <message>
      <source>LTRIANGLE_MARKER_LBL</source>
      <translation>左の三角形を指向</translation>
    </message>
    <message>
      <source>RTRIANGLE_MARKER_LBL</source>
      <translation>右向き三角形を指向</translation>
    </message>
    <message>
      <source>RECTANGLE_MARKER_LBL</source>
      <translation>四角形の作成</translation>
    </message>
    <message>
      <source>CROSS_MARKER_LBL</source>
      <translation>クロス</translation>
    </message>
    <message>
      <source>XCROSS_MARKER_LBL</source>
      <translation>斜め十字</translation>
    </message>
    <message>
      <source>DIAMOND_MARKER_LBL</source>
      <translation>ダイヤモンド</translation>
    </message>
    <message>
      <source>CIRCLE_MARKER_LBL</source>
      <translation>円</translation>
    </message>
    <message>
      <source>NONE_MARKER_LBL</source>
      <translation>[なし]</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_FitDataDlg</name>
    <message>
      <source>FIT_DATA_TLT</source>
      <translation>データの範囲を調整します。</translation>
    </message>
    <message>
      <source>FIT_HORIZONTAL</source>
      <translation>水平調整します。</translation>
    </message>
    <message>
      <source>MIN_VALUE_LAB</source>
      <translation>最小:</translation>
    </message>
    <message>
      <source>VERTICAL_AXIS</source>
      <translation>垂直軸</translation>
    </message>
    <message>
      <source>MAX_VALUE_LAB</source>
      <translation>最大:</translation>
    </message>
    <message>
      <source>HORIZONTAL_AXIS</source>
      <translation>水平軸</translation>
    </message>
    <message>
      <source>VERTICAL_LEFT_AXIS</source>
      <translation>左側の垂直軸</translation>
    </message>
    <message>
      <source>FIT_ALL</source>
      <translation>すべてを調整します。</translation>
    </message>
    <message>
      <source>VERTICAL_RIGHT_AXIS</source>
      <translation>右数値軸</translation>
    </message>
    <message>
      <source>FIT_VERTICAL</source>
      <translation>垂直方向に調整します。</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_ViewManager</name>
    <message>
      <source>PLOT2D_VIEW_TITLE</source>
      <translation>シーン Plot2d: %M - ビューアー: %V</translation>
    </message>
    <message>
      <source>PREF_GROUP_PLOT2DVIEWER</source>
      <translation>Plot 2D Viewer</translation>
    </message>
    <message>
      <source>PREF_SHOW_LEGEND</source>
      <translation>キャプションを表示します。</translation>
    </message>
    <message>
      <source>PREF_LEGEND_POSITION</source>
      <translation>凡例の位置:</translation>
    </message>
    <message>
      <source>PREF_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>PREF_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>PREF_TOP</source>
      <translation>ページのトップへ</translation>
    </message>
    <message>
      <source>PREF_BOTTOM</source>
      <translation>下</translation>
    </message>
    <message>
      <source>PREF_CURVE_TYPE</source>
      <translation>曲線の種類:</translation>
    </message>
    <message>
      <source>PREF_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>PREF_LINES</source>
      <translation>ライン</translation>
    </message>
    <message>
      <source>PREF_SPLINE</source>
      <translation>スプライン</translation>
    </message>
    <message>
      <source>PREF_MARKER_SIZE</source>
      <translation>座標系のサイズ:</translation>
    </message>
    <message>
      <source>PREF_LINEAR</source>
      <translation>線形</translation>
    </message>
    <message>
      <source>PREF_LOGARITHMIC</source>
      <translation>対数</translation>
    </message>
    <message>
      <source>PREF_HOR_AXIS_SCALE</source>
      <translation>水平方向の軸のスケール:</translation>
    </message>
    <message>
      <source>PREF_VERT_AXIS_SCALE</source>
      <translation>垂直軸のスケール:</translation>
    </message>
    <message>
      <source>PREF_VIEWER_BACKGROUND</source>
      <translation>背景色</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_AnalyticalCurveDlg</name>
    <message>
      <source>ANALYTICAL_CURVE_TLT</source>
      <translation>分析曲線のプロパティ</translation>
    </message>
    <message>
      <source>AC_CURVE_PARAMS</source>
      <translation>曲線のパラメーター</translation>
    </message>
    <message>
      <source>AC_CURVE_PROPS</source>
      <translation>曲線のプロパティ</translation>
    </message>
    <message>
      <source>AC_FORMULA</source>
      <translation>y (x) =</translation>
    </message>
    <message>
      <source>AC_NB_INTERVALS</source>
      <translation>Nb に登録間隔</translation>
    </message>
    <message>
      <source>AC_AUTO_ASSIGN</source>
      <translation>自動割り当て。</translation>
    </message>
    <message>
      <source>AC_MARKER_TYPE</source>
      <translation>マーカーの種類</translation>
    </message>
    <message>
      <source>AC_LINE_TYPE</source>
      <translation>行の種類</translation>
    </message>
    <message>
      <source>AC_LINE_WIDTH</source>
      <translation>線の太さ</translation>
    </message>
    <message>
      <source>AC_CURVE_COLOR</source>
      <translation>曲線の色</translation>
    </message>
    <message>
      <source>AC_ADD_BTN</source>
      <translation>カーブを追加します。</translation>
    </message>
    <message>
      <source>AC_REM_BTN</source>
      <translation>カーブを削除します。</translation>
    </message>
    <message>
      <source>AC_OK_BTN</source>
      <translation>わかりました</translation>
    </message>
    <message>
      <source>AC_APPLY_BTN</source>
      <translation>適用</translation>
    </message>
    <message>
      <source>AC_CANT_CALCULATE</source>
      <translation>曲線は計算できません。入力パラメーターを確認してください。</translation>
    </message>
    <message>
      <source>AC_CLOSE_BTN</source>
      <translation>閉じる(&amp;C)</translation>
    </message>
    <message>
      <source>AC_HELP_BTN</source>
      <translation>ヘルプ</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_SetupCurveScaleDlg</name>
    <message>
      <source>TLT_SETUP_CURVE_SCALE</source>
      <translation>スケールの曲線 (s)</translation>
    </message>
    <message>
      <source>CURVE_SCALE_FACTOR</source>
      <translation>スケール ファクター</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_SetupViewDlg</name>
    <message>
      <source>PLOT2D_CURVE_TYPE_LBL</source>
      <translation>曲線の種類:</translation>
    </message>
    <message>
      <source>PLOT2D_SET_AS_DEFAULT_CHECK</source>
      <translation>既定の設定として保存します。</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_HOR</source>
      <translation>水平軸:</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_TLT</source>
      <translation>標準化</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_MODE_MIN</source>
      <translation>最小を標準化します。</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_MODE_MAX</source>
      <translation>最大値を標準化します。</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_LEFT_AXIS</source>
      <translation>左の Y 軸:</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_RIGHT_AXIS</source>
      <translation>右の Y 軸:</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_VER</source>
      <translation>垂直軸:</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_TLT</source>
      <translation>グリッド、軸のマーク</translation>
    </message>
    <message>
      <source>INF_AXES_X</source>
      <translation>X 軸</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_TLT</source>
      <translation>スケール モード</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_BOTTOM</source>
      <translation>下</translation>
    </message>
    <message>
      <source>TLT_SETUP_PLOT2D_VIEW</source>
      <translation>2次元可視化設定をプロットします。</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_VER_TITLE</source>
      <translation>垂直軸のタイトル</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_HOR_TITLE</source>
      <translation>水平軸のタイトル</translation>
    </message>
    <message>
      <source>PLOT2D_CURVE_TYPE_LINES</source>
      <translation>ライン</translation>
    </message>
    <message>
      <source>PLOT2D_MAX_INTERVALS</source>
      <translation>最大間隔</translation>
    </message>
    <message>
      <source>INF_AXES_Y_LEFT</source>
      <translation>左の Y 軸</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_TOP</source>
      <translation>トップ</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_VER_MAJOR</source>
      <translation>主な垂直</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_HOR_MAJOR</source>
      <translation>主な水平</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_VER_MINOR</source>
      <translation>セカンダリ垂直</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_HOR_MINOR</source>
      <translation>セカンダリ水平</translation>
    </message>
    <message>
      <source>PLOT2D_BACKGROUND_COLOR_LBL</source>
      <translation>背景色:</translation>
    </message>
    <message>
      <source>PLOT2D_SELECTION_COLOR_LBL</source>
      <translation>選択色:</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_MARKER_TLT</source>
      <translation>バイパス マーカー</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_LW_LBL</source>
      <translation>線の太さ</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_TS_LBL</source>
      <translation>サイズ チェック マーク付き</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_CL_LBL</source>
      <translation>色</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_LOGARITHMIC</source>
      <translation>対数</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_LEGEND</source>
      <translation>キャプションを表示します。</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_FONT</source>
      <translation>凡例のフォント</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_LINEAR</source>
      <translation>線形</translation>
    </message>
    <message>
      <source>PLOT2D_CURVE_TYPE_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>PLOT2D_CURVE_TYPE_SPLINE</source>
      <translation>スプライン</translation>
    </message>
    <message>
      <source>INF_AXES_Y_RIGHT</source>
      <translation>右の Y 軸</translation>
    </message>
    <message>
      <source>PLOT2D_MARKER_SIZE_LBL</source>
      <translation>マーカーのサイズ:</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_MAIN_TITLE</source>
      <translation>主なタイトル</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_GROUP</source>
      <translation>凡例</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION</source>
      <translation>凡例の位置</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_SYMBOL_TYPE</source>
      <translation>シンボルタイプ:</translation>
    </message>
    <message>
      <source>PLOT2D_MARKER_ABOVE_LINE</source>
      <translation>線の上のマーカー</translation>
    </message>
    <message>
      <source>PLOT2D_MARKER_ON_LINE</source>
      <translation>線上のマーカー</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_FONT_COLOR</source>
      <translation>凡例フォントの色:</translation>
    </message>
    <message>
      <source>PLOT2D_SELECTED_LEGEND_FONT_COLOR</source>
      <translation>ハイライト凡例フォントの色:</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_SetupCurveDlg</name>
    <message>
      <source>TLT_SETUP_CURVE</source>
      <translation>曲線を初期化します。</translation>
    </message>
    <message>
      <source>CURVE_LINE_WIDTH_LAB</source>
      <translation>線幅:</translation>
    </message>
    <message>
      <source>CURVE_LINE_TYPE_LAB</source>
      <translation>線種:</translation>
    </message>
    <message>
      <source>CURVE_COLOR_LAB</source>
      <translation>色：</translation>
    </message>
    <message>
      <source>CURVE_PREVIEW_LAB</source>
      <translation>プレビュー：</translation>
    </message>
    <message>
      <source>CURVE_MARKER_TYPE_LAB</source>
      <translation>マーカーの種類:</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_ViewWindow</name>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>表示をDump...</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パン</translation>
    </message>
    <message>
      <source>MNU_CLONE_VIEW</source>
      <translation>表示を複製</translation>
    </message>
    <message>
      <source>MNU_PRINT_VIEW</source>
      <translation>表示を印刷</translation>
    </message>
    <message>
      <source>POSTSCRIPT_FILES</source>
      <translation>PostScript ファイル (* .ps)</translation>
    </message>
    <message>
      <source>ENCAPSULATED_POSTSCRIPT_FILES</source>
      <translation>カプセル化された PostScript ファイル (*.eps)</translation>
    </message>
    <message>
      <source>PDF_FILES</source>
      <translation>PDF files (*.pdf)</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>表示の新しい中心の選択</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LINEAR_VER</source>
      <translation>垂直軸に沿ったリニアスケールモードへ表示を切り替え</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LINEAR_HOR</source>
      <translation>水平軸に沿ったリニアスケールモードへ表示の切り替え</translation>
    </message>
    <message>
      <source>CURVE_TYPE_POPUP</source>
      <translation>カーブタイプ</translation>
    </message>
    <message>
      <source>NORMALIZATION_TYPE_POPUP</source>
      <translation>正規化</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LINEAR_VER</source>
      <translation>垂直軸: リニア</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LINEAR_HOR</source>
      <translation>水平軸: リニア</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>パン</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CURVES_SPLINES</source>
      <translation>スプラインモードへ表示の切り替え</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>全表示</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>全表示</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LOGARITHMIC_HOR</source>
      <translation>水平軸: 対数</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LOGARITHMIC_VER</source>
      <translation>垂直軸: 対数</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバルパニング</translation>
    </message>
    <message>
      <source>DSC_CLONE_VIEW</source>
      <translation>アクティブシーンのための新規OCCビューワの作成</translation>
    </message>
    <message>
      <source>DSC_PRINT_VIEW</source>
      <translation>アクティブビューの印刷</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_SETTINGS</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_ANALYTICAL_CURVES</source>
      <translation>検量線</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_LMAX</source>
      <translation>左Y軸: 全体最大値の正規化</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_LMIN</source>
      <translation>左Y軸: 全体最小値の正規化</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_RMAX</source>
      <translation>右Y軸: 全体最大値の正規化</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_RMIN</source>
      <translation>右Y軸: 全体最小値の正規化</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CURVES_SPLINES</source>
      <translation>2Dスプラインカーブ</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LOGARITHMIC_HOR</source>
      <translation>水平軸に沿った対数スケーリングモードへ表示切り替え</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LOGARITHMIC_VER</source>
      <translation>垂直軸に沿った対数スケーリングモードへ表示切り替え</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CURVES_POINTS</source>
      <translation>点の作成</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域でフィット</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>領域でフィット</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CURVES_POINTS</source>
      <translation>点の作成</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CURVES_POINTS</source>
      <translation>点モードへ表示切り替え</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>アクティブビューを画像ファイルに保存</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_ANALYTICAL_CURVES</source>
      <translation>検量線プロパティ設定</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_LMAX</source>
      <translation>左Y軸による最大値正規化モードへ表示切り替え</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_LMIN</source>
      <translation>左Y軸による最小値正規化モードへ表示切り替え</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_RMAX</source>
      <translation>右Y軸による最大値正規化モードへ表示切り替え</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_RMIN</source>
      <translation>右側の Y 軸の最小の標準化の方法に、ビューを切り替える</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_SETTINGS</source>
      <translation>可視化を設定します。</translation>
    </message>
    <message>
      <source>SCALING_POPUP</source>
      <translation>スケール</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_FITDATA</source>
      <translation>間隔を調整します。</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_FITDATA</source>
      <translation>間隔を調整します。(&amp;R)</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_FITDATA</source>
      <translation>指定したデータ範囲を調整します。</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LOGARITHMIC_HOR</source>
      <translation>水平軸: 対数</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LOGARITHMIC_VER</source>
      <translation>垂直軸: 対数</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_LMIN</source>
      <translation>左の Y 軸: 最小</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_LMAX</source>
      <translation>左の Y 軸: 最大</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_RMIN</source>
      <translation>右の Y 軸: 最小</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_RMAX</source>
      <translation>右の Y 軸: 最大</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LINEAR_VER</source>
      <translation>垂直軸: 線形</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LINEAR_HOR</source>
      <translation>水平軸: 線形</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_SHOW_LEGEND</source>
      <translation>キャプションを表示します。(&amp;L)</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_SHOW_LEGEND</source>
      <translation>凡例を有効または無効</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_SHOW_LEGEND</source>
      <translation>キャプションを表示します。</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CURVES_SPLINES</source>
      <translation>スプラインを描画します。</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_SETTINGS</source>
      <translation>パラメーター(&amp;S)</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_ANALYTICAL_CURVES</source>
      <translation>分析曲線</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>表示操作</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CURVES_LINES</source>
      <translation>線を描</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CURVES_LINES</source>
      <translation>表示モードの行を変更します。</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CURVES_LINES</source>
      <translation>線を描く</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_Viewer</name>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>ビューを保存.</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CHANGE_BACKGROUND</source>
      <translation>背景を変更する.</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_ViewFrame</name>
    <message>
      <source>INF_COORDINATES</source>
      <translation>お問い合わせ: x: %1、y: %2</translation>
    </message>
    <message>
      <source>WRN_XLOG_NOT_ALLOWED</source>
      <translation>X 軸上非陽性値を持つポイントが検出されました。カテゴリの対数目盛は許可されていません。</translation>
    </message>
    <message>
      <source>WRN_YLOG_NOT_ALLOWED</source>
      <translation>Y 軸上非陽性値を持つポイントが検出されました。切片の対数目盛は許可されていません。</translation>
    </message>
    <message>
      <source>INF_COORDINATES_SOME_Y</source>
      <translation>お問い合わせ: x: %1、y: %2 ( %3 )</translation>
    </message>
  </context>
</TS>
