<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
<context>
    <name>@default</name>
    <message>
        <source>ICON_PLOT2D_GLOBALPAN</source>
        <translation>plot2d_glpan.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_CLONE_VIEW</source>
        <translation>plot2d_clone.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_CURVES_POINTS</source>
        <translation>plot2d_points.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_FIT_AREA</source>
        <translation>plot2d_fitarea.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_DUMP</source>
        <translation>plot2d_camera_dump.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_ZOOM</source>
        <translation>plot2d_zoom.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_MODE_LINEAR_VER</source>
        <translation>plot2d_linear_y.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_MODE_LINEAR_HOR</source>
        <translation>plot2d_linear.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_PAN</source>
        <translation>plot2d_pan.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_FIT_ALL</source>
        <translation>plot2d_fitall.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_MODE_LOGARITHMIC_HOR</source>
        <translation>plot2d_log.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_MODE_LOGARITHMIC_VER</source>
        <translation>plot2d_log_y.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_NORMALIZE_MODE_LMIN</source>
        <translation>plot2d_lmin_normalization.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_NORMALIZE_MODE_LMAX</source>
        <translation>plot2d_lmax_normalization.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_NORMALIZE_MODE_RMIN</source>
        <translation>plot2d_rmin_normalization.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_NORMALIZE_MODE_RMAX</source>
        <translation>plot2d_rmax_normalization.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_SETTINGS</source>
        <translation>plot2d_settings.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_ANALYTICAL_CURVES</source>
        <translation>plot2d_analytical_curve.png</translation>
    </message>    
    <message>
        <source>ICON_PLOT2D_CURVES_LINES</source>
        <translation>plot2d_lines.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_CURVES_SPLINES</source>
        <translation>plot2d_splines.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_SHOW_LEGEND</source>
        <translation>plot2d_legend.png</translation>
    </message>
    <message>
        <source>ICON_PLOT2D_PRINT</source>
        <translation>plot2d_print.png</translation>
    </message>
</context>
</TS>
