<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>PLOT2D_CURVE_TYPE_LBL</source>
      <translation>カーブの種類:</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>PLOT2D_SET_AS_DEFAULT_CHECK</source>
      <translation>設定を既定値として保存します。</translation>
    </message>
    <message>
      <source>TLT_SETUP_CURVE</source>
      <translation>セットアップ曲線</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>表示をダンプします.</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_HOR</source>
      <translation>水平軸:</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_TLT</source>
      <translation>正規化</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_MODE_MIN</source>
      <translation>最小限に正規化します。</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_MODE_MAX</source>
      <translation>最大に正規化します。</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_LEFT_AXIS</source>
      <translation>左 Y 軸:</translation>
    </message>
    <message>
      <source>PLOT2D_NORMALIZE_RIGHT_AXIS</source>
      <translation>右の Y 軸:</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_VER</source>
      <translation>垂直軸:</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パン</translation>
    </message>
    <message>
      <source>MNU_CLONE_VIEW</source>
      <translation>クローン ビュー</translation>
    </message>
    <message>
      <source>MNU_PRINT_VIEW</source>
      <translation>印刷レイアウト表示</translation>
    </message>
    <message>
      <source>POSTSCRIPT_FILES</source>
      <translation>PostScript ファイル (* .ps)</translation>
    </message>
    <message>
      <source>ENCAPSULATED_POSTSCRIPT_FILES</source>
      <translation>カプセル化された PostScript ファイル (*.eps)</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心の選択</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LINEAR_VER</source>
      <translation>スイッチのビューに垂直軸に沿って線形スケーリング モード</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LINEAR_HOR</source>
      <translation>スイッチを水平軸に沿った線形スケーリング モード表示します。</translation>
    </message>
    <message>
      <source>CURVE_LINE_WIDTH_LAB</source>
      <translation>線の幅:</translation>
    </message>
    <message>
      <source>CURVE_TYPE_POPUP</source>
      <translation>カーブの種類</translation>
    </message>
    <message>
      <source>NORMALIZATION_TYPE_POPUP</source>
      <translation>正規化</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LINEAR_VER</source>
      <translation>垂直軸: 線形</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LINEAR_HOR</source>
      <translation>水平軸: 線形</translation>
    </message>
    <message>
      <source>FIT_DATA_TLT</source>
      <translation>フィット データ範囲</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_TLT</source>
      <translation>グリッド/軸マーク</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>パン表示]</translation>
    </message>
    <message>
      <source>DASHDOT_LINE_LBL</source>
      <translation>DashDot</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CURVES_SPLINES</source>
      <translation>スプライン モードにスイッチ ビュー</translation>
    </message>
    <message>
      <source>INF_AXES_X</source>
      <translation>X 軸</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_TLT</source>
      <translation>スケール モード</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>ビュー フレーム内のすべてのオブジェクトに適合します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>すべてに適合します。</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LOGARITHMIC_HOR</source>
      <translation>水平軸: 対数</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_MODE_LOGARITHMIC_VER</source>
      <translation>縦軸： 対数</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバル パン</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>表示をダンプします</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_BOTTOM</source>
      <translation>下</translation>
    </message>
    <message>
      <source>INF_COORDINATES</source>
      <translation>座標: X:%1、Y:%2</translation>
    </message>
    <message>
      <source>DSC_CLONE_VIEW</source>
      <translation>新しい OCC ビューアーのアクティブなシーンを作成します。</translation>
    </message>
    <message>
      <source>DSC_PRINT_VIEW</source>
      <translation>アクティブなビューを印刷します。</translation>
    </message>
    <message>
      <source>DASH_LINE_LBL</source>
      <translation>ダッシュ</translation>
    </message>
    <message>
      <source>DTRIANGLE_MARKER_LBL</source>
      <translation>下向き三角形</translation>
    </message>
    <message>
      <source>UTRIANGLE_MARKER_LBL</source>
      <translation>上向き三角形</translation>
    </message>
    <message>
      <source>LTRIANGLE_MARKER_LBL</source>
      <translation>左の三角形</translation>
    </message>
    <message>
      <source>RTRIANGLE_MARKER_LBL</source>
      <translation>右向き三角形</translation>
    </message>
    <message>
      <source>RECTANGLE_MARKER_LBL</source>
      <translation>四角形</translation>
    </message>
    <message>
      <source>TLT_SETUP_PLOT2D_VIEW</source>
      <translation>プロット 2 d ビューの設定</translation>
    </message>
    <message>
      <source>CURVE_LINE_TYPE_LAB</source>
      <translation>線の種類:</translation>
    </message>
    <message>
      <source>CROSS_MARKER_LBL</source>
      <translation>クロス</translation>
    </message>
    <message>
      <source>XCROSS_MARKER_LBL</source>
      <translation>交差斜線</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_VER_TITLE</source>
      <translation>垂直軸のタイトル</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_HOR_TITLE</source>
      <translation>水平軸のタイトル</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_SETTINGS</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_ANALYTICAL_CURVES</source>
      <translation>分析カーブ</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_LMAX</source>
      <translation>左 Y 軸: 大域的最大値に正規化します。</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_LMIN</source>
      <translation>左 Y 軸: グローバル最小限に正規化します。</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_RMAX</source>
      <translation>右の Y 軸: 大域的最大値に正規化します。</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_NORMALIZE_MODE_RMIN</source>
      <translation>右の Y 軸: グローバル最小限に正規化します。</translation>
    </message>
    <message>
      <source>PLOT2D_CURVE_TYPE_LINES</source>
      <translation>行</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CURVES_SPLINES</source>
      <translation>スプラインを描画します。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LOGARITHMIC_HOR</source>
      <translation>スイッチを水平軸に沿って対数スケール モード表示します。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_MODE_LOGARITHMIC_VER</source>
      <translation>スイッチのビューに垂直軸に沿って対数スケール モード</translation>
    </message>
    <message>
      <source>PLOT2D_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.png *.jpg クリックした場合 if)</translation>
    </message>
    <message>
      <source>PLOT2D_MAX_INTERVALS</source>
      <translation>最大間隔</translation>
    </message>
    <message>
      <source>INF_AXES_Y_LEFT</source>
      <translation>軸 Y 左</translation>
    </message>
    <message>
      <source>CURVE_COLOR_LAB</source>
      <translation>色：</translation>
    </message>
    <message>
      <source>CURVE_PREVIEW_LAB</source>
      <translation>プレビュー：</translation>
    </message>
    <message>
      <source>DIAMOND_MARKER_LBL</source>
      <translation>ダイヤモンド</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_TOP</source>
      <translation>ページのトップへ</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CHANGE_BACKGROUND</source>
      <translation>背景の変更</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CHANGE_BACKGROUND</source>
      <translation>背景の変更.</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CHANGE_BACKGROUND</source>
      <translation>背景色の変更</translation>
    </message>
    <message>
      <source>SOLID_LINE_LBL</source>
      <translation>固体</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_VER_MAJOR</source>
      <translation>垂直メジャー</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_HOR_MAJOR</source>
      <translation>水平方向の主な</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_VER_MINOR</source>
      <translation>垂直方向のマイナー</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CURVES_POINTS</source>
      <translation>点を描画します。</translation>
    </message>
    <message>
      <source>PLOT2D_GRID_ENABLE_HOR_MINOR</source>
      <translation>水平方向のマイナー</translation>
    </message>
    <message>
      <source>PLOT2D_BACKGROUND_COLOR_LBL</source>
      <translation>背景色:</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_MARKER_TLT</source>
      <translation>偏差マーカー</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_LW_LBL</source>
      <translation>線の幅</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_TS_LBL</source>
      <translation>ティック サイズ</translation>
    </message>
    <message>
      <source>PLOT2D_DEVIATION_CL_LBL</source>
      <translation>色</translation>
    </message>
    <message>
      <source>WRN_XLOG_NOT_ALLOWED</source>
      <translation>非正横軸の値を持ついくつかのポイントが検出されました。横座標軸の対数スケールは許可されていません。</translation>
    </message>
    <message>
      <source>WRN_YLOG_NOT_ALLOWED</source>
      <translation>いくつかのポイントと負の座標値が検出されました。座標の軸の対数スケールは許可されていません。</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域ビュー フレームに合わせて</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>フィット エリア</translation>
    </message>
    <message>
      <source>DOT_LINE_LBL</source>
      <translation>ドット</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CURVES_POINTS</source>
      <translation>描画ポイント</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CURVES_POINTS</source>
      <translation>スイッチのビュー ポイント モードに</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_LOGARITHMIC</source>
      <translation>対数</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_POSITION_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>作業中のビューをイメージ ファイルに保存します</translation>
    </message>
    <message>
      <source>WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_LEGEND</source>
      <translation>凡例を表示します。</translation>
    </message>
    <message>
      <source>PLOT2D_LEGEND_FONT</source>
      <translation>凡例のフォント</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ビューをズームします。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_ANALYTICAL_CURVES</source>
      <translation>セットアップ分析曲線プロパティ</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_LMAX</source>
      <translation>左 Y 軸での最大正規化モードにスイッチを表示します。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_LMIN</source>
      <translation>左の Y 軸で最小正規化モードにスイッチを表示します。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_RMAX</source>
      <translation>右の Y 軸での最大正規化モードにスイッチを表示します。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_NORMALIZE_MODE_RMIN</source>
      <translation>右の Y 軸で最小正規化モードにスイッチを表示します。</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_SETTINGS</source>
      <translation>セットアップのプロパティを表示します。</translation>
    </message>
    <message>
      <source>INF_COORDINATES_SOME_Y</source>
      <translation>座標: X:%1、Y:%2 (%3)</translation>
    </message>
    <message>
      <source>SCALING_POPUP</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>PLOT2D_SCALE_MODE_LINEAR</source>
      <translation>線形</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_FITDATA</source>
      <translation>フィットの範囲</translation>
    </message>
    <message>
      <source>PLOT2D_CURVE_TYPE_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>PLOT2D_CURVE_TYPE_SPLINE</source>
      <translation>スプライン</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_FITDATA</source>
      <translation>フィット &amp; 範囲</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LOGARITHMIC_HOR</source>
      <translation>水平軸: 対数</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LOGARITHMIC_VER</source>
      <translation>縦軸： 対数</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_LMIN</source>
      <translation>左 Y 軸: 最小</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_LMAX</source>
      <translation>左 Y 軸: 最大</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_RMIN</source>
      <translation>右の Y 軸: 最小</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_NORMALIZE_MODE_RMAX</source>
      <translation>右の Y 軸: 最大</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_FITDATA</source>
      <translation>指定されたデータ範囲に収まるビュー</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LINEAR_VER</source>
      <translation>垂直軸: 線形</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_MODE_LINEAR_HOR</source>
      <translation>水平軸: 線形</translation>
    </message>
    <message>
      <source>NONE_MARKER_LBL</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できません。</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_SHOW_LEGEND</source>
      <translation>&amp; に凡例を表示</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_SHOW_LEGEND</source>
      <translation>伝説の有効/無効にします</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_SHOW_LEGEND</source>
      <translation>凡例を表示します。</translation>
    </message>
    <message>
      <source>INF_AXES_Y_RIGHT</source>
      <translation>軸 Y 右</translation>
    </message>
    <message>
      <source>DAHSDOTDOT_LINE_LBL</source>
      <translation>DashDotDot</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CURVES_SPLINES</source>
      <translation>スプラインを描画します。</translation>
    </message>
    <message>
      <source>CURVE_MARKER_TYPE_LAB</source>
      <translation>マーカーの種類:</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_SETTINGS</source>
      <translation>&amp; 設定</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_ANALYTICAL_CURVES</source>
      <translation>分析カーブ</translation>
    </message>
    <message>
      <source>CIRCLE_MARKER_LBL</source>
      <translation>円</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>[操作の表示</translation>
    </message>
    <message>
      <source>NONE_LINE_LBL</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>PLOT2D_MARKER_SIZE_LBL</source>
      <translation>マーカーのサイズ:</translation>
    </message>
    <message>
      <source>PLOT2D_ENABLE_MAIN_TITLE</source>
      <translation>メイン ・ タイトル</translation>
    </message>
    <message>
      <source>TOT_PLOT2D_CURVES_LINES</source>
      <translation>線を描く</translation>
    </message>
    <message>
      <source>PRP_PLOT2D_CURVES_LINES</source>
      <translation>スイッチのビューに行モード</translation>
    </message>
    <message>
      <source>MEN_PLOT2D_CURVES_LINES</source>
      <translation>線を描く</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_FitDataDlg</name>
    <message>
      <source>FIT_HORIZONTAL</source>
      <translation>水平方向に収まる</translation>
    </message>
    <message>
      <source>MIN_VALUE_LAB</source>
      <translation>Min:</translation>
    </message>
    <message>
      <source>VERTICAL_AXIS</source>
      <translation>垂直軸</translation>
    </message>
    <message>
      <source>MAX_VALUE_LAB</source>
      <translation>最大:</translation>
    </message>
    <message>
      <source>HORIZONTAL_AXIS</source>
      <translation>水平軸</translation>
    </message>
    <message>
      <source>VERTICAL_LEFT_AXIS</source>
      <translation>垂直左軸</translation>
    </message>
    <message>
      <source>FIT_ALL</source>
      <translation>フィット感の両方</translation>
    </message>
    <message>
      <source>VERTICAL_RIGHT_AXIS</source>
      <translation>垂直右軸</translation>
    </message>
    <message>
      <source>FIT_VERTICAL</source>
      <translation>縦します。</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_ViewManager</name>
    <message>
      <source>PLOT2D_VIEW_TITLE</source>
      <translation>Plot2d シーン:%M - ビューアー:%V</translation>
    </message>
    <message>
      <source>PREF_GROUP_PLOT2DVIEWER</source>
      <translation>Plot2d ビューアー</translation>
    </message>
    <message>
      <source>PREF_SHOW_LEGEND</source>
      <translation>凡例を表示します。</translation>
    </message>
    <message>
      <source>PREF_LEGEND_POSITION</source>
      <translation>凡例の位置:</translation>
    </message>
    <message>
      <source>PREF_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>PREF_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>PREF_TOP</source>
      <translation>ページのトップへ</translation>
    </message>
    <message>
      <source>PREF_BOTTOM</source>
      <translation>下</translation>
    </message>
    <message>
      <source>PREF_CURVE_TYPE</source>
      <translation>カーブの種類:</translation>
    </message>
    <message>
      <source>PREF_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>PREF_LINES</source>
      <translation>行</translation>
    </message>
    <message>
      <source>PREF_SPLINE</source>
      <translation>スプライン</translation>
    </message>
    <message>
      <source>PREF_MARKER_SIZE</source>
      <translation>マーカーのサイズ:</translation>
    </message>
    <message>
      <source>PREF_LINEAR</source>
      <translation>線形</translation>
    </message>
    <message>
      <source>PREF_LOGARITHMIC</source>
      <translation>対数</translation>
    </message>
    <message>
      <source>PREF_HOR_AXIS_SCALE</source>
      <translation>水平軸スケール:</translation>
    </message>
    <message>
      <source>PREF_VERT_AXIS_SCALE</source>
      <translation>垂直軸スケール:</translation>
    </message>
    <message>
      <source>PREF_VIEWER_BACKGROUND</source>
      <translation>背景色</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_AnalyticalCurveDlg</name>
    <message>
      <source>ANALYTICAL_CURVE_TLT</source>
      <translation>分析カーブ プロパティ</translation>
    </message>
    <message>
      <source>AC_CURVE_PARAMS</source>
      <translation>曲線のパラメーター</translation>
    </message>
    <message>
      <source>AC_CURVE_PROPS</source>
      <translation>曲線のプロパティ</translation>
    </message>
    <message>
      <source>AC_FORMULA</source>
      <translation>でき =</translation>
    </message>
    <message>
      <source>AC_NB_INTERVALS</source>
      <translation>注意間隔</translation>
    </message>
    <message>
      <source>AC_AUTO_ASSIGN</source>
      <translation>自動割り当て</translation>
    </message>
    <message>
      <source>AC_MARKER_TYPE</source>
      <translation>マーカーの種類</translation>
    </message>
    <message>
      <source>AC_LINE_TYPE</source>
      <translation>線の種類</translation>
    </message>
    <message>
      <source>AC_LINE_WIDTH</source>
      <translation>線の幅</translation>
    </message>
    <message>
      <source>AC_CURVE_COLOR</source>
      <translation>曲線の色</translation>
    </message>
    <message>
      <source>AC_ADD_BTN</source>
      <translation>曲線を追加します。</translation>
    </message>
    <message>
      <source>AC_REM_BTN</source>
      <translation>カーブを削除します。</translation>
    </message>
    <message>
      <source>AC_OK_BTN</source>
      <translation>わかりました</translation>
    </message>
    <message>
      <source>AC_APPLY_BTN</source>
      <translation>適用</translation>
    </message>
    <message>
      <source>AC_CANT_CALCULATE</source>
      <translation>曲線を算出することはできません。入力パラメーターをチェックしてください ！</translation>
    </message>
    <message>
      <source>AC_CLOSE_BTN</source>
      <translation>&amp; 閉じる</translation>
    </message>
    <message>
      <source>AC_HELP_BTN</source>
      <translation>ヘルプ</translation>
    </message>
  </context>
  <context>
    <name>Plot2d_SetupCurveScaleDlg</name>
    <message>
      <source>TLT_SETUP_CURVE_SCALE</source>
      <translation>スケールを curve(s) します。</translation>
    </message>
    <message>
      <source>CURVE_SCALE_FACTOR</source>
      <translation>尺度係数</translation>
    </message>
  </context>
</TS>
