<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>PyViewer_ViewManager</name>
    <message>
      <source>PYVIEWER_VIEW_TITLE</source>
      <translation>Python viewer:%M - viewer:%V</translation>
    </message>
  </context>
  <context>
    <name>PyViewer_ViewWindow</name>
    <message>
      <source>NAME_PYEDITOR</source>
      <translation>Python Editor</translation>
    </message>
    <message>
      <source>ACT_NEW</source>
      <translation>新規</translation>
    </message>
    <message>
      <source>TTP_NEW</source>
      <translation>新規</translation>
    </message>
    <message>
      <source>DSC_NEW</source>
      <translation>新規 python ファイルの作成</translation>
    </message>
    <message>
      <source>ACT_OPEN</source>
      <translation>開く</translation>
    </message>
    <message>
      <source>TTP_OPEN</source>
      <translation>開く</translation>
    </message>
    <message>
      <source>DSC_OPEN</source>
      <translation>存在する python ファイルを開く</translation>
    </message>
    <message>
      <source>ACT_SAVE</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>TTP_SAVE</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>DSC_SAVE</source>
      <translation>python ドキュメントをディスクに保存</translation>
    </message>
    <message>
      <source>ACT_SAVEAS</source>
      <translation>別名保存</translation>
    </message>
    <message>
      <source>TTP_SAVEAS</source>
      <translation>別名保存</translation>
    </message>
    <message>
      <source>DSC_SAVEAS</source>
      <translation>新しい名前で python ドキュメントを保存</translation>
    </message>
    <message>
      <source>ACT_UNDO</source>
      <translation>元に戻す</translation>
    </message>
    <message>
      <source>TTP_UNDO</source>
      <translation>元に戻す</translation>
    </message>
    <message>
      <source>DSC_UNDO</source>
      <translation>最後の操作を元に戻す</translation>
    </message>
    <message>
      <source>ACT_REDO</source>
      <translation>やり直し</translation>
    </message>
    <message>
      <source>TTP_REDO</source>
      <translation>やり直し</translation>
    </message>
    <message>
      <source>DSC_REDO</source>
      <translation>最後の操作をやり直す</translation>
    </message>
    <message>
      <source>ACT_CUT</source>
      <translation>カット</translation>
    </message>
    <message>
      <source>TTP_CUT</source>
      <translation>カット</translation>
    </message>
    <message>
      <source>DSC_CUT</source>
      <translation>現在選択中の内容をクリップボードにカット</translation>
    </message>
    <message>
      <source>ACT_COPY</source>
      <translation>コピー</translation>
    </message>
    <message>
      <source>TTP_COPY</source>
      <translation>コピー</translation>
    </message>
    <message>
      <source>DSC_COPY</source>
      <translation>現在選択中の内容をクリップボードにコピー</translation>
    </message>
    <message>
      <source>ACT_PASTE</source>
      <translation>ペースト</translation>
    </message>
    <message>
      <source>TTP_PASTE</source>
      <translation>ペースト</translation>
    </message>
    <message>
      <source>DSC_PASTE</source>
      <translation>クリップボードの内容を現在の選択にペースト</translation>
    </message>
    <message>
      <source>ACT_DELETE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>TTP_DELETE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>DSC_DELETE</source>
      <translation>現在選択中の内容を削除</translation>
    </message>
    <message>
      <source>ACT_SELECT_ALL</source>
      <translation>すべて選択</translation>
    </message>
    <message>
      <source>TTP_SELECT_ALL</source>
      <translation>すべて選択</translation>
    </message>
    <message>
      <source>DSC_SELECT_ALL</source>
      <translation>すべての内容を選択</translation>
    </message>
    <message>
      <source>ACT_PREFERENCES</source>
      <translation>環境設定</translation>
    </message>
    <message>
      <source>TTP_PREFERENCES</source>
      <translation>環境設定</translation>
    </message>
    <message>
      <source>DSC_PREFERENCES</source>
      <translation>環境設定ボックスの表示</translation>
    </message>
    <message>
      <source>ACT_HELP</source>
      <translation>ヘルプ</translation>
    </message>
    <message>
      <source>TTP_HELP</source>
      <translation>ヘルプ</translation>
    </message>
    <message>
      <source>DSC_HELP</source>
      <translation>ヘルプ</translation>
    </message>
    <message>
      <source>TOOLBAR_LABEL</source>
      <translation>操作の編集</translation>
    </message>
    <message>
      <source>TIT_PY_FILES</source>
      <translation>ã..ã.¡ã.¤ã.« Python</translation>
    </message>
    <message>
      <source>TIT_DLG_OPEN</source>
      <translation>ファイルを開く</translation>
    </message>
    <message>
      <source>TIT_DLG_SAVE</source>
      <translation>ファイルを保存</translation>
    </message>
    <message>
      <source>WRN_SAVE_FILE</source>
      <translation>ドキュメントは修正済みです。&lt;br&gt;変更を保存しますか？</translation>
    </message>
    <message>
      <source>WRN_READ_FILE</source>
      <translation>Cannot read file %1:\n%2.</translation>
    </message>
    <message>
      <source>WRN_WRITE_FILE</source>
      <translation>Cannot write file %1:\n%2.</translation>
    </message>
    <message>
      <source>NONAME</source>
      <translation>Noname.py</translation>
    </message>
  </context>
</TS>
