<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>転送</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>上から見る</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パンニング</translation>
    </message>
    <message>
      <source>MNU_CLONE_VIEW</source>
      <translation>ビューの複製</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRE</source>
      <translation>表示/非表示の三面体をシーンに</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRE</source>
      <translation>軸の表示/非表示</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>トップ</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心地の選択</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ステージの中心の周りを回転します。</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>ビューを移動します。</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>左側のビュー</translation>
    </message>
    <message>
      <source>DSC_SHOOT_VIEW</source>
      <translation>状態の現在のシーンを保存し、一覧に追加</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>すべてのオブジェクトを表示します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>すべて表示</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>正面</translation>
    </message>
    <message>
      <source>MNU_ROTATIONPOINTGRAVITY_VIEW</source>
      <translation>回転点: 重力の中心部</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバルパンニング</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>ビューを保存します。</translation>
    </message>
    <message>
      <source>DSC_CLIPPING</source>
      <translation>クリップ平面を定義します。</translation>
    </message>
    <message>
      <source>DSC_CLONE_VIEW</source>
      <translation>現在のステージの可視化の新しいウィンドウを開く</translation>
    </message>
    <message>
      <source>INF_APP_SHOOT_VIEW</source>
      <translation>場面を覚えています。</translation>
    </message>
    <message>
      <source>MNU_CLIPPING</source>
      <translation>断面</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>背面</translation>
    </message>
    <message>
      <source>MNU_SHOOT_VIEW</source>
      <translation>ビューの保存</translation>
    </message>
    <message>
      <source>DSC_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>シーンになってポイントを変更します。</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>Bottom</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>復元</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>左</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>右側のビュー</translation>
    </message>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>表示を左に</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>右のビューを回転させる</translation>
    </message>
    <message>
      <source>MNU_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>回転の基準点を変更</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域にビューを表示します。</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>表示エリア</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>下から表示します。</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>現在のビューをイメージ ファイルに保存します。</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>MNU_ROTATIONPOINT000_VIEW</source>
      <translation>回転点: (0,0,0)</translation>
    </message>
    <message>
      <source>MNU_ROTATIONPOINTSELECTED_VIEW</source>
      <translation>回転点: ユーザーが選択したポイント</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>ビューのポイントを復元します。</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できませんでした。</translation>
    </message>
    <message>
      <source>DSC_PRESETS_VIEW</source>
      <translation>状態の復元は、現在のシーンの記憶</translation>
    </message>
    <message>
      <source>MNU_PRESETS_VIEW</source>
      <translation>ビューの読み込み</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>左回転</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>右回転</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>法律</translation>
    </message>
    <message>
      <source>INF_APP_PRESETS_VIEW</source>
      <translation>シーンを復元します。</translation>
    </message>
    <message>
      <source>LBL_XYTOOLBAR_LABEL</source>
      <translation>XY 表示での操作</translation>
    </message>
    <message>
      <source>LBL_XZTOOLBAR_LABEL</source>
      <translation>XZ ビューの操作</translation>
    </message>
    <message>
      <source>LBL_YZTOOLBAR_LABEL</source>
      <translation>YZ ビューの操作</translation>
    </message>
    <message>
      <source>LBL_3DTOOLBAR_LABEL</source>
      <translation>3D ビューの操作</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>背面図</translation>
    </message>
    <message>
      <source>DSC_SCALING</source>
      <translation>座標のスケールの軸を変更します。</translation>
    </message>
    <message>
      <source>MNU_SCALING</source>
      <translation>スケールを変更します。</translation>
    </message>
    <message>
      <source>DSC_GRADUATED_AXES</source>
      <translation>目盛付軸</translation>
    </message>
    <message>
      <source>MNU_GRADUATED_AXES</source>
      <translation>軸に目盛り付け</translation>
    </message>
    <message>
      <source>DSC_AMBIENT</source>
      <translation>アンビエント ライトを表示します。</translation>
    </message>
    <message>
      <source>MNU_AMBIENT</source>
      <translation>アンビエント ライトを表示します。</translation>
    </message>
    <message>
      <source>DSC_STYLE_SWITCH</source>
      <translation>相互作用のスタイルを変更します。</translation>
    </message>
    <message>
      <source>MNU_STYLE_SWITCH</source>
      <translation>相互作用のスタイルを変更します。</translation>
    </message>
    <message>
      <source>DSC_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルを変更します。</translation>
    </message>
    <message>
      <source>MNU_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルを変更します。</translation>
    </message>
    <message>
      <source>DSC_ENABLE_PRESELECTION</source>
      <translation>DSC_ENABLE_PRESELECTION</translation>
    </message>
    <message>
      <source>MNU_ENABLE_PRESELECTION</source>
      <translation>MNU_ENABLE_PRESELECTION</translation>
    </message>
    <message>
      <source>DSC_ENABLE_SELECTION</source>
      <translation>DSC_ENABLE_SELECTION</translation>
    </message>
    <message>
      <source>MNU_ENABLE_SELECTION</source>
      <translation>MNU_ENABLE_SELECTION</translation>
    </message>
    <message>
      <source>OCC_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp (*.png) *.png *.jpg *.jpeg *.eps 年 .ps)</translation>
    </message>
    <message>
      <source>OCC_TEXTURE_FILES</source>
      <translation>ファイル (*.bmp, *.gif *.pix *.xwd *.rgb ※ .rs）</translation>
    </message>
    <message>
      <source>DSC_MAXIMIZE_VIEW</source>
      <translation>ビューを最大化します。</translation>
    </message>
    <message>
      <source>DSC_MINIMIZE_VIEW</source>
      <translation>ビューを最小化します。</translation>
    </message>
    <message>
      <source>MNU_MAXIMIZE_VIEW</source>
      <translation>最大化します。</translation>
    </message>
    <message>
      <source>MNU_MINIMIZE_VIEW</source>
      <translation>最小化する</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_CreateRestoreViewDlg</name>
    <message>
      <source>CAPTION</source>
      <translation>表示を元に戻す</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_SetRotationPointDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点を設定</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>回転中心設定</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ビューで、項目を選択します。</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_ViewManager</name>
    <message>
      <source>OCC_VIEW_TITLE</source>
      <translation>シーン OCC: %M - ビューアー: %V</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>ビューを保存します。</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景を変更</translation>
    </message>
    <message>
      <source>MEN_CHANGE_IMAGE</source>
      <translation>背景画像を設定/変更...</translation>
    </message>
    <message>
      <source>SELECT_IMAGE</source>
      <translation>画像を選択します。</translation>
    </message>
    <message>
      <source>CENTERED</source>
      <translation>中心のモード</translation>
    </message>
    <message>
      <source>TILED</source>
      <translation>テンキー モード</translation>
    </message>
    <message>
      <source>STRETCHED</source>
      <translation>ストレッチ モード</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>グラデーションの 2 番目の角</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目の角勾配</translation>
    </message>
    <message>
      <source>GT_FORTHCORNERGRADIENT</source>
      <translation>第 4 コーナー グラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>ファイル (*.bmp, *.gif *.pix *.xwd *.rgb ※ .rs）</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_AxialScaleDlg</name>
    <message>
      <source>DLG_SCALING</source>
      <translation>スケールの変更</translation>
    </message>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
  </context>
</TS>
