<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>フロント</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>表示をダンプします</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>トップ ビュー</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パン</translation>
    </message>
    <message>
      <source>MNU_CLONE_VIEW</source>
      <translation>クローン ビュー</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRE</source>
      <translation>三面体を現在のビューの表示/非表示</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRE</source>
      <translation>三面体の表示/非表示</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>ページのトップへ</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心の選択</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ビューのポイント シーンの中心の周りの回転</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>パン表示]</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>左ビュー</translation>
    </message>
    <message>
      <source>DSC_SHOOT_VIEW</source>
      <translation>作業中のビューの状態を記憶し、それをリストに追加します</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>ビュー フレーム内のすべてのオブジェクトに適合します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>すべてに適合します。</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>正面から見た図</translation>
    </message>
    <message>
      <source>MNU_ROTATIONPOINTGRAVITY_VIEW</source>
      <translation>回転ポイント: 重力のセンター</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバル パン</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>表示をダンプします</translation>
    </message>
    <message>
      <source>DSC_CLIPPING</source>
      <translation>クリップ平面を設定します。</translation>
    </message>
    <message>
      <source>DSC_CLONE_VIEW</source>
      <translation>新しい OCC ビューアーのアクティブなシーンを作成します。</translation>
    </message>
    <message>
      <source>INF_APP_SHOOT_VIEW</source>
      <translation>ビューを記憶します。</translation>
    </message>
    <message>
      <source>MNU_CLIPPING</source>
      <translation>クリッピング</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>戻る</translation>
    </message>
    <message>
      <source>MNU_SHOOT_VIEW</source>
      <translation>ビューを記憶します。</translation>
    </message>
    <message>
      <source>DSC_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>回転の周り実行ポイントを変更します。</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>下</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>リセット</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>左</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>右側のビュー</translation>
    </message>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>ビューを反時計回りに回転します。</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>ビューを時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>変更回転ポイント</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域ビュー フレームに合わせて</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>フィット エリア</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>底面図</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>作業中のビューをイメージ ファイルに保存します</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ビューをズームします。</translation>
    </message>
    <message>
      <source>MNU_ROTATIONPOINT000_VIEW</source>
      <translation>回転点: (0,0,0)</translation>
    </message>
    <message>
      <source>MNU_ROTATIONPOINTSELECTED_VIEW</source>
      <translation>回転点: ユーザーが選択したポイント</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>リセット ビュー ポイント</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できません。</translation>
    </message>
    <message>
      <source>DSC_PRESETS_VIEW</source>
      <translation>記憶の状態、アクティブなビューの選択</translation>
    </message>
    <message>
      <source>MNU_PRESETS_VIEW</source>
      <translation>ビューを復元します。</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>反時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>右</translation>
    </message>
    <message>
      <source>INF_APP_PRESETS_VIEW</source>
      <translation>ビューを復元します。</translation>
    </message>
    <message>
      <source>LBL_XYTOOLBAR_LABEL</source>
      <translation>XY 表示操作</translation>
    </message>
    <message>
      <source>LBL_XZTOOLBAR_LABEL</source>
      <translation>XZ ビューの操作</translation>
    </message>
    <message>
      <source>LBL_YZTOOLBAR_LABEL</source>
      <translation>YZ ビューの操作</translation>
    </message>
    <message>
      <source>LBL_3DTOOLBAR_LABEL</source>
      <translation>3 D ビューの操作</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>背面図</translation>
    </message>
    <message>
      <source>DSC_SCALING</source>
      <translation>軸の目盛を変更します。</translation>
    </message>
    <message>
      <source>MNU_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>DSC_GRADUATED_AXES</source>
      <translation>卒業軸</translation>
    </message>
    <message>
      <source>MNU_GRADUATED_AXES</source>
      <translation>卒業軸</translation>
    </message>
    <message>
      <source>DSC_AMBIENT</source>
      <translation>切り替えのみの周囲の光を維持します。</translation>
    </message>
    <message>
      <source>MNU_AMBIENT</source>
      <translation>切り替えのみの周囲の光を維持します。</translation>
    </message>
    <message>
      <source>DSC_STYLE_SWITCH</source>
      <translation>相互作用のスタイルのスイッチ</translation>
    </message>
    <message>
      <source>MNU_STYLE_SWITCH</source>
      <translation>相互作用のスタイルのスイッチ</translation>
    </message>
    <message>
      <source>DSC_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルのスイッチ</translation>
    </message>
    <message>
      <source>MNU_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルのスイッチ</translation>
    </message>
    <message>
      <source>OCC_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.png *.jpg クリックした場合 if *.eps * .ps)</translation>
    </message>
    <message>
      <source>OCC_TEXTURE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.gif *.pix *.xwd *.rgb * .rs)</translation>
    </message>
    <message>
      <source>DSC_MAXIMIZE_VIEW</source>
      <translation>ビューを最大化します。</translation>
    </message>
    <message>
      <source>DSC_MINIMIZE_VIEW</source>
      <translation>ビューを最小化します。</translation>
    </message>
    <message>
      <source>MNU_MAXIMIZE_VIEW</source>
      <translation>最大化します。</translation>
    </message>
    <message>
      <source>MNU_MINIMIZE_VIEW</source>
      <translation>最小限に抑える</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_CreateRestoreViewDlg</name>
    <message>
      <source>CAPTION</source>
      <translation>ビューを復元します。</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_SetRotationPointDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点に設定します。</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>回転ポイントを設定</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ポイントのビューから選択</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_ViewManager</name>
    <message>
      <source>OCC_VIEW_TITLE</source>
      <translation>OCC シーン:%M - ビューアー:%V</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>表示をダンプします.</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示します。</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景の変更.</translation>
    </message>
    <message>
      <source>MEN_CHANGE_IMAGE</source>
      <translation>背景画像を設定/変更.</translation>
    </message>
    <message>
      <source>SELECT_IMAGE</source>
      <translation>イメージを選択します.</translation>
    </message>
    <message>
      <source>CENTERED</source>
      <translation>モードを中心としました。</translation>
    </message>
    <message>
      <source>TILED</source>
      <translation>タイル張りのモードで</translation>
    </message>
    <message>
      <source>STRETCHED</source>
      <translation>ストレッチ モードで</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>2 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_FORTHCORNERGRADIENT</source>
      <translation>4 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.gif *.pix *.xwd *.rgb * .rs)</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_AxialScaleDlg</name>
    <message>
      <source>DLG_SCALING</source>
      <translation>軸のスケーリング</translation>
    </message>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
  </context>
</TS>
