<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
<context>
    <name>@default</name>
    <message>
        <source>ICON_OCCVIEWER_VIEW_GLOBALPAN</source>
        <translation>occ_view_glpan.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_CLIPPING_PRESSED</source>
        <translation>occ_view_clipping_pressed.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_FITAREA</source>
        <translation>occ_view_fitarea.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_FITSELECTION</source>
        <translation>occ_view_fitselection.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_CLONE_VIEW</source>
        <translation>occ_view_clone.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_PRESETS_VIEW</source>
        <translation>occ_view_presets.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_TOP</source>
        <translation>occ_view_top.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_PAN</source>
        <translation>occ_view_pan.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_SHOOT_VIEW</source>
        <translation>occ_view_shoot.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_ROTATION_POINT</source>
        <translation>occ_view_rotation_point.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_DUMP</source>
        <translation>occ_view_camera_dump.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_BACK</source>
        <translation>occ_view_back.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_ZOOM</source>
        <translation>occ_view_zoom.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_LEFT</source>
        <translation>occ_view_left.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_FITALL</source>
        <translation>occ_view_fitall.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_BOTTOM</source>
        <translation>occ_view_bottom.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_ROTATE</source>
        <translation>occ_view_rotate.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_FRONT</source>
        <translation>occ_view_front.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_RESET</source>
        <translation>occ_view_reset.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_RIGHT</source>
        <translation>occ_view_right.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_CLOCKWISE</source>
        <translation>occ_view_clockwise.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_ANTICLOCKWISE</source>
        <translation>occ_view_anticlockwise.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_CLIPPING</source>
        <translation>occ_view_clipping.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_VIEW_TRIHEDRON</source>
        <translation>occ_view_triedre.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_SCALING</source>
        <translation>occ_view_scaling.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_GRADUATED_AXES</source>
        <translation>occ_view_graduated_axes.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_AMBIENT</source>
        <translation>occ_view_ambient.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_STYLE_SWITCH</source>
        <translation>occ_view_style_switch.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_ZOOMING_STYLE_SWITCH</source>
        <translation>occ_view_zooming_style_switch.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_MAXIMIZE</source>
        <translation>occ_view_maximized.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_MINIMIZE</source>
        <translation>occ_view_minimized.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_RETURN_3D_VIEW</source>
        <translation>occ_view_return_3d_view.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_PRESELECTION</source>
        <translation>occ_view_preselection.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_SELECTION</source>
        <translation>occ_view_selection.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_ORTHOGRAPHIC</source>
        <translation>occ_view_orthographic.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_PERSPECTIVE</source>
        <translation>occ_view_perspective.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_STEREO</source>
        <translation>occ_view_stereo.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_RAY_TRACING</source>
        <translation>occ_view_ray_tracing.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_ENV_TEXTURE</source>
        <translation>occ_view_env_texture.png</translation>
    </message>
    <message>
        <source>ICON_OCCVIEWER_LIGHT_SOURCE</source>
        <translation>occ_view_light_source.png</translation>
    </message>
</context>
</TS>
