<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <!-- used in GEOM module: to be moved there? -->
      <source>OCC_TEXTURE_FILES</source>
      <translatorcomment>Update to new supported format (see OCCT Image_AlienPixMap documentation)</translatorcomment>
      <translation>イメージファイル (*.bmp *.gif *.pix *.xwd *.rgb *.rs)</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_ViewWindow</name>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>正面</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>正面</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>上面</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>上から見る</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>シーンを保存します。</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>現在のシーンをイメージ ファイルに保存します。</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>並進移動</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>ビューを移動します。</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバルパンニング</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心地の選択</translation>
    </message>
    <message>
      <source>MNU_CLONE_VIEW</source>
      <translation>ビューの複製</translation>
    </message>
    <message>
      <source>DSC_CLONE_VIEW</source>
      <translation>現在のステージの可視化の新しいウィンドウを開く</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRE</source>
      <translation>軸の表示/非表示</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRE</source>
      <translation>表示/非表示の三面体をシーンに</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ステージの中心の周りを回転します。</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>左側面</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>左側のビュー</translation>
    </message>
    <message>
      <source>MNU_SHOOT_VIEW</source>
      <translation>ビューの保存</translation>
    </message>
    <message>
      <source>DSC_SHOOT_VIEW</source>
      <translation>状態の現在のシーンを保存し、一覧に追加</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>全体表示</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>すべてのオブジェクトを表示するには、シーンを</translation>
    </message>
    <message>
      <source>MNU_CLIPPING</source>
      <translation>断面</translation>
    </message>
    <message>
      <source>DSC_CLIPPING</source>
      <translation>クリップ平面を定義します。</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>背面</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>背面図</translation>
    </message>
    <message>
      <source>MNU_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>回転の基準点を変更</translation>
    </message>
    <message>
      <source>DSC_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>シーンになってポイントを変更します。</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>底面</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>下から表示します。</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>表示リセット</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>ビューのポイントを復元します。</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>右側面</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>右側のビュー</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>左回転</translation>
    </message>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>表示を左に</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>右回転</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>右のビューを回転させる</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>表示エリア</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>彼の党をボックスで選択を表示するには、ステージのサイズを変更します。</translation>
    </message>
    <message>
      <source>MNU_FITSELECTION</source>
      <translation>選択をフィット</translation>
    </message>
    <message>
      <source>DSC_FITSELECTION</source>
      <translation>ビューフレームの内側にある選択されたすべてのオブジェクトをフィット</translation>
    </message>
    <message>
      <source>MNU_PRESETS_VIEW</source>
      <translation>ビューの読み込み</translation>
    </message>
    <message>
      <source>DSC_PRESETS_VIEW</source>
      <translation>状態の復元は、現在のシーンの記憶</translation>
    </message>
    <message>
      <source>MNU_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>DSC_SCALING</source>
      <translation>座標のスケールの軸を変更します。</translation>
    </message>
    <message>
      <source>MNU_GRADUATED_AXES</source>
      <translation>目盛付軸</translation>
    </message>
    <message>
      <source>DSC_GRADUATED_AXES</source>
      <translation>目盛付軸</translation>
    </message>
    <message>
      <source>MNU_AMBIENT</source>
      <translation>アンビエント ライトを表示します。</translation>
    </message>
    <message>
      <source>DSC_AMBIENT</source>
      <translation>環境光のみの表示</translation>
    </message>
    <message>
      <source>MNU_STYLE_SWITCH</source>
      <translation>相互作用のスタイルを変更します。</translation>
    </message>
    <message>
      <source>DSC_STYLE_SWITCH</source>
      <translation>相互作用のスタイルを変更します。</translation>
    </message>
    <message>
      <source>MNU_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルを変更します。</translation>
    </message>
    <message>
      <source>DSC_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルを変更します。</translation>
    </message>
    <message>
      <source>MNU_ENABLE_PRESELECTION</source>
      <translation>予選の有効/無効にします。</translation>
    </message>
    <message>
      <source>DSC_ENABLE_PRESELECTION</source>
      <translation>予選の有効/無効にします。</translation>
    </message>
    <message>
      <source>MNU_ENABLE_SELECTION</source>
      <translation>選択を有効/無効にします。</translation>
    </message>
    <message>
      <source>DSC_ENABLE_SELECTION</source>
      <translation>選択を有効/無効にします。</translation>
    </message>
    <message>
      <source>MNU_MAXIMIZE_VIEW</source>
      <translation>ビューの最大化</translation>
    </message>
    <message>
      <source>DSC_MAXIMIZE_VIEW</source>
      <translation>ビューの最大化</translation>
    </message>
    <message>
      <source>MNU_MINIMIZE_VIEW</source>
      <translation>ビューの最小化</translation>
    </message>
    <message>
      <source>DSC_MINIMIZE_VIEW</source>
      <translation>ビューの最小化</translation>
    </message>
    <message>
      <source>MNU_RETURN_3D_VIEW</source>
      <translation>3D に戻る</translation>
    </message>
    <message>
      <source>DSC_RETURN_3D_VIEW</source>
      <translation>3D view に戻る</translation>
    </message>
    <message>
      <source>MNU_RAY_TRACING</source>
      <translation>レイトレース</translation>
    </message>
    <message>
      <source>DSC_RAY_TRACING</source>
      <translation>レイトレース</translation>
    </message>
    <message>
      <source>MNU_ENV_TEXTURE</source>
      <translation>環境テキスチャ</translation>
    </message>
    <message>
      <source>DSC_ENV_TEXTURE</source>
      <translation>環境テキスチャ</translation>
    </message>
    <message>
      <source>MNU_LIGHT_SOURCE</source>
      <translation>光源</translation>
    </message>
    <message>
      <source>DSC_LIGHT_SOURCE</source>
      <translation>光源</translation>
    </message>
    <message>
      <source>OCC_IMAGE_FILES</source>
      <translation>イメージファイル (*.bmp *.png *.jpg *.jpeg *.eps *.ps)</translation>
    </message>
    <message>
      <source>LBL_XYTOOLBAR_LABEL</source>
      <translation>XY ビューの操作</translation>
    </message>
    <message>
      <source>LBL_XZTOOLBAR_LABEL</source>
      <translation>XZ ビューの操作</translation>
    </message>
    <message>
      <source>LBL_YZTOOLBAR_LABEL</source>
      <translation>YZ ビューの操作</translation>
    </message>
    <message>
      <source>LBL_3DTOOLBAR_LABEL</source>
      <translation>3D ビューの操作</translation>
    </message>
    <message>
      <source>MNU_ORTHOGRAPHIC_MODE</source>
      <translation>正射影投影</translation>
    </message>
    <message>
      <source>DSC_ORTHOGRAPHIC_MODE</source>
      <translation>正射影投影タイプを設定</translation>
    </message>
    <message>
      <source>MNU_PERSPECTIVE_MODE</source>
      <translation>遠近投影</translation>
    </message>
    <message>
      <source>DSC_PERSPECTIVE_MODE</source>
      <translation>遠近投影タイプを設定</translation>
    </message>
    <message>
      <source>MNU_STEREO_MODE</source>
      <translation>ステレオ投影</translation>
    </message>
    <message>
      <source>DSC_STEREO_MODE</source>
      <translation>ステレオ投影タイプを設定</translation>
    </message>
    <message>
      <source>WRN_SUPPORT_QUAD_BUFFER</source>
      <translation>グラフィックドライバはquad-bufferをサポートしていません</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_CreateRestoreViewDlg</name>
    <message>
      <source>CAPTION</source>
      <translation>ビューの読み込み</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_SetRotationPointDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点を設定</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>回転中心設定</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ビューで、項目を選択します。</translation>
    </message>
    <message>
      <source>LBL_POINT</source>
      <translation>点</translation>
    </message>
    <message>
      <source>LBL_EDGE</source>
      <translation>エッジ</translation>
    </message>
    <message>
      <source>LBL_FACE</source>
      <translation>面</translation>
    </message>
    <message>
      <source>LBL_SOLID</source>
      <translation>ソリッド</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_ViewManager</name>
    <message>
      <source>OCC_VIEW_TITLE</source>
      <translation>シーン OCC: %M - ビューアー: %V</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>ビューの保存</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景の変更</translation>
    </message>
    <message>
      <source>MEN_CHANGE_IMAGE</source>
      <translation>背景画像の設定/変更</translation>
    </message>
    <message>
      <source>SELECT_IMAGE</source>
      <translation>イメージの選択</translation>
    </message>
    <message>
      <source>CENTERED</source>
      <translation>中心のモード</translation>
    </message>
    <message>
      <source>TILED</source>
      <translation>テンキー モード</translation>
    </message>
    <message>
      <source>STRETCHED</source>
      <translation>ストレッチ モード</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>グラデーションの 2 番目の角</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目の角勾配</translation>
    </message>
    <message>
      <source>GT_FORTHCORNERGRADIENT</source>
      <translation>第 4 コーナー グラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.gif *.pix *.xwd *.rgb * .rs)</translation>
    </message>
    <message>
      <source>ST_QUADBUFFER</source>
      <translation>3D眼鏡 （OpenGL quad-buffer）</translation>
    </message>
    <message>
      <source>ST_ANAGLYPH</source>
      <translation>Anaglyph</translation>
    </message>
    <message>
      <source>ST_ROWINTERLACED</source>
      <translation>行インターレース</translation>
    </message>
    <message>
      <source>ST_COLUMNINTERLACED</source>
      <translation>列インターレース</translation>
    </message>
    <message>
      <source>ST_CHESSBOARD</source>
      <translation>Chess-board stereo for DLP TVs</translation>
    </message>
    <message>
      <source>ST_SIDEBYSIDE</source>
      <translation>水平アナモルフィック（横に並列）</translation>
    </message>
    <message>
      <source>ST_OVERUNDER</source>
      <translation>垂直アナモルフィック（縦に並列）</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_AxialScaleDlg</name>
    <message>
      <source>DLG_SCALING</source>
      <translation>スケールの変更</translation>
    </message>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_ClippingDlg</name>
    <message>
      <source>CLIPPING_PLANES</source>
      <translation>平面の切り抜き</translation>
    </message>
    <message>
      <source>NO_PLANES</source>
      <translation>平面がない</translation>
    </message>
    <message>
      <source>IS_ACTIVE_PLANE</source>
      <translation>アクティブな平面</translation>
    </message>
    <message>
      <source>BTN_NEW</source>
      <translation>新規</translation>
    </message>
    <message>
      <source>BTN_DELETE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>AUTO_APPLY</source>
      <translation>自動適用</translation>
    </message>
    <message>
      <source>MODE</source>
      <translation>モード</translation>
    </message>
    <message>
      <source>ORIENTATION</source>
      <translation>方向</translation>
    </message>
    <message>
      <source>DISTANCE</source>
      <translation>距離</translation>
    </message>
    <message>
      <source>ROTATION_AROUND_X_Y2Z</source>
      <translation>X軸周りに回転（Y軸からZ軸へ）</translation>
    </message>
    <message>
      <source>ROTATION_AROUND_Y_X2Z</source>
      <translation>Y軸周りに回転（X軸からZ軸へ）</translation>
    </message>
    <message>
      <source>ROTATION_AROUND_Z_Y2X</source>
      <translation>Z軸周りに回転（Y軸からX軸へ）</translation>
    </message>
    <message>
      <source>ROTATION_AROUND_X_Z2Y</source>
      <translation>X軸周りに回転（Z軸からY軸へ）</translation>
    </message>
    <message>
      <source>ROTATION_AROUND_Y_Z2X</source>
      <translation>Y軸周りに回転（Z軸からX軸へ）</translation>
    </message>
    <message>
      <source>ROTATION_AROUND_Z_X2Y</source>
      <translation>Z軸周りに回転（X軸からY軸へ）</translation>
    </message>
    <message>
      <source>ALONG_XY</source>
      <translation>XY平面に平行</translation>
    </message>
    <message>
      <source>ALONG_YZ</source>
      <translation>YZ平面に平行</translation>
    </message>
    <message>
      <source>ALONG_ZX</source>
      <translation>ZX平面に平行</translation>
    </message>
    <message>
      <source>ABSOLUTE</source>
      <translation>絶対</translation>
    </message>
    <message>
      <source>RELATIVE</source>
      <translation>相対</translation>
    </message>
    <message>
      <source>BTN_DISABLE_ALL</source>
      <translation>すべて無効</translation>
    </message>
    <message>
      <source>PREVIEW</source>
      <translation>プレビュー</translation>
    </message>
    <message>
      <source>RESET</source>
      <translation>リセット</translation>
    </message>
    <message>
      <source>INVERT</source>
      <translation>反転</translation>
    </message>
    <message>
      <source>BASE_POINT</source>
      <translation>基準点</translation>
    </message>
    <message>
      <source>DIRECTION</source>
      <translation>方向</translation>
    </message>
    <message>
      <source>PARAMETERS</source>
      <translation>パラメータ</translation>
    </message>
    <message>
      <source>HELP</source>
      <translation>ヘルプ(&amp;H)</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_RayTracingDlg</name>
    <message>
      <source>RAY_TRACING</source>
      <translation>レイトレース</translation>
    </message>
    <message>
      <source>DEPTH</source>
      <translation>深度</translation>
    </message>
    <message>
      <source>SHADOW</source>
      <translation>影のレンダリング</translation>
    </message>
    <message>
      <source>REFLECTION</source>
      <translation>狭反射</translation>
    </message>
    <message>
      <source>ANTIALIASING</source>
      <translation>最適アンチエイリアシング</translation>
    </message>
    <message>
      <source>TRANSPARENT_SHADOW</source>
      <translation>影の透過</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_EnvTextureDlg</name>
    <message>
      <source>ENV_TEXTURE</source>
      <translation>環境テキスチャ</translation>
    </message>
    <message>
      <source>ENV_CLOUDS</source>
      <translation>雲</translation>
    </message>
    <message>
      <source>ENV_CV</source>
      <translation>Cv</translation>
    </message>
    <message>
      <source>ENV_MEDIT</source>
      <translation>Medit</translation>
    </message>
    <message>
      <source>ENV_PEARL</source>
      <translation>Pearl</translation>
    </message>
    <message>
      <source>ENV_SKY1</source>
      <translation>Sky1</translation>
    </message>
    <message>
      <source>ENV_SKY2</source>
      <translation>Sky2</translation>
    </message>
    <message>
      <source>ENV_LINES</source>
      <translation>ライン</translation>
    </message>
    <message>
      <source>ENV_ROAD</source>
      <translation>道</translation>
    </message>
    <message>
      <source>ENV_CUSTOM</source>
      <translation>カスタム...</translation>
    </message>
  </context>
  <context>
    <name>OCCViewer_LightSourceDlg</name>
    <message>
      <source>LIGHT_SOURCE</source>
      <translation>光源</translation>
    </message>
    <message>
      <source>TYPE</source>
      <translation>型</translation>
    </message>
    <message>
      <source>DIRECTIONAL</source>
      <translation>方向</translation>
    </message>
    <message>
      <source>DIRECTION</source>
      <translation>方向</translation>
    </message>
    <message>
      <source>POSITIONAL</source>
      <translation>位置</translation>
    </message>
    <message>
      <source>POSITION</source>
      <translation>位置</translation>
    </message>
    <message>
      <source>COLOR</source>
      <translation>色</translation>
    </message>
    <message>
      <source>HEADLIGHT</source>
      <translation>ヘッドライト</translation>
    </message>
    <message>
      <source>BUT_DEFAULT</source>
      <translation>デフォルト</translation>
    </message>
  </context>
</TS>
