<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>TOT_DESK_EDIT_CUT</source>
      <translation>カット</translation>
    </message>
    <message>
      <source>PRP_DESK_EDIT_CUT</source>
      <translation>選択範囲を切り取って、クリップボードにコピー</translation>
    </message>
    <message>
      <source>MEN_DESK_EDIT_CUT</source>
      <translation>カット(&amp;t)</translation>
    </message>
    <message>
      <source>ERR_APP_NOAPP</source>
      <translation>アプリケーションがありません</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW</source>
      <translation>ウィンドウ(&amp;W)</translation>
    </message>
    <message>
      <source>TOT_DESK_EDIT_COPY</source>
      <translation>コピー</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW_CASCADE</source>
      <translation>カスケード(&amp;C)</translation>
    </message>
    <message>
      <source>PRP_DESK_EDIT_COPY</source>
      <translation>選択範囲をクリップボードにコピー</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_CASCADE</source>
      <translation>ウィンドウを重ねて整理</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_SAVEAS</source>
      <translation>ドキュメントを別名で保存...</translation>
    </message>
    <message>
      <source>MEN_DESK_EDIT_COPY</source>
      <translation>コピー(&amp;C)</translation>
    </message>
    <message>
      <source>MSG_CANT_SAVE</source>
      <translation>ファイル"%1"を保存できませんでした</translation>
    </message>
    <message>
      <source>INF_DESK_TOOLBAR_STANDARD</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>ALL_FILES</source>
      <translation>すべてのファイル (*. *)</translation>
    </message>
    <message>
      <source>DESK_DEFAULTTITLE</source>
      <translation>Qtアプリケーション デスクトップ</translation>
    </message>
    <message>
      <source>QUE_DESK_EXIT</source>
      <translation>本当に終了しますか？</translation>
    </message>
    <message>
      <source>INF_INFO</source>
      <translation>情報</translation>
    </message>
    <message>
      <source>ERR_DOC_UNKNOWNTYPE_OPEN</source>
      <translation>不明な種類 (%1) のドキュメントを開こうとしています。</translation>
    </message>
    <message>
      <source>ERR_DOC_UNKNOWNTYPE_SAVE</source>
      <translation>不明な種類 (%1) のドキュメントを保存しようしています。</translation>
    </message>
    <message>
      <source>TOT_DESK_NEWWINDOW</source>
      <translation>新しいウィンドウを作成</translation>
    </message>
    <message>
      <source>BUT_CANCEL</source>
      <translation>キャンセル(&amp;C)</translation>
    </message>
    <message>
      <source>MEN_DESK_HELP_ABOUT</source>
      <translation>バージョン情報...(&amp;A)</translation>
    </message>
    <message>
      <source>PRP_DESK_NEWWINDOW</source>
      <translation>新しいウィンドウを作成</translation>
    </message>
    <message>
      <source>MEN_DESK_VIEW_STATUSBAR</source>
      <translation>ステータス バー(&amp;S)</translation>
    </message>
    <message>
      <source>MEN_DESK_NEWWINDOW</source>
      <translation>新しいウィンドウ(&amp;N)</translation>
    </message>
    <message>
      <source>PRP_DESK_VIEW_STATUSBAR</source>
      <translation>ステータスバーの有効/無効</translation>
    </message>
    <message>
      <source>ERR_DOC_DIRWITHNAMEEXIST_SAVE</source>
      <translation>ファイル %1 を保存できません。\nこの名前のディレクトリが既にディスクに存在します。別の名前を使用してください。</translation>
    </message>
    <message>
      <source>BUT_NO</source>
      <translation>いいえ(&amp;N)</translation>
    </message>
    <message>
      <source>BUT_OK</source>
      <translation>OK(&amp;O)</translation>
    </message>
    <message>
      <source>FILTER_FILES</source>
      <translation>%1 ファイル (%2)</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_ACTIVATE</source>
      <translation>このウィンドウをアクティブ化</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_PRINT</source>
      <translation>ドキュメントを印刷</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_CLOSE</source>
      <translation>ドキュメントを閉じる</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_NEW</source>
      <translation>新しいドキュメント</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_NEW</source>
      <translation>新しいドキュメントを作成</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_MRU</source>
      <translation>ドキュメントを開く</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_NEW</source>
      <translation>新規作成(&amp;N)</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_MRU</source>
      <translation>最近使用したファイル(&amp;F)</translation>
    </message>
    <message>
      <source>TOT_DESK_EDIT_PASTE</source>
      <translation>貼り付け</translation>
    </message>
    <message>
      <source>MEN_DESK_VIEW_DOCKWINDOWS</source>
      <translation>Windows(&amp;i)</translation>
    </message>
    <message>
      <source>BUT_YES</source>
      <translation>はい(&amp;Y)</translation>
    </message>
    <message>
      <source>MEN_DESK_VIEW</source>
      <translation>表示(&amp;V)</translation>
    </message>
    <message>
      <source>PRP_DESK_HELP_ABOUT</source>
      <translation>ソフト情報の表示</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE</source>
      <translation>ファイル(&amp;F)</translation>
    </message>
    <message>
      <source>MEN_DESK_EDIT</source>
      <translation>編集(&amp;E)</translation>
    </message>
    <message>
      <source>MEN_DESK_HELP</source>
      <translation>ヘルプ(&amp;H)</translation>
    </message>
    <message>
      <source>ERR_ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>ERR_DESK_NOAPP</source>
      <translation>登録されたアプリケーションがありません</translation>
    </message>
    <message>
      <source>INF_DESK_DOC_CREATE</source>
      <translation>新しいドキュメントを作成</translation>
    </message>
    <message>
      <source>QUE_DOC_ALREADYOPEN</source>
      <translation>ドキュメント %1 は既に開いています。\n再読込みしますか？</translation>
    </message>
    <message>
      <source>BUT_APPLY</source>
      <translation>適用(&amp;A)</translation>
    </message>
    <message>
      <source>BUT_CLOSE</source>
      <translation>閉じる(&amp;C)</translation>
    </message>
    <message>
      <source>BUT_APPLY_AND_CLOSE</source>
      <translation>適用して閉じる（&amp;p）</translation>
    </message>
    <message>
      <source>INF_DESK_EXIT</source>
      <translation>終了</translation>
    </message>
    <message>
      <source>ERR_UNKNOWN</source>
      <translation>不明なエラー</translation>
    </message>
    <message>
      <source>BUT_HELP</source>
      <translation>ヘルプ(&amp;H)</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_CLOSE</source>
      <translation>現在のドキュメントを閉じる</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_PRINT</source>
      <translation>現在のドキュメントを印刷</translation>
    </message>
    <message>
      <source>WRN_WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>TOT_DESK_HELP_ABOUT</source>
      <translation>About...</translation>
    </message>
    <message>
      <source>MEN_DESK_VIEW_TOOLBARS</source>
      <translation>ツールバー(&amp;o)</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_HSPLIT</source>
      <translation>現在のウィンドウを 2つに水平分割</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW_HSPLIT</source>
      <translation>水平分割(&amp;H)</translation>
    </message>
    <message>
      <source>PRP_DESK_EDIT_PASTE</source>
      <translation>クリップボードの内容を挿入</translation>
    </message>
    <message>
      <source>DLG_LOAD_STUDY_CAPTION</source>
      <translation>スタディを読み込む</translation>
    </message>
    <message>
      <source>PRP_DESK_HELP_SEARCH</source>
      <translation>ヘルプのトピック検索</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_SAVEAS</source>
      <translation>現在のドキュメントを新しい名前で保存</translation>
    </message>
    <message>
      <source>INF_READY</source>
      <translation>準備完了</translation>
    </message>
    <message>
      <source>INF_CANCELLED</source>
      <translation>キャンセル</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_VSPLIT</source>
      <translation>現在のウィンドウを２つに上下分割</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW_VSPLIT</source>
      <translation>垂直分割(&amp;V)</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_TILE</source>
      <translation>ウィンドウを並べて表示</translation>
    </message>
    <message>
      <source>MEN_DESK_HELP_CONTENTS</source>
      <translation>コンテンツ(&amp;C)</translation>
    </message>
    <message>
      <source>PRP_DESK_HELP_CONTENTS</source>
      <translation>ヘルプコンテンツの全表示</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW_HTILE</source>
      <translation>水平方向に並べて表示(&amp;H)</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW_VTILE</source>
      <translation>垂直方向に並べて表示(&amp;V)</translation>
    </message>
    <message>
      <source>ERR_DOC_PERMISSIONDENIED_SAVE</source>
      <translation>ファイル %1 を保存できません。権限がありません。</translation>
    </message>
    <message>
      <source>INF_DESK_DOCALREADYOPEN</source>
      <translation>既に開いているドキュメントと同じ名前で保存できません。\n保存するには別の名前を指定してください。\n( %1 )</translation>
    </message>
    <message>
      <source>TIT_FILE_SAVEAS</source>
      <translation>別名保存</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_CLOSE</source>
      <translation>閉じる(&amp;C)</translation>
    </message>
    <message>
      <source>MSG_FILE_EXISTS</source>
      <translation>ファイル"%1"は既に存在します。\n上書きしますか？</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_PRINT</source>
      <translation>印刷(&amp;P)</translation>
    </message>
    <message>
      <source>MEN_DESK_HELP_SEARCH</source>
      <translation>検索...(&amp;S)</translation>
    </message>
    <message>
      <source>MEN_DESK_VIEW_STDTOOLBAR</source>
      <translation>標準(&amp;S)</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_SAVEAS</source>
      <translation>別名保存...(&amp;A)</translation>
    </message>
    <message>
      <source>PRP_DESK_VIEW_STDTOOLBAR</source>
      <translation>標準ツールバーの有効/無効</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_SAVE</source>
      <translation>ドキュメントを保存</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_EXIT</source>
      <translation>アプリケーションを終了</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_OPEN</source>
      <translation>文書を開く</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_REOPEN</source>
      <translation>ドキュメントの再読み込み</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_EXIT</source>
      <translation>アプリケーションを終了</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_OPEN</source>
      <translation>既存のドキュメントを開く</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_REOPEN</source>
      <translation>現在のドキュメントを再読込み</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_SAVE</source>
      <translation>現在のドキュメントを保存</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_HTILE</source>
      <translation>ウィンドウを左右に並べて表示</translation>
    </message>
    <message>
      <source>PRP_DESK_WINDOW_VTILE</source>
      <translation>ウィンドウを上下に並べて表示</translation>
    </message>
    <message>
      <source>MEN_DESK_WINDOW_TILE</source>
      <translation>モザイク(&amp;T)</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_EXIT</source>
      <translation>終了(&amp;x)</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_OPEN</source>
      <translation>開く...(&amp;O)</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_REOPEN</source>
      <translation>再読み込み</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_SAVE</source>
      <translation>保存(&amp;S)</translation>
    </message>
    <message>
      <source>MEN_DESK_EDIT_PASTE</source>
      <translation>貼り付け(&amp;P)</translation>
    </message>
    <message>
      <source>MEN_STUDIES_CHOICE</source>
      <translation>既存のスタディを選択</translation>
    </message>
  </context>
  <context>
    <name>STD_Application</name>
    <message>
      <source>INF_DOC_MODIFIED</source>
      <translation>ドキュメントが変更されています。変更を保存しますか。</translation>
    </message>
    <message>
      <source>INF_DOC_SAVING</source>
      <translation>スタディを保存</translation>
    </message>
    <message>
      <source>INF_DOC_SAVED</source>
      <translation>Study %1 を保存</translation>
    </message>
    <message>
      <source>TOT_DOCK_WINDOWS</source>
      <translation>ドッキング可能なウィンドウとツールバーを表示/非表示</translation>
    </message>
    <message>
      <source>MEN_DOCK_WINDOWS</source>
      <translation>ウィンドウとツールバー</translation>
    </message>
    <message>
      <source>ABOUT_INFO</source>
      <translation>SUIT標準アプリケーション</translation>
    </message>
    <message>
      <source>INF_DOC_SAVING_FAILS</source>
      <translation>ファイル"%1"を保存できません.\n理由:\n- 権限がない;\n- ディスクの残りのスペースが不十分;\n- アプリケーション エラー.\n別のファイル名をご使用ください。</translation>
    </message>
    <message>
      <source>INF_DOCUMENT_MODIFIED</source>
      <translation>ドキュメント"%1"が変更されました。変更を保存しますか。</translation>
    </message>
    <message>
      <source>CLOSE_STUDY</source>
      <translation>現在のスタディを閉じる</translation>
    </message>
    <message>
      <source>CLOSE_QUESTION</source>
      <translation>閉じる前にスタディを保存しますか？</translation>
    </message>
    <message>
      <source>REOPEN_STUDY</source>
      <translation>スタディを再読み込み</translation>
    </message>
    <message>
      <source>REOPEN_QUESTION</source>
      <translation>スタディを再開しますか。\n最後に保存してからのすべての変更は失われます。</translation>
    </message>
  </context>
</TS>
