<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
<context>
    <name>@default</name>
    <message>
        <source>ICON_FILE_NEW</source>
        <translation>new.png</translation>
    </message>
    <message>
        <source>ICON_DESK_WINDOW_TILE</source>
        <translation>tile.png</translation>
    </message>
    <message>
        <source>ICON_PRINT</source>
        <translation>print.png</translation>
    </message>
    <message>
        <source>ICON_RESET</source>
        <translation>reset.png</translation>
    </message>
    <message>
        <source>ICON_HELP</source>
        <translation>help.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_CUT</source>
        <translation>cut.png</translation>
    </message>
    <message>
        <source>ICON_DESK_WINDOW_CASCADE</source>
        <translation>cascade.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_COPY</source>
        <translation>copy.png</translation>
    </message>
    <message>
        <source>ICON_FILE_SAVE</source>
        <translation>save.png</translation>
    </message>
    <message>
        <source>ICON_FILE_OPEN</source>
        <translation>open.png</translation>
    </message>
    <message>
        <source>ICON_DESK_WINDOW_HSPLIT</source>
        <translation>htile.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_REDO</source>
        <translation>redo.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_UNDO</source>
        <translation>undo.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_DELETE</source>
        <translation>delete.png</translation>
    </message>
    <message>
        <source>ICON_DESK_WINDOW_VSPLIT</source>
        <translation>vtile.png</translation>
    </message>
    <message>
        <source>ICON_DESK_WINDOW_HTILE</source>
        <translation>htile.png</translation>
    </message>
    <message>
        <source>ICON_DESK_WINDOW_VTILE</source>
        <translation>vtile.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_PASTE</source>
        <translation>paste.png</translation>
    </message>
    <message>
        <source>ICON_FILE_CLOSE</source>
        <translation>close.png</translation>
    </message>
</context>
</TS>
