<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>TOOLS_WRN_WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>TOOLS_BUT_BROWSE</source>
      <translation>開く...</translation>
    </message>
    <message>
      <source>TOOLS_ERR_ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>TOOLS_ERR_FILE_NOT_EXIST</source>
      <translation>ファイル %1 は存在しません</translation>
    </message>
    <message>
      <source>TOOLS_BUT_OK</source>
      <translation>Ok(&amp;O)</translation>
    </message>
    <message>
      <source>TOOLS_BUT_APPLY</source>
      <translation>適用(&amp;A)</translation>
    </message>
    <message>
      <source>TOOLS_BUT_CLOSE</source>
      <translation>閉じる(&amp;C)</translation>
    </message>
  </context>
  <context>
    <name>ToolsGUI_CatalogGeneratorDlg</name>
    <message>
      <source>TOOLS_MEN_EXPORT</source>
      <translation>エクスポート</translation>
    </message>
    <message>
      <source>TOOLS_MEN_IMPORT</source>
      <translation>インポート</translation>
    </message>
    <message>
      <source>TOOLS_VERSION</source>
      <translation>バージョン：</translation>
    </message>
    <message>
      <source>TOOLS_COMP_NAME</source>
      <translation>名前:</translation>
    </message>
    <message>
      <source>TOOLS_COMP_TYPE</source>
      <translation>型:</translation>
    </message>
    <message>
      <source>TOOLS_XML_FILE</source>
      <translation>XML:</translation>
    </message>
    <message>
      <source>TOOLS_PNG_FILE</source>
      <translation>アイコン:</translation>
    </message>
    <message>
      <source>TOOLS_SUPPLEMENT</source>
      <translation>コンポーネントの追加のデータ</translation>
    </message>
    <message>
      <source>TOOLS_AUTHOR</source>
      <translation>著者:</translation>
    </message>
    <message>
      <source>TOOLS_COMP_MULTISTD</source>
      <translation>Multistudy:</translation>
    </message>
    <message>
      <source>TOOLS_COMP_USERNAME</source>
      <translation>ユーザー名:</translation>
    </message>
    <message>
      <source>TOOLS_CATALOG_GENERATOR</source>
      <translation>カタログ ジェネレーター</translation>
    </message>
    <message>
      <source>TOOLS_FILES</source>
      <translation>ファイル</translation>
    </message>
    <message>
      <source>TOOLS_MEN_IMPORT_PNG</source>
      <translation>PNG ファイル (*.png)</translation>
    </message>
    <message>
      <source>TOOLS_MEN_IMPORT_IDL</source>
      <translation>IDL ファイル (*.idl)</translation>
    </message>
    <message>
      <source>TOOLS_MEN_EXPORT_XML</source>
      <translation>XML ファイル (*.xml)</translation>
    </message>
    <message>
      <source>TOOLS_IDL_FILE</source>
      <translation>IDL:</translation>
    </message>
  </context>
  <context>
    <name>ToolsGUI_RegWidget</name>
    <message>
      <source>TLT_REFRESH_INTERVAL</source>
      <translation>更新間隔</translation>
    </message>
    <message>
      <source>LAB_REFRESH_INTERVAL</source>
      <translation>更新頻度 （秒）</translation>
    </message>
    <message>
      <source>TLT_REGISTRY</source>
      <translation>レジストリ</translation>
    </message>
    <message>
      <source>MNU_ACTIONS</source>
      <translation>アクション</translation>
    </message>
    <message>
      <source>TB_ACTIONS</source>
      <translation>アクション</translation>
    </message>
    <message>
      <source>MEN_REFRESH</source>
      <translation>更新</translation>
    </message>
    <message>
      <source>STB_REFRESH</source>
      <translation>コンポーネントの一覧を更新します。</translation>
    </message>
    <message>
      <source>MEN_INTERVAL</source>
      <translation>更新間隔.</translation>
    </message>
    <message>
      <source>STB_INTERVAL</source>
      <translation>更新の頻度を変更します。</translation>
    </message>
    <message>
      <source>MEN_CLOSE</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>STB_CLOSE</source>
      <translation>レジストリのウィンドウを閉じる</translation>
    </message>
    <message>
      <source>TAB_RUNNING</source>
      <translation>実行中</translation>
    </message>
    <message>
      <source>TAB_HISTORY</source>
      <translation>履歴</translation>
    </message>
    <message>
      <source>HDR_COMPONENT</source>
      <translation>コンポーネント</translation>
    </message>
    <message>
      <source>HDR_PID</source>
      <translation>PID</translation>
    </message>
    <message>
      <source>HDR_USERNAME</source>
      <translation>ユーザー名</translation>
    </message>
    <message>
      <source>HDR_HOSTNAME</source>
      <translation>ホスト名</translation>
    </message>
    <message>
      <source>HDR_STARTED</source>
      <translation>開始日時</translation>
    </message>
    <message>
      <source>HDR_FINISHED</source>
      <translation>終了</translation>
    </message>
    <message>
      <source>HDR_HELLO</source>
      <translation>最後の アクセス</translation>
    </message>
    <message>
      <source>ERR_NO_REGISTRY</source>
      <translation>エラー: レジストリ サーバーが見つかりません</translation>
    </message>
    <message>
      <source>INFO_SERVICE</source>
      <translation>サービス: %1</translation>
    </message>
    <message>
      <source>INFO_PROCESS</source>
      <translation>マシン名 %2 (IPアドレス: %3 )上のプロセス (PID: %1); ディレクトリ%6でユーザ%4(UID: %5)によって起動された 。</translation>
    </message>
    <message>
      <source>INFO_STARTED</source>
      <translation>開始: %1</translation>
    </message>
    <message>
      <source>INFO_LAST_PING</source>
      <translation>最終アクセス: %1</translation>
    </message>
    <message>
      <source>INFO_FINISHED</source>
      <translation>終了: %1</translation>
    </message>
    <message>
      <source>INFO_RUNNING</source>
      <translation>実行中</translation>
    </message>
    <message>
      <source>INFO_TIME_DIFF</source>
      <translation>%1 の時刻はサーバーの時刻とずれております。ずれは %2 秒です。</translation>
    </message>
  </context>
</TS>
