<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>EXTERNAL_BROWSER_CANNOT_SHOW_PAGE</source>
      <translation>拡張ブラウザ "%1" はヘルプページ "%2"は見ることができない。設定を変更しますか？</translation>
    </message>
    <message>
      <source>ABOUT_COPYRIGHT</source>
      <translation>Copyright (C) 2007-2016 CEA/DEN, EDF R&amp;D, OPEN CASCADE

Copyright (C) 2003-2007 OPEN CASCADE, EADS/CCR, LIP6,
CEA/DEN, CEDRAT, EDF R&amp;D, LEG, PRINCIPIA R&amp;D, BUREAU VERITAS</translation>
    </message>
    <message>
      <source>ABOUT_CAPTION</source>
      <translation>%1について</translation>
    </message>
    <message>
      <source>ABOUT_BASE</source>
      <translation>一般的な情報</translation>
    </message>
    <message>
      <source>ABOUT_MODULE_INFOS</source>
      <translation>モジュール情報</translation>
    </message>
    <message>
      <source>ABOUT_UNKNOWN_VERSION</source>
      <translation>不明</translation>
    </message>
    <message>
      <source>ABOUT_CLOSE</source>
      <translation>閉じる(&amp;C)</translation>
    </message>
    <message>
      <source>APP_NAME</source>
      <translation>SALOME</translation>
    </message>
    <message>
      <source>ABOUT_LICENSE</source>
      <translation>GNU LGPL</translation>
    </message>
    <message>
      <source>ABOUT_VERSION</source>
      <translation>Version %1</translation>
    </message>
    <message>
      <source>ENTRY_COLUMN</source>
      <translation>エントリ</translation>
    </message>
    <message>
      <source>APPCLOSE_CAPTION</source>
      <translation>現在のスタディを閉じる</translation>
    </message>
    <message>
      <source>STUDYCLOSE_DESCRIPTION</source>
      <translation>既存のスタディを閉じる必要があります。閉じますか？
</translation>
    </message>
    <message>
      <source>APPCLOSE_SAVE</source>
      <translation>保存して閉じる(&amp;S)</translation>
    </message>
    <message>
      <source>APPCLOSE_CLOSE</source>
      <translation>保存せずに閉じる(&amp;C)</translation>
    </message>
    <message>
      <source>APPCLOSE_CANCEL</source>
      <translation>キャンセル(&amp;C)</translation>
    </message>
    <message>
      <source>WRN_PYTHON_FILE_NAME_BAD</source>
      <translation>正確なファイル名を入力してください。
Pythonファイルは、文字、数字、アンダースコアが含まれており、文字またはアンダースコアから開始する必要があります。</translation>
    </message>
    <message>
      <source>PYTHON_FILES_FILTER</source>
      <translation>ファイル (*.py) PYTHON</translation>
    </message>
    <message>
      <source>LOG_FILES_FILTER</source>
      <translation>ログファイル (*.log *.txt)</translation>
    </message>
  </context>
  <context>
    <name>LightApp_Application</name>
    <message>
      <source>LANG_CHANGED</source>
      <translation>アプリケーションの言語が変更されました。&lt;BR&gt;変更は、次のセッションに適用されます。</translation>
    </message>
    <message>
      <source>LOCALE_CHANGED</source>
      <translation>アプリケーションの言語が変更されました。
次回のセッションから有効になります。</translation>
    </message>
    <message>
      <source>MEN_DESK_THEME</source>
      <translation>テーマ(&amp;h)</translation>
    </message>
    <message>
      <source>TOT_THEME</source>
      <translation>テーマ</translation>
    </message>
    <message>
      <source>PRP_THEME</source>
      <translation>スタイルのプロパティを変更</translation>
    </message>
    <message>
      <source>TOT_FULLSCREEN</source>
      <translation>全画面表示</translation>
    </message>
    <message>
      <source>MEN_DESK_FULLSCREEN</source>
      <translation>全画面表示</translation>
    </message>
    <message>
      <source>PRP_FULLSCREEN</source>
      <translation>全画面表示モードに切り替え</translation>
    </message>
    <message>
      <source>INF_TOOLBAR_MODULES</source>
      <translation>モジュール情報</translation>
    </message>
    <message>
      <source>PREF_SHOW_LEGEND</source>
      <translation>凡例を表示</translation>
    </message>
    <message>
      <source>MEN_DESK_RENAME</source>
      <translation>名前変更(&amp;R)</translation>
    </message>
    <message>
      <source>PREF_MULTI_FILE</source>
      <translation>複数ファイルの保存</translation>
    </message>
    <message>
      <source>MEN_DESK_PREFERENCES</source>
      <translation>環境設定...(&amp;f)</translation>
    </message>
    <message>
      <source>PREF_TRIHEDRON_SHOW</source>
      <translation>三面体を表示</translation>
    </message>
    <message>
      <source>PREF_TRIHEDRON</source>
      <translation>三面体</translation>
    </message>
    <message>
      <source>PREF_TRIHEDRON_SIZE</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>OBJECT_BROWSER</source>
      <translation>オブジェクトブラウザー</translation>
    </message>
    <message>
      <source>PRP_DESK_PREFERENCES</source>
      <translation>設定を変更することができます。</translation>
    </message>
    <message>
      <source>PREF_GROUP_DIRECTORIES</source>
      <translation>ディレクトリの一覧</translation>
    </message>
    <message>
      <source>PREF_GROUP_VTKVIEWER</source>
      <translation>VTK 3D Viewer</translation>
    </message>
    <message>
      <source>PREF_LOAD_LIGHT</source>
      <translation>スタディを開くときにLightモジュールを自動読み込みする</translation>
    </message>
    <message>
      <source>PREF_STORE_POS</source>
      <translation>ウィンドウの位置を保存</translation>
    </message>
    <message>
      <source>PREF_STORE_TOOL_POS</source>
      <translation>ツールバーの位置を保存します。</translation>
    </message>
    <message>
      <source>PREF_AUTO_SAVE</source>
      <translation>自動保存間隔 (分)</translation>
    </message>
    <message>
      <source>PREF_AUTO_SAVE_DISABLED</source>
      <translation>無効</translation>
    </message>
    <message>
      <source>PREF_PROJECTION_MODE</source>
      <translation>投影モード:</translation>
    </message>
    <message>
      <source>PREF_ORTHOGRAPHIC</source>
      <translation>直交</translation>
    </message>
    <message>
      <source>PREF_PERSPECTIVE</source>
      <translation>遠近法</translation>
    </message>
    <message>
      <source>PREF_NAVIGATION</source>
      <translation>ナビゲーション スタイル</translation>
    </message>
    <message>
      <source>PREF_STANDARD_STYLE</source>
      <translation>Salome標準コントロール</translation>
    </message>
    <message>
      <source>PREF_KEYFREE_STYLE</source>
      <translation>キーボードなしのスタイル</translation>
    </message>
    <message>
      <source>PREF_ZOOMING</source>
      <translation>ズーム モード:</translation>
    </message>
    <message>
      <source>PREF_ZOOMING_AT_CENTER</source>
      <translation>ビューの中心を基準</translation>
    </message>
    <message>
      <source>PREF_ZOOMING_AT_CURSOR</source>
      <translation>カーソルを中心に</translation>
    </message>
    <message>
      <source>PREF_INCREMENTAL_SPEED</source>
      <translation>速度の増加:</translation>
    </message>
    <message>
      <source>PREF_INCREMENTAL_SPEED_MODE</source>
      <translation>編集モード:</translation>
    </message>
    <message>
      <source>PREF_ARITHMETIC</source>
      <translation>Arithmetic progression</translation>
    </message>
    <message>
      <source>PREF_GEOMETRICAL</source>
      <translation>幾何学的進行</translation>
    </message>
    <message>
      <source>PREF_FRAME_SPACEMOUSE</source>
      <translation>Spacemouse</translation>
    </message>
    <message>
      <source>PREF_SHOW_STATIC_TRIHEDRON</source>
      <translation>静的三面体をを表示</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_FUNC_1</source>
      <translation>速度低減</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_FUNC_2</source>
      <translation>速度増加</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_FUNC_3</source>
      <translation>Dominant / combined スイッチ</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_1</source>
      <translation>ボタン 1</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_2</source>
      <translation>ボタン 2</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_3</source>
      <translation>ボタン 3</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_4</source>
      <translation>ボタン 4</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_5</source>
      <translation>ボタン 5</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_6</source>
      <translation>ボタン 6</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_7</source>
      <translation>ボタン 7</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_8</source>
      <translation>ボタン 8</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_*</source>
      <translation>ボタン *</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_10</source>
      <translation>ボタン 10</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_11</source>
      <translation>ボタン 11</translation>
    </message>
    <message>
      <source>PREF_FRAME_RECORDING</source>
      <translation>AVIで記録</translation>
    </message>
    <message>
      <source>PREF_ALL_DISLPAYED_FRAMES</source>
      <translation>表示されるすべてのフレームを保存</translation>
    </message>
    <message>
      <source>PREF_FPS</source>
      <translation>FPS</translation>
    </message>
    <message>
      <source>PREF_GROUP_TTL</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>PREF_PROGRESSIVE</source>
      <translation>プログレッシブ</translation>
    </message>
    <message>
      <source>PREF_QUALITY</source>
      <translation>品質</translation>
    </message>
    <message>
      <source>PREF_RECORDING_MODE</source>
      <translation>モード</translation>
    </message>
    <message>
      <source>PREF_SKIPPED_FRAMES</source>
      <translation>与えられたFPSに記録しています</translation>
    </message>
    <message>
      <source>PREF_FRAME_GROUP_NAMES</source>
      <translation>グループの名前</translation>
    </message>
    <message>
      <source>PREF_GROUP_NAMES_TEXT_COLOR</source>
      <translation>テキストの色</translation>
    </message>
    <message>
      <source>PREF_GROUP_NAMES_TRANSPARENCY</source>
      <translation>透明度</translation>
    </message>
    <message>
      <source>PREF_BOTTOM</source>
      <translation>Bottom</translation>
    </message>
    <message>
      <source>PREF_CURVE_TYPE</source>
      <translation>曲線の種類:</translation>
    </message>
    <message>
      <source>PREF_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>PRP_MODULE</source>
      <translation>モジュール”%1”に切り替え</translation>
    </message>
    <message>
      <source>PREF_ASCII_FILE</source>
      <translation>ASCIIでの保存</translation>
    </message>
    <message>
      <source>PREFERENCES_NOT_LOADED</source>
      <translation>“&lt;b&gt;%N&lt;/b&gt;”モジュールの環境設定は、そのモジュールをロードしているときだけです。</translation>
    </message>
    <message>
      <source>PREF_LINEAR</source>
      <translation>線形</translation>
    </message>
    <message>
      <source>DATA_MODELS</source>
      <translation>データ モデル</translation>
    </message>
    <message>
      <source>PRP_RENAME</source>
      <translation>アクティブなウィンドウの名前を変更</translation>
    </message>
    <message>
      <source>TOT_RENAME</source>
      <translation>名前変更</translation>
    </message>
    <message>
      <source>MEN_RENAME_OBJ</source>
      <translation>名前変更</translation>
    </message>
    <message>
      <source>LOG_WINDOW</source>
      <translation>メッセージウィンドウ</translation>
    </message>
    <message>
      <source>PREF_SPLINE</source>
      <translation>スプライン</translation>
    </message>
    <message>
      <source>PREF_OBJ_BROWSER_SEARCH_TOOL</source>
      <translation>検索ツール</translation>
    </message>
    <message>
      <source>PREF_AUTO_HIDE_SEARCH_TOOL</source>
      <translation>自動非表示の有効化</translation>
    </message>
    <message>
      <source>PREF_OBJ_BROWSER_SETTINGS</source>
      <translation>オブジェクトブラウザーの設定</translation>
    </message>
    <message>
      <source>PRP_APP_MODULE</source>
      <translation>Salomeプラットフォームの中立ポイントにスイッチ</translation>
    </message>
    <message>
      <source>PREF_GROUP_PY_CONSOLE</source>
      <translation>Python コンソールのプロパティ</translation>
    </message>
    <message>
      <source>PREF_SHOW_BANNER</source>
      <translation>バナーの表示</translation>
    </message>
    <message>
      <source>PREF_AUTO_COMPLETION</source>
      <translation>コマンドオートコンプリート</translation>
    </message>
    <message>
      <source>PREF_GROUP_STYLE</source>
      <translation>Salomeスタイル</translation>
    </message>
    <message>
      <source>PREF_USE_SALOME_STYLE</source>
      <translation>Salomeスタイルを使用</translation>
    </message>
    <message>
      <source>PREF_MARKER_SIZE</source>
      <translation>マーカーのサイズ:</translation>
    </message>
    <message>
      <source>PREF_TAB_VIEWERS</source>
      <translation>シーン</translation>
    </message>
    <message>
      <source>PREF_APP</source>
      <translation>アプリケーション</translation>
    </message>
    <message>
      <source>PREF_TOP</source>
      <translation>トップ</translation>
    </message>
    <message>
      <source>MEN_REFRESH</source>
      <translation>更新</translation>
    </message>
    <message>
      <source>PREF_AUTO_SIZE_FIRST</source>
      <translation>[名前] 列の自動サイズ</translation>
    </message>
    <message>
      <source>PREF_RESIZE_ON_EXPAND_ITEM</source>
      <translation>オブジェクトを開いたときの列のサイズを変更</translation>
    </message>
    <message>
      <source>PREF_BROWSE_TO_THE_PUBLISHED_OBJECT</source>
      <translation>公開オブジェクトをブラウズ</translation>
    </message>
    <message>
      <source>PREF_BROWSE_NEVER</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>PREF_BROWSE_AFTER_APPLY_AND_CLOSE_ONLY</source>
      <translation>適用して閉じるをした後のみ</translation>
    </message>
    <message>
      <source>PREF_BROWSE_ALWAYS</source>
      <translation>適用毎に</translation>
    </message>
    <message>
      <source>PREF_TAB_OBJBROWSER</source>
      <translation>オブジェクトブラウザー</translation>
    </message>
    <message>
      <source>PREF_TAB_GENERAL</source>
      <translation>一般的な</translation>
    </message>
    <message>
      <source>NEW_WINDOW_0</source>
      <translation>GL 2D view(&amp;G)</translation>
    </message>
    <message>
      <source>NEW_WINDOW_1</source>
      <translation>Plot 2D View(&amp;P)</translation>
    </message>
    <message>
      <source>NEW_WINDOW_2</source>
      <translation>OCC 3D　View(&amp;O)</translation>
    </message>
    <message>
      <source>NEW_WINDOW_3</source>
      <translation>VTK 3D View(&amp;K)</translation>
    </message>
    <message>
      <source>NEW_WINDOW_4</source>
      <translation>シーン QxScene(&amp;S)</translation>
    </message>
    <message>
      <source>NEW_WINDOW_5</source>
      <translation>グラフィックの表示 （&amp;r）</translation>
    </message>
    <message>
      <source>NEW_WINDOW_6</source>
      <translation>ParaView 表示 (&amp;w)</translation>
    </message>
    <message>
      <source>NEW_WINDOW_7</source>
      <translation>P&amp;ython view</translation>
    </message>
    <message>
      <source>CREATING_NEW_WINDOW</source>
      <translation>新しい %1 を作成します。</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_NAME</source>
      <translation>オブジェクト</translation>
    </message>
    <message>
      <source>PREF_LEGEND_POSITION</source>
      <translation>凡例の位置:</translation>
    </message>
    <message>
      <source>PREF_RELATIVE_SIZE</source>
      <translation>相対</translation>
    </message>
    <message>
      <source>PREF_VIEWER_BACKGROUND</source>
      <translation>背景</translation>
    </message>
    <message>
      <source>PREF_VIEWER_BACKGROUND_COLOR</source>
      <translation>背景色</translation>
    </message>
    <message>
      <source>PREF_VIEWER_SELECTION</source>
      <translation>選択色</translation>
    </message>
    <message>
      <source>PREF_XYVIEWER_BACKGROUND</source>
      <translation>XY 表示</translation>
    </message>
    <message>
      <source>PREF_XZVIEWER_BACKGROUND</source>
      <translation>XZ ビュー</translation>
    </message>
    <message>
      <source>PREF_YZVIEWER_BACKGROUND</source>
      <translation>ビュー YZ</translation>
    </message>
    <message>
      <source>PREF_3DVIEWER_BACKGROUND</source>
      <translation>3D ビュー</translation>
    </message>
    <message>
      <source>PREF_FONT</source>
      <translation>フォント</translation>
    </message>
    <message>
      <source>PREF_LEGEND_FONT</source>
      <translation>凡例のフォント</translation>
    </message>
    <message>
      <source>PREF_FONT_COLOR</source>
      <translation>凡例のフォントの色</translation>
    </message>
    <message>
      <source>PREF_SELECTED_FONT_COLOR</source>
      <translation>ハイライトした凡例の文字色</translation>
    </message>
    <message>
      <source>PREF_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>PREF_TAB_DIRECTORIES</source>
      <translation>ディレクトリー</translation>
    </message>
    <message>
      <source>ACTIVATING_MODULE</source>
      <translation>モジュール”%1”をアクティブにする</translation>
    </message>
    <message>
      <source>PREF_VERT_AXIS_SCALE</source>
      <translation>垂直軸のスケール:</translation>
    </message>
    <message>
      <source>PREF_HOR_AXIS_SCALE</source>
      <translation>水平方向の軸のスケール:</translation>
    </message>
    <message>
      <source>PREF_GROUP_LANGUAGE</source>
      <translation>言語</translation>
    </message>
    <message>
      <source>PREF_CURRENT_LANGUAGE</source>
      <translation>現在の言語</translation>
    </message>
    <message>
      <source>PREF_CURRENT_LOCALE</source>
      <translation>言語 "C" を使います</translation>
    </message>
    <message>
      <source>PREF_GROUP_LOOK_AND_FEEL</source>
      <translation>外観</translation>
    </message>
    <message>
      <source>PREF_SHOW_SPLASH</source>
      <translation>スプラッシュ スクリーンを表示します。</translation>
    </message>
    <message>
      <source>PREF_OPAQUE_RESIZE</source>
      <translation>不透明のサイズ変更</translation>
    </message>
    <message>
      <source>PREF_GROUP_STUDY</source>
      <translation>スタディのプロパティ</translation>
    </message>
    <message>
      <source>PREF_CATEGORY_SALOME</source>
      <translation>SALOME</translation>
    </message>
    <message>
      <source>PREF_DROP_DOWN_BUTTONS</source>
      <translation>バーでのボタンの配置</translation>
    </message>
    <message>
      <source>PREF_GROUP_COMMON</source>
      <translation>共通</translation>
    </message>
    <message>
      <source>PREF_GROUP_3DVIEWER</source>
      <translation>3D シーン</translation>
    </message>
    <message>
      <source>PREF_GROUP_OCCVIEWER</source>
      <translation>OCC 3D　Viewer</translation>
    </message>
    <message>
      <source>PREF_GROUP_STEREO</source>
      <translation>ステレオレンダリング</translation>
    </message>
    <message>
      <source>PREF_STEREO_TYPE</source>
      <translation>ステレオタイプ</translation>
    </message>
    <message>
      <source>PREF_ANAGLYPH_FILTER</source>
      <translation>Anaglyph filter</translation>
    </message>
    <message>
      <source>PREF_ANAGLYPH_RED_CYAN</source>
      <translation>赤-シアン投影</translation>
    </message>
    <message>
      <source>PREF_ANAGLYPH_YELLOW_BLUE</source>
      <translation>黄-青投影</translation>
    </message>
    <message>
      <source>PREF_ANAGLYPH_GREEN_MAGENTA</source>
      <translation>緑-マゼンタ投影</translation>
    </message>
    <message>
      <source>PREF_FOCUS_TYPE</source>
      <translation>一致距離型</translation>
    </message>
    <message>
      <source>PREF_FOCUS_VALUE</source>
      <translation>立体画法焦点値</translation>
    </message>
    <message>
      <source>PREF_IOD_TYPE</source>
      <translation>眼間距離（IOD）型</translation>
    </message>
    <message>
      <source>PREF_IOD_VALUE</source>
      <translation>眼間距離（IOD）値</translation>
    </message>
    <message>
      <source>PREF_ABSOLUTE</source>
      <translation>絶対</translation>
    </message>
    <message>
      <source>PREF_RELATIVE</source>
      <translation>早退</translation>
    </message>
    <message>
      <source>PREF_REVERSE_STEREO</source>
      <translation>Reverse stereo</translation>
    </message>
    <message>
      <source>PREF_ENABLE_VSYNC</source>
      <translation>V-Syncを有効</translation>
    </message>
    <message>
      <source>PREF_ENABLE_QUAD_BUFFER_SUPPORT</source>
      <translation>quad-buffer サポートを有効</translation>
    </message>
    <message>
      <source>PREF_LOGARITHMIC</source>
      <translation>対数</translation>
    </message>
    <message>
      <source>MEN_DESK_MODULE_HELP</source>
      <translation>モジュールのヘルプ</translation>
    </message>
    <message>
      <source>PREF_SUPERV_TITLE_COLOR</source>
      <translation>タイトルの色</translation>
    </message>
    <message>
      <source>PREF_PARAM</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>PREF_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>PREF_LINES</source>
      <translation>ライン</translation>
    </message>
    <message>
      <source>INF_CANCELLED</source>
      <translation>モジュールの有効化をキャンセル</translation>
    </message>
    <message>
      <source>PREF_GROUP_EXT_BROWSER</source>
      <translation>外部ブラウザー</translation>
    </message>
    <message>
      <source>PREF_SUPERV_CTRL_COLOR</source>
      <translation>コントロールの色</translation>
    </message>
    <message>
      <source>PREF_GROUP_DEF_COLUMNS</source>
      <translation>既定の列</translation>
    </message>
    <message>
      <source>PREF_GROUP_PLOT2DVIEWER</source>
      <translation>Plot 2D Viewer</translation>
    </message>
    <message>
      <source>PREF_GROUP_VIEWER</source>
      <translation>ビューワ</translation>
    </message>
    <message>
      <source>PREF_GROUP_LEGEND</source>
      <translation>凡例</translation>
    </message>
    <message>
      <source>PREF_LEGEND_SYMBOL_TYPE</source>
      <translation>シンボルの型:</translation>
    </message>
    <message>
      <source>PREF_MARKER_ABOVE_LINE</source>
      <translation>線の上のマーカー</translation>
    </message>
    <message>
      <source>PREF_MARKER_ON_LINE</source>
      <translation>線上のマーカー</translation>
    </message>
    <message>
      <source>PREF_DEVIATION_COLOR</source>
      <translation>偏差のマーカーの色</translation>
    </message>
    <message>
      <source>PREF_DEVIATION_MARKER_LW</source>
      <translation>偏差のマーカーの線の太さ</translation>
    </message>
    <message>
      <source>PREF_DEVIATION_MARKER_TS</source>
      <translation>サイズ偏差マーカーのチェック マーク</translation>
    </message>
    <message>
      <source>MEN_DESK_MRU</source>
      <translation>最近使用したファイル</translation>
    </message>
    <message>
      <source>TOT_DESK_PREFERENCES</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>DEFINE_EXTERNAL_BROWSER</source>
      <translation>外部のブラウザーが見つかりません。環境設定で設定しますか。</translation>
    </message>
    <message>
      <source>PREF_AUTO_SIZE</source>
      <translation>他の列の自動サイズ</translation>
    </message>
    <message>
      <source>TOT_DESK_MRU</source>
      <translation>最近使用したファイル</translation>
    </message>
    <message>
      <source>ACTIVATE_MODULE_OP_NEW</source>
      <translation>新規作成(&amp;N)</translation>
    </message>
    <message>
      <source>ACTIVATE_MODULE_OP_OPEN</source>
      <translation>開く...(&amp;O)</translation>
    </message>
    <message>
      <source>PYTHON_CONSOLE</source>
      <translation>Python コンソール</translation>
    </message>
    <message>
      <source>PREF_GROUP_SELECTION</source>
      <translation>選択</translation>
    </message>
    <message>
      <source>PREF_ENABLE_SELECTION</source>
      <translation>選択範囲を有効にします。</translation>
    </message>
    <message>
      <source>PREF_ENABLE_PRESELECTION</source>
      <translation>予選を有効にします。</translation>
    </message>
    <message>
      <source>PREF_PRESELECTION</source>
      <translation>予選</translation>
    </message>
    <message>
      <source>PREF_PRESELECTION_STANDARD</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>PREF_PRESELECTION_DYNAMIC</source>
      <translation>動的</translation>
    </message>
    <message>
      <source>PREF_PRESELECTION_DISABLED</source>
      <translation>無効になっています。</translation>
    </message>
    <message>
      <source>PREF_GROUP_CLIPPING</source>
      <translation>クリッピングパラメータ</translation>
    </message>
    <message>
      <source>PREF_CLIPPING_COLOR</source>
      <translation>色</translation>
    </message>
    <message>
      <source>PREF_CLIPPING_DEFAULT_TEXTURE</source>
      <translation>デフォルトテキスチャの使用</translation>
    </message>
    <message>
      <source>PREF_CLIPPING_TEXTURE</source>
      <translation>テキスチャ</translation>
    </message>
    <message>
      <source>OCC_TEXTURE_FILES</source>
      <translation>イメージファイル (*.jpeg *jpg *.jpe *.png *.bmp *.gif *.ppm *.tif *.tiff* .tga *.exr)</translation>
    </message>
    <message>
      <source>PREF_CLIPPING_MODULATE</source>
      <translation>調整</translation>
    </message>
    <message>
      <source>PREF_CLIPPING_SCALE</source>
      <translation>スケールファクタ</translation>
    </message>
    <message>
      <source>PREF_GROUP_RAY_TRACING</source>
      <translation>レイトレース</translation>
    </message>
    <message>
      <source>PREF_RAY_TRACING_DEPTH</source>
      <translation>深度</translation>
    </message>
    <message>
      <source>PREF_RAY_TRACING_REFLECTION</source>
      <translation>狭反射</translation>
    </message>
    <message>
      <source>PREF_RAY_TRACING_ANTIALIASING</source>
      <translation>最適アンチエイリアシング</translation>
    </message>
    <message>
      <source>PREF_RAY_TRACING_SHADOW</source>
      <translation>シャドウレンダリング</translation>
    </message>
    <message>
      <source>PREF_RAY_TRACING_TRANS_SHADOW</source>
      <translation>透過影</translation>
    </message>
    <message>
      <source>PREF_GROUP_LIGHT</source>
      <translation>光源</translation>
    </message>
    <message>
      <source>PREF_LIGHT_COLOR</source>
      <translation>色</translation>
    </message>
    <message>
      <source>TOT_CLOSE</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>MEN_DESK_CLOSE</source>
      <translation>閉じる(&amp;C)</translation>
    </message>
    <message>
      <source>PRP_CLOSE</source>
      <translation>アクティブ ウィンドウを閉じる</translation>
    </message>
    <message>
      <source>TOT_CLOSE_ALL</source>
      <translation>すべて閉じる</translation>
    </message>
    <message>
      <source>MEN_DESK_CLOSE_ALL</source>
      <translation>すべて閉じる</translation>
    </message>
    <message>
      <source>PRP_CLOSE_ALL</source>
      <translation>すべてのウィンドウを閉じる</translation>
    </message>
    <message>
      <source>TOT_GROUP_ALL</source>
      <translation>すべてをグループ化</translation>
    </message>
    <message>
      <source>MEN_DESK_GROUP_ALL</source>
      <translation>すべてをグループ化(&amp;G)</translation>
    </message>
    <message>
      <source>PRP_GROUP_ALL</source>
      <translation>すべてのウィンドウをグループ化</translation>
    </message>
    <message>
      <source>ERR_DOC_NOT_EXISTS</source>
      <translation>%1 を開くことができません。ファイルが存在しません</translation>
    </message>
    <message>
      <source>PREF_GROUP_MRU</source>
      <translation>MRUアイテムの表示</translation>
    </message>
    <message>
      <source>PREF_MRU_VISIBLE_COUNT</source>
      <translation>MRUアイテムの数</translation>
    </message>
    <message>
      <source>PREF_MRU_INSERT_MODE</source>
      <translation>挿入モード</translation>
    </message>
    <message>
      <source>PREF_MRU_MOVE_FIRST</source>
      <translation>先頭に移動</translation>
    </message>
    <message>
      <source>PREF_MRU_MOVE_LAST</source>
      <translation>末尾に移動</translation>
    </message>
    <message>
      <source>PREF_MRU_ADD_FIRST</source>
      <translation>先頭に追加</translation>
    </message>
    <message>
      <source>PREF_MRU_ADD_LAST</source>
      <translation>最後に追加</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_TYPE</source>
      <translation>リンクの種類</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_AUTO</source>
      <translation>自動</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_SHORT</source>
      <translation>短い</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_FULL</source>
      <translation>完全な</translation>
    </message>
    <message>
      <source>PREFERENCES_NOT_SUPPORTED</source>
      <translation>モジュール "%1" の設定はサポートされていません</translation>
    </message>
    <message>
      <source>PREF_TAB_SHORTCUTS</source>
      <translation>ショートカット</translation>
    </message>
    <message>
      <source>PREF_GROUP_SHORTCUTS</source>
      <translation>ショートカットの設定</translation>
    </message>
    <message>
      <source>PREF_GROUP_FULL_SCREEN</source>
      <translation>全画面表示</translation>
    </message>
    <message>
      <source>PREF_FULL_SCREEN_AUTO</source>
      <translation>オブジェクトブラウザと表示ツールバーを隠す</translation>
    </message>
    <message>
      <source>PREF_TAB_PYEDITOR</source>
      <translation>Python Viewer</translation>
    </message>
    <message>
      <source>PREF_GROUP_PY_FONT</source>
      <translation>フォント設定</translation>
    </message>
    <message>
      <source>PREF_PY_FONT</source>
      <translation>フォント</translation>
    </message>
    <message>
      <source>PREF_GROUP_PY_DISPLAY</source>
      <translation>セッティング表示</translation>
    </message>
    <message>
      <source>PREF_PY_CURRLINE_HIGHLIGHT</source>
      <translation>現在のハイライト線を有効</translation>
    </message>
    <message>
      <source>PREF_PY_TEXT_WRAP</source>
      <translation>テキストラッピングを有効</translation>
    </message>
    <message>
      <source>PREF_PY_CURSON_ON_SCROLL</source>
      <translation>スクロール上のセンタカーソル</translation>
    </message>
    <message>
      <source>PREF_PY_LINE_NUMBS_AREA</source>
      <translation>ライン数エリアの表示</translation>
    </message>
    <message>
      <source>PREF_GROUP_PY_TAB</source>
      <translation>設定タブ</translation>
    </message>
    <message>
      <source>PREF_PY_TAB_WHITESPACES</source>
      <translation>タブホワイトスペースタブの表示</translation>
    </message>
    <message>
      <source>PREF_PY_TAB_SIZE</source>
      <translation>タブサイズ:</translation>
    </message>
    <message>
      <source>PREF_GROUP_VERT_EDGE</source>
      <translation>垂直エッジ設定</translation>
    </message>
    <message>
      <source>PREF_PY_VERT_EDGE</source>
      <translation>垂直エッジの表示</translation>
    </message>
    <message>
      <source>PREF_PY_NUM_COLUMNS</source>
      <translation>列数</translation>
    </message>
  </context>
  <context>
    <name>LightApp_Module</name>
    <message>
      <source>MEN_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>TOP_DISPLAY_ONLY</source>
      <translation>選択のみ表示</translation>
    </message>
    <message>
      <source>STB_DISPLAY_ONLY</source>
      <translation>選択のみ表示</translation>
    </message>
    <message>
      <source>MEN_DISPLAY_ONLY</source>
      <translation>選択のみ表示</translation>
    </message>
    <message>
      <source>TOP_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>MEN_ERASE_ALL</source>
      <translation>すべてを非表示</translation>
    </message>
    <message>
      <source>STB_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>STB_SHOW</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>TOP_SHOW</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>MEN_SHOW</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>STB_ERASE_ALL</source>
      <translation>すべてを非表示</translation>
    </message>
    <message>
      <source>TOP_ERASE_ALL</source>
      <translation>すべてを非表示</translation>
    </message>
  </context>
  <context>
    <name>LightApp_ModuleDlg</name>
    <message>
      <source>DESCRIPTION</source>
      <translation>モジュール &lt;b&gt;%1&lt;/b&gt; を起動します。&lt;br&gt;下のボタンを押して動作を選択して下さい。</translation>
    </message>
    <message>
      <source>CANCEL</source>
      <translation>キャンセル(&amp;C)</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>モジュールのアクティブ化</translation>
    </message>
  </context>
  <context>
    <name>LightApp_NameDlg</name>
    <message>
      <source>TLT_RENAME</source>
      <translation>名前変更</translation>
    </message>
    <message>
      <source>NAME_LBL</source>
      <translation>名前:</translation>
    </message>
  </context>
  <context>
    <name>LightApp_PreferencesDlg</name>
    <message>
      <source>IMPORT_PREFERENCES</source>
      <translation>インポート設定</translation>
    </message>
    <message>
      <source>XML_FILES_FILTER</source>
      <translation>XMLファイル （*.xml）</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>環境設定</translation>
    </message>
    <message>
      <source>WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>IMPORT_BTN_TEXT</source>
      <translation>インポート</translation>
    </message>
    <message>
      <source>DEFAULT_QUESTION</source>
      <translation>既定の設定を復元しますか？</translation>
    </message>
    <message>
      <source>DEFAULT_BTN_TEXT</source>
      <translation>デフォルト</translation>
    </message>
    <message>
      <source>PREF_NEED_RESTART</source>
      <translation>幾つかの変更はアプリケーションを再起動後に有効になります</translation>
    </message>
  </context>
  <context>
    <name>LightApp_ModuleAction</name>
    <message>
      <source>ACTIVATE_MODULE_TOP</source>
      <translation>モジュール %1 の有効/無効にします。</translation>
    </message>
  </context>
  <context>
    <name>LightApp_PyEditor</name>
    <message>
      <source>TOT_DUMP_PYCOMMANDS</source>
      <translation>スクリプト コマンドを生成します。</translation>
    </message>
    <message>
      <source>TOT_SAVE_PYLOG</source>
      <translation>ログの保存</translation>
    </message>
  </context>
</TS>
