<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>EXTERNAL_BROWSER_CANNOT_SHOW_PAGE</source>
      <translation>外部ブラウザー「%1」「%2」のページのヘルプを表示することができます。設定を変更するか。</translation>
    </message>
    <message>
      <source>ABOUT_COPYRIGHT</source>
      <translation>著作権 (C) 2007年-2012 CEA/デン、EDF の R&amp;D オープン カスケード著作権 (C) 2003年-2007 年オープン カスケード、EADS/CCR、LIP6、CEA/デン、CEDRAT、EDF の R&amp;D、脚、プリンキピア R&amp;D、ビューローベリタスジャパン</translation>
    </message>
    <message>
      <source>ABOUT_CAPTION</source>
      <translation>約%1</translation>
    </message>
    <message>
      <source>ABOUT_BASE</source>
      <translation>基本情報</translation>
    </message>
    <message>
      <source>ABOUT_MODULE_INFOS</source>
      <translation>モジュール情報</translation>
    </message>
    <message>
      <source>ABOUT_UNKNOWN_VERSION</source>
      <translation>不明</translation>
    </message>
    <message>
      <source>ABOUT_CLOSE</source>
      <translation>&amp; 閉じる</translation>
    </message>
    <message>
      <source>APP_NAME</source>
      <translation>サロメ</translation>
    </message>
    <message>
      <source>ABOUT_LICENSE</source>
      <translation>GNU LGPL</translation>
    </message>
    <message>
      <source>ABOUT_VERSION</source>
      <translation>バージョン%1</translation>
    </message>
    <message>
      <source>ENTRY_COLUMN</source>
      <translation>エントリ</translation>
    </message>
    <message>
      <source>BROWSER_TITLE</source>
      <translation>サロメ ヘルプ ・ ブラウザー</translation>
    </message>
    <message>
      <source>BROWSER_TOOLBAR_TITLE</source>
      <translation>ナビゲーション</translation>
    </message>
    <message>
      <source>BROWSER_FILEMENU</source>
      <translation>&amp; ファイル</translation>
    </message>
    <message>
      <source>BROWSER_CLOSE</source>
      <translation>&amp; 閉じる</translation>
    </message>
    <message>
      <source>BROWSER_BACK</source>
      <translation>戻ってください</translation>
    </message>
    <message>
      <source>BROWSER_FORWARD</source>
      <translation>前に進む</translation>
    </message>
    <message>
      <source>BROWSER_FIND</source>
      <translation>&amp; を見つける.</translation>
    </message>
    <message>
      <source>BROWSER_FINDNEXT</source>
      <translation>検索 &amp; 次へ</translation>
    </message>
    <message>
      <source>BROWSER_FINDPREV</source>
      <translation>見つける &amp; 前</translation>
    </message>
  </context>
  <context>
    <name>LightApp_Application</name>
    <message>
      <source>LANG_CHANGED</source>
      <translation>アプリケーションの言語が変更されました。変更は、次のアプリケーション セッションに適用されます。</translation>
    </message>
    <message>
      <source>MEN_DESK_THEME</source>
      <translation>テーマ</translation>
    </message>
    <message>
      <source>TOT_THEME</source>
      <translation>テーマ</translation>
    </message>
    <message>
      <source>PRP_THEME</source>
      <translation>スタイルのプロパティの変更</translation>
    </message>
    <message>
      <source>TOT_FULLSCREEN</source>
      <translation>全画面表示</translation>
    </message>
    <message>
      <source>MEN_DESK_FULLSCREEN</source>
      <translation>全画面表示</translation>
    </message>
    <message>
      <source>PRP_FULLSCREEN</source>
      <translation>全画面表示モードに切り替える</translation>
    </message>
    <message>
      <source>INF_TOOLBAR_MODULES</source>
      <translation>モジュール</translation>
    </message>
    <message>
      <source>PREF_SHOW_LEGEND</source>
      <translation>凡例を表示します。</translation>
    </message>
    <message>
      <source>MEN_DESK_RENAME</source>
      <translation>&amp; 名前の変更</translation>
    </message>
    <message>
      <source>PREF_MULTI_FILE</source>
      <translation>マルチ ファイルを保存します。</translation>
    </message>
    <message>
      <source>MEN_DESK_PREFERENCES</source>
      <translation>前 &amp; ferences.</translation>
    </message>
    <message>
      <source>PREF_TRIHEDRON_SHOW</source>
      <translation>三面体を表示します。</translation>
    </message>
    <message>
      <source>PREF_TRIHEDRON</source>
      <translation>三面体を</translation>
    </message>
    <message>
      <source>PREF_TRIHEDRON_SIZE</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>OBJECT_BROWSER</source>
      <translation>オブジェクト ブラウザー</translation>
    </message>
    <message>
      <source>PRP_DESK_PREFERENCES</source>
      <translation>設定を変更することができます。</translation>
    </message>
    <message>
      <source>PREF_GROUP_DIRECTORIES</source>
      <translation>クイック ディレクトリ リスト</translation>
    </message>
    <message>
      <source>PREF_GROUP_VTKVIEWER</source>
      <translation>VTK 3D ビューアー</translation>
    </message>
    <message>
      <source>PREF_STORE_POS</source>
      <translation>ウィンドウの位置を保存します。</translation>
    </message>
    <message>
      <source>PREF_AUTO_SAVE</source>
      <translation>自動保存間隔 (分)</translation>
    </message>
    <message>
      <source>PREF_AUTO_SAVE_DISABLED</source>
      <translation>無効</translation>
    </message>
    <message>
      <source>PREF_PROJECTION_MODE</source>
      <translation>投影モード:</translation>
    </message>
    <message>
      <source>PREF_ORTHOGRAPHIC</source>
      <translation>直交</translation>
    </message>
    <message>
      <source>PREF_PERSPECTIVE</source>
      <translation>視点</translation>
    </message>
    <message>
      <source>PREF_NAVIGATION</source>
      <translation>ナビゲーション スタイル</translation>
    </message>
    <message>
      <source>PREF_STANDARD_STYLE</source>
      <translation>サロメの標準のコントロール</translation>
    </message>
    <message>
      <source>PREF_KEYFREE_STYLE</source>
      <translation>キーボードのフリー スタイル</translation>
    </message>
    <message>
      <source>PREF_ZOOMING</source>
      <translation>ズームのスタイル</translation>
    </message>
    <message>
      <source>PREF_ZOOMING_AT_CENTER</source>
      <translation>ビューの中心を基準</translation>
    </message>
    <message>
      <source>PREF_ZOOMING_AT_CURSOR</source>
      <translation>カーソルに合わせる</translation>
    </message>
    <message>
      <source>PREF_INCREMENTAL_SPEED</source>
      <translation>速の増分:</translation>
    </message>
    <message>
      <source>PREF_INCREMENTAL_SPEED_MODE</source>
      <translation>変更モード:</translation>
    </message>
    <message>
      <source>PREF_ARITHMETIC</source>
      <translation>等差数列</translation>
    </message>
    <message>
      <source>PREF_GEOMETRICAL</source>
      <translation>幾何学的な進行</translation>
    </message>
    <message>
      <source>PREF_FRAME_SPACEMOUSE</source>
      <translation>Spacemouse</translation>
    </message>
    <message>
      <source>PREF_SHOW_STATIC_TRIHEDRON</source>
      <translation>静的三面体を表示します。</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_FUNC_1</source>
      <translation>減少速度増加</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_FUNC_2</source>
      <translation>増加速度の増加</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_FUNC_3</source>
      <translation>支配的な/複合スイッチ</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_1</source>
      <translation>ボタン 1</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_2</source>
      <translation>ボタン 2</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_3</source>
      <translation>ボタン 3</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_4</source>
      <translation>ボタン 4</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_5</source>
      <translation>ボタン 5</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_6</source>
      <translation>ボタン 6</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_7</source>
      <translation>ボタン 7</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_8</source>
      <translation>ボタン 8</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_*</source>
      <translation>ボタン *</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_10</source>
      <translation>ボタン 10</translation>
    </message>
    <message>
      <source>PREF_SPACEMOUSE_BTN_11</source>
      <translation>ボタン 11</translation>
    </message>
    <message>
      <source>PREF_FRAME_RECORDING</source>
      <translation>Avi ファイルの記録</translation>
    </message>
    <message>
      <source>PREF_ALL_DISLPAYED_FRAMES</source>
      <translation>表示を記録フレーム</translation>
    </message>
    <message>
      <source>PREF_FPS</source>
      <translation>FPS</translation>
    </message>
    <message>
      <source>PREF_GROUP_TTL</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>PREF_PROGRESSIVE</source>
      <translation>プログレッシブ</translation>
    </message>
    <message>
      <source>PREF_QUALITY</source>
      <translation>品質</translation>
    </message>
    <message>
      <source>PREF_RECORDING_MODE</source>
      <translation>モード</translation>
    </message>
    <message>
      <source>PREF_SKIPPED_FRAMES</source>
      <translation>指定した FPS で記録</translation>
    </message>
    <message>
      <source>PREF_FRAME_GROUP_NAMES</source>
      <translation>グループの名前</translation>
    </message>
    <message>
      <source>PREF_GROUP_NAMES_TEXT_COLOR</source>
      <translation>テキストの色</translation>
    </message>
    <message>
      <source>PREF_GROUP_NAMES_TRANSPARENCY</source>
      <translation>透明性</translation>
    </message>
    <message>
      <source>PREF_BOTTOM</source>
      <translation>下</translation>
    </message>
    <message>
      <source>PREF_CURVE_TYPE</source>
      <translation>カーブの種類:</translation>
    </message>
    <message>
      <source>PREF_ISOS</source>
      <translation>面分割線の数</translation>
    </message>
    <message>
      <source>PREF_ISOS_U</source>
      <translation>U に沿って</translation>
    </message>
    <message>
      <source>PREF_ISOS_V</source>
      <translation>V に沿って</translation>
    </message>
    <message>
      <source>PREF_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>PRP_MODULE</source>
      <translation>「%1」のモジュールに切り替えます</translation>
    </message>
    <message>
      <source>PREF_ASCII_FILE</source>
      <translation>ASCII 保存</translation>
    </message>
    <message>
      <source>PREFERENCES_NOT_LOADED</source>
      <translation>モジュールの設定"&lt;b&gt;%N&lt;/b&gt;」、モジュールが読み込まれる場合に利用できます</translation>
    </message>
    <message>
      <source>PREF_LINEAR</source>
      <translation>線形</translation>
    </message>
    <message>
      <source>DATA_MODELS</source>
      <translation>データ モデル</translation>
    </message>
    <message>
      <source>PRP_RENAME</source>
      <translation>作業中のウィンドウの名前を変更します。</translation>
    </message>
    <message>
      <source>TOT_RENAME</source>
      <translation>名前の変更</translation>
    </message>
    <message>
      <source>MEN_RENAME_OBJ</source>
      <translation>名前の変更</translation>
    </message>
    <message>
      <source>LOG_WINDOW</source>
      <translation>メッセージ ウィンドウ</translation>
    </message>
    <message>
      <source>PREF_SPLINE</source>
      <translation>スプライン</translation>
    </message>
    <message>
      <source>PREF_OBJ_BROWSER_SEARCH_TOOL</source>
      <translation>検索ツール</translation>
    </message>
    <message>
      <source>PREF_AUTO_HIDE_SEARCH_TOOL</source>
      <translation>自動非表示を有効にします。</translation>
    </message>
    <message>
      <source>PREF_OBJ_BROWSER_SETTINGS</source>
      <translation>[オブジェクト ブラウザー設定]</translation>
    </message>
    <message>
      <source>PRP_APP_MODULE</source>
      <translation>サロメ プラットフォーム中立的なポイントに切り替える</translation>
    </message>
    <message>
      <source>PREF_GROUP_PY_CONSOLE</source>
      <translation>Python コンソール</translation>
    </message>
    <message>
      <source>PREF_SHOW_BANNER</source>
      <translation>バナーを表示します。</translation>
    </message>
    <message>
      <source>PREF_GROUP_STYLE</source>
      <translation>サロメ スタイル</translation>
    </message>
    <message>
      <source>PREF_USE_SALOME_STYLE</source>
      <translation>サロメ スタイルを使用します。</translation>
    </message>
    <message>
      <source>PREF_MARKER_SIZE</source>
      <translation>マーカーのサイズ:</translation>
    </message>
    <message>
      <source>PREF_TAB_VIEWERS</source>
      <translation>視聴者</translation>
    </message>
    <message>
      <source>PREF_APP</source>
      <translation>アプリケーション</translation>
    </message>
    <message>
      <source>PREF_TOP</source>
      <translation>ページのトップへ</translation>
    </message>
    <message>
      <source>MEN_REFRESH</source>
      <translation>更新</translation>
    </message>
    <message>
      <source>PREF_AUTO_SIZE_FIRST</source>
      <translation>「名」列の自動サイズ</translation>
    </message>
    <message>
      <source>PREF_RESIZE_ON_EXPAND_ITEM</source>
      <translation>項目のサイズを変更する列を展開します。</translation>
    </message>
    <message>
      <source>PREF_BROWSE_TO_THE_PUBLISHED_OBJECT</source>
      <translation>パブリッシュされたオブジェクトを参照します。</translation>
    </message>
    <message>
      <source>PREF_BROWSE_NEVER</source>
      <translation>決して</translation>
    </message>
    <message>
      <source>PREF_BROWSE_AFTER_APPLY_AND_CLOSE_ONLY</source>
      <translation>適用 &amp; 終了後のみ</translation>
    </message>
    <message>
      <source>PREF_BROWSE_ALWAYS</source>
      <translation>常に</translation>
    </message>
    <message>
      <source>PREF_GROUP_SUPERV</source>
      <translation>グラフのスーパーバイザー</translation>
    </message>
    <message>
      <source>PREF_TAB_OBJBROWSER</source>
      <translation>オブジェクト ブラウザー</translation>
    </message>
    <message>
      <source>PREF_TAB_GENERAL</source>
      <translation>一般的な</translation>
    </message>
    <message>
      <source>NEW_WINDOW_0</source>
      <translation>&amp; GL 2D ビュー</translation>
    </message>
    <message>
      <source>NEW_WINDOW_1</source>
      <translation>&amp; プロット 2 D ビュー</translation>
    </message>
    <message>
      <source>NEW_WINDOW_2</source>
      <translation>&amp; OCC の 3 D ビュー</translation>
    </message>
    <message>
      <source>NEW_WINDOW_3</source>
      <translation>VT &amp; K 3 D ビュー</translation>
    </message>
    <message>
      <source>NEW_WINDOW_4</source>
      <translation>&amp; QxGraph 2D ビュー</translation>
    </message>
    <message>
      <source>NEW_WINDOW_5</source>
      <translation>Qx &amp; シーン 2 D ビュー</translation>
    </message>
    <message>
      <source>CREATING_NEW_WINDOW</source>
      <translation>新しい%1 を作成します。</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_NAME</source>
      <translation>オブジェクト</translation>
    </message>
    <message>
      <source>PREF_LEGEND_POSITION</source>
      <translation>凡例の位置:</translation>
    </message>
    <message>
      <source>PREF_RELATIVE_SIZE</source>
      <translation>相対</translation>
    </message>
    <message>
      <source>PREF_VIEWER_BACKGROUND</source>
      <translation>バック グラウンド</translation>
    </message>
    <message>
      <source>PREF_VIEWER_BACKGROUND_COLOR</source>
      <translation>背景色</translation>
    </message>
    <message>
      <source>PREF_VIEWER_SELECTION</source>
      <translation>選択色</translation>
    </message>
    <message>
      <source>PREF_XYVIEWER_BACKGROUND</source>
      <translation>XY 表示</translation>
    </message>
    <message>
      <source>PREF_XZVIEWER_BACKGROUND</source>
      <translation>XZ ビュー</translation>
    </message>
    <message>
      <source>PREF_YZVIEWER_BACKGROUND</source>
      <translation>YZ ビュー</translation>
    </message>
    <message>
      <source>PREF_3DVIEWER_BACKGROUND</source>
      <translation>3 D ビュー</translation>
    </message>
    <message>
      <source>PREF_FONT</source>
      <translation>フォント</translation>
    </message>
    <message>
      <source>PREF_LEGEND_FONT</source>
      <translation>凡例のフォント</translation>
    </message>
    <message>
      <source>PREF_FONT_COLOR</source>
      <translation>凡例のフォントの色</translation>
    </message>
    <message>
      <source>PREF_SELECTED_FONT_COLOR</source>
      <translation>強調表示された凡例のフォントの色</translation>
    </message>
    <message>
      <source>PREF_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>PREF_TAB_DIRECTORIES</source>
      <translation>ディレクトリ</translation>
    </message>
    <message>
      <source>ACTIVATING_MODULE</source>
      <translation>モジュール「%1」をアクティブにしようとしました。</translation>
    </message>
    <message>
      <source>PREF_VERT_AXIS_SCALE</source>
      <translation>垂直軸スケール:</translation>
    </message>
    <message>
      <source>PREF_HOR_AXIS_SCALE</source>
      <translation>水平軸スケール:</translation>
    </message>
    <message>
      <source>PREF_GROUP_LANGUAGE</source>
      <translation>言語</translation>
    </message>
    <message>
      <source>PREF_CURRENT_LANGUAGE</source>
      <translation>現在の言語</translation>
    </message>
    <message>
      <source>PREF_GROUP_LOOK_AND_FEEL</source>
      <translation>ルック アンド フィール</translation>
    </message>
    <message>
      <source>PREF_SHOW_SPLASH</source>
      <translation>起動時にスプラッシュ スクリーンを表示します。</translation>
    </message>
    <message>
      <source>PREF_OPAQUE_RESIZE</source>
      <translation>不透明なサイズ変更</translation>
    </message>
    <message>
      <source>PREF_GROUP_STUDY</source>
      <translation>物性研究</translation>
    </message>
    <message>
      <source>PREF_CATEGORY_SALOME</source>
      <translation>サロメ</translation>
    </message>
    <message>
      <source>PREF_DROP_DOWN_BUTTONS</source>
      <translation>アクション グループをツールバーのドロップ ダウン ボタン</translation>
    </message>
    <message>
      <source>PREF_GROUP_COMMON</source>
      <translation>一般的です</translation>
    </message>
    <message>
      <source>PREF_GROUP_OCCVIEWER</source>
      <translation>OCC の 3 D ビューアー</translation>
    </message>
    <message>
      <source>PREF_LOGARITHMIC</source>
      <translation>対数</translation>
    </message>
    <message>
      <source>MEN_DESK_MODULE_HELP</source>
      <translation>モジュールのヘルプ</translation>
    </message>
    <message>
      <source>PREF_SUPERV_TITLE_COLOR</source>
      <translation>タイトルの色</translation>
    </message>
    <message>
      <source>PREF_PARAM</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>PREF_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>PREF_LINES</source>
      <translation>行</translation>
    </message>
    <message>
      <source>INF_CANCELLED</source>
      <translation>キャンセル モジュールのアクティブ化</translation>
    </message>
    <message>
      <source>PREF_GROUP_EXT_BROWSER</source>
      <translation>外部ブラウザー</translation>
    </message>
    <message>
      <source>PREF_SUPERV_CTRL_COLOR</source>
      <translation>Ctrl キーを色</translation>
    </message>
    <message>
      <source>PREF_GROUP_DEF_COLUMNS</source>
      <translation>既定の列</translation>
    </message>
    <message>
      <source>PREF_GROUP_PLOT2DVIEWER</source>
      <translation>プロット 2 D ビューアー</translation>
    </message>
    <message>
      <source>PREF_DEVIATION_COLOR</source>
      <translation>偏差のマーカーの色</translation>
    </message>
    <message>
      <source>PREF_DEVIATION_MARKER_LW</source>
      <translation>偏差標示の線幅</translation>
    </message>
    <message>
      <source>PREF_DEVIATION_MARKER_TS</source>
      <translation>偏差マーカー ティック サイズ</translation>
    </message>
    <message>
      <source>MEN_DESK_MRU</source>
      <translation>最近使用しました。</translation>
    </message>
    <message>
      <source>TOT_DESK_PREFERENCES</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>DEFINE_EXTERNAL_BROWSER</source>
      <translation>外部ブラウザーが見つかりません。環境設定で定義しますか。</translation>
    </message>
    <message>
      <source>PREF_AUTO_SIZE</source>
      <translation>その他の列の自動サイズ</translation>
    </message>
    <message>
      <source>TOT_DESK_MRU</source>
      <translation>最近使用しました。</translation>
    </message>
    <message>
      <source>ACTIVATE_MODULE_OP_NEW</source>
      <translation>&amp; 新</translation>
    </message>
    <message>
      <source>ACTIVATE_MODULE_OP_OPEN</source>
      <translation>&amp; を開く.</translation>
    </message>
    <message>
      <source>PYTHON_CONSOLE</source>
      <translation>Python コンソール</translation>
    </message>
    <message>
      <source>PREF_DYNAMIC_PRESELECTION</source>
      <translation>動的な事前選択</translation>
    </message>
    <message>
      <source>TOT_CLOSE</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>MEN_DESK_CLOSE</source>
      <translation>&amp; 閉じる</translation>
    </message>
    <message>
      <source>PRP_CLOSE</source>
      <translation>アクティブなウィンドウを閉じる</translation>
    </message>
    <message>
      <source>TOT_CLOSE_ALL</source>
      <translation>すべて閉じる</translation>
    </message>
    <message>
      <source>MEN_DESK_CLOSE_ALL</source>
      <translation>すべて閉じる</translation>
    </message>
    <message>
      <source>PRP_CLOSE_ALL</source>
      <translation>すべてのウィンドウを閉じる</translation>
    </message>
    <message>
      <source>TOT_GROUP_ALL</source>
      <translation>すべてをグループします。</translation>
    </message>
    <message>
      <source>MEN_DESK_GROUP_ALL</source>
      <translation>&amp; すべてグループ化</translation>
    </message>
    <message>
      <source>PRP_GROUP_ALL</source>
      <translation>すべてのウィンドウをグループ化します。</translation>
    </message>
    <message>
      <source>ERR_DOC_NOT_EXISTS</source>
      <translation>%1 を開くことができません。ファイルが存在しません。</translation>
    </message>
    <message>
      <source>PREF_GROUP_MRU</source>
      <translation>最近使用したアイテムを表示します。</translation>
    </message>
    <message>
      <source>PREF_MRU_VISIBLE_COUNT</source>
      <translation>最近使用したアイテムの数</translation>
    </message>
    <message>
      <source>PREF_MRU_INSERT_MODE</source>
      <translation>挿入モード</translation>
    </message>
    <message>
      <source>PREF_MRU_MOVE_FIRST</source>
      <translation>先頭に移動します。</translation>
    </message>
    <message>
      <source>PREF_MRU_MOVE_LAST</source>
      <translation>末尾に移動します。</translation>
    </message>
    <message>
      <source>PREF_MRU_ADD_FIRST</source>
      <translation>先頭に追加します。</translation>
    </message>
    <message>
      <source>PREF_MRU_ADD_LAST</source>
      <translation>最後に追加します。</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_TYPE</source>
      <translation>リンクの種類</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_AUTO</source>
      <translation>自動</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_SHORT</source>
      <translation>短い</translation>
    </message>
    <message>
      <source>PREF_MRU_LINK_FULL</source>
      <translation>完全な</translation>
    </message>
    <message>
      <source>PREFERENCES_NOT_SUPPORTED</source>
      <translation>設定モジュール「%1」はサポートされていません</translation>
    </message>
    <message>
      <source>PREF_TAB_SHORTCUTS</source>
      <translation>ショートカット</translation>
    </message>
    <message>
      <source>PREF_GROUP_SHORTCUTS</source>
      <translation>ショートカット設定</translation>
    </message>
  </context>
  <context>
    <name>LightApp_Module</name>
    <message>
      <source>MEN_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>TOP_DISPLAY_ONLY</source>
      <translation>のみを表示します。</translation>
    </message>
    <message>
      <source>STB_DISPLAY_ONLY</source>
      <translation>のみを表示します。</translation>
    </message>
    <message>
      <source>MEN_DISPLAY_ONLY</source>
      <translation>のみを表示します。</translation>
    </message>
    <message>
      <source>TOP_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>MEN_ERASE_ALL</source>
      <translation>すべてを非表示します。</translation>
    </message>
    <message>
      <source>STB_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>STB_SHOW</source>
      <translation>ショー</translation>
    </message>
    <message>
      <source>TOP_SHOW</source>
      <translation>ショー</translation>
    </message>
    <message>
      <source>MEN_SHOW</source>
      <translation>ショー</translation>
    </message>
    <message>
      <source>STB_ERASE_ALL</source>
      <translation>すべてを非表示します。</translation>
    </message>
    <message>
      <source>TOP_ERASE_ALL</source>
      <translation>すべてを非表示します。</translation>
    </message>
  </context>
  <context>
    <name>LightApp_ModuleDlg</name>
    <message>
      <source>DESCRIPTION</source>
      <translation>モジュール &lt;b&gt;%1&lt;/b&gt; を活性化しています。&lt;br&gt;してください、下の対応するボタンを押すことによって選択の必要なアクション。</translation>
    </message>
    <message>
      <source>CANCEL</source>
      <translation>&amp; [キャンセル</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>モジュールをアクティブにします。</translation>
    </message>
  </context>
  <context>
    <name>LightApp_NameDlg</name>
    <message>
      <source>TLT_RENAME</source>
      <translation>名前の変更</translation>
    </message>
    <message>
      <source>NAME_LBL</source>
      <translation>名前:</translation>
    </message>
  </context>
  <context>
    <name>LightApp_PreferencesDlg</name>
    <message>
      <source>IMPORT_PREFERENCES</source>
      <translation>インポートの基本設定</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>IMPORT_BTN_TEXT</source>
      <translation>インポート</translation>
    </message>
    <message>
      <source>DEFAULT_QUESTION</source>
      <translation>既定の設定を取得しますか。</translation>
    </message>
    <message>
      <source>DEFAULT_BTN_TEXT</source>
      <translation>既定値</translation>
    </message>
  </context>
  <context>
    <name>LightApp_ModuleAction</name>
    <message>
      <source>ACTIVATE_MODULE_TOP</source>
      <translation>モジュールのオン/オフの%1</translation>
    </message>
  </context>
</TS>
