<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>GLViewer_ViewFrame</name>
    <message>
      <source>MNU_FITSELECT</source>
      <translation>ディスプレイの選択</translation>
    </message>
    <message>
      <source>DSC_FITSELECT</source>
      <translation>ビューで選択したゾーンを表示します。</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>現在のビューをイメージ ファイルに保存します。</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パンニング</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>ビューを移動します。</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバルパンニング</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心地の選択</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>すべて表示</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>すべてのオブジェクトを表示します。</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>復元</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>ビューのポイントを復元します。</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>表示エリア</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域にビューを表示します。</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>表示操作</translation>
    </message>
  </context>
  <context>
    <name>GLViewer_ViewManager</name>
    <message>
      <source>GL_VIEW_TITLE</source>
      <translation>シーン GL: %M - ビューアー: %V</translation>
    </message>
  </context>
  <context>
    <name>GLViewer_Viewer</name>
    <message>
      <source>CHANGE_BGCOLOR</source>
      <translation>背景色を変更.</translation>
    </message>
  </context>
</TS>
