<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
<context>
    <name>@default</name>
    <message>
        <source>ICON_VERTEX_MARKER_1</source>
        <translation>marker_1.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_2</source>
        <translation>marker_2.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_3</source>
        <translation>marker_3.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_4</source>
        <translation>marker_4.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_5</source>
        <translation>marker_5.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_6</source>
        <translation>marker_6.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_7</source>
        <translation>marker_7.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_8</source>
        <translation>marker_8.png</translation>
    </message>
    <message>
        <source>ICON_VERTEX_MARKER_9</source>
        <translation>marker_9.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_GLOBALPAN</source>
        <translation>vtk_view_glpan.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FITAREA</source>
        <translation>vtk_view_fitarea.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FITSELECTION</source>
        <translation>vtk_view_fitselection.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FRONT</source>
        <translation>vtk_view_front.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_RESET</source>
        <translation>vtk_view_reset.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_RIGHT</source>
        <translation>vtk_view_right.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FITALL</source>
        <translation>vtk_view_fitall.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_BOTTOM</source>
        <translation>vtk_view_bottom.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_TOP</source>
        <translation>vtk_view_top.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_PAN</source>
        <translation>vtk_view_pan.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_ROTATE</source>
        <translation>vtk_view_rotate.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_DUMP</source>
        <translation>vtk_view_camera_dump.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_BACK</source>
        <translation>vtk_view_back.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_ZOOM</source>
        <translation>vtk_view_zoom.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_LEFT</source>
        <translation>vtk_view_left.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_TRIHEDRON</source>
        <translation>vtk_view_triedre.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_CLOCKWISE</source>
        <translation>occ_view_clockwise.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_ANTICLOCKWISE</source>
        <translation>occ_view_anticlockwise.png</translation>
    </message>
</context>
</TS>
