<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>表示を左に</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>右のビューを回転させる</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>左回転</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>右回転</translation>
    </message>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>正面</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>ビューを保存.</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>上から見る</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>並進移動</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>上面</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心地の選択</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ステージの中心の周りを回転します。</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>ビューを移動します。</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>左側のビュー</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>すべてのオブジェクトを表示するには、ステージのサイズを変更します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>全体表示</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRON</source>
      <translation>現在のビューの三面体を表示/非表示</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>正面</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバルパンニング</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>ビューを保存します。</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>背面</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRON</source>
      <translation>三面体を表示/非表示</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>底面</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>表示リセット</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>左</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>右側のビュー</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>選択領域をビューフレーム内に表示</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>選択範囲表示</translation>
    </message>
    <message>
      <source>MNU_FITSELECTION</source>
      <translation>選択をフィット</translation>
    </message>
    <message>
      <source>DSC_FITSELECTION</source>
      <translation>ビューフレームの内側にある選択されたすべてのオブジェクトをフィット</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>下から表示します。</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>現在のシーンをイメージファイルで保存</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>VTK_IMAGE_FILES</source>
      <translation>イメージ (*.bmp *.png *.jpg *.jpeg) ファイル</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>ビューポイントをリセット</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できませんでした。</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>法律</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>後側のビュー</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_ViewWindow</name>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>表示操作</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_MarkerDlg</name>
    <message>
      <source>SET_MARKER_TLT</source>
      <translation>ポイントマーカーの定義</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_MarkerWidget</name>
    <message>
      <source>STANDARD_MARKER</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>CUSTOM_MARKER</source>
      <translation>カスタム</translation>
    </message>
    <message>
      <source>TYPE</source>
      <translation>型:</translation>
    </message>
    <message>
      <source>SCALE</source>
      <translation>スケール:</translation>
    </message>
    <message>
      <source>CUSTOM</source>
      <translation>テクスチャ:</translation>
    </message>
    <message>
      <source>BROWSE</source>
      <translation>移動...</translation>
    </message>
    <message>
      <source>LOAD_TEXTURE_TLT</source>
      <translation>テクスチャをロード</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_ViewManager</name>
    <message>
      <source>VTK_VIEW_TITLE</source>
      <translation>VTK scene:%M - viewer:%V</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>ビューを保存.</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景を変更する.</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>グラデーションの 2 番目の角</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目の角勾配</translation>
    </message>
    <message>
      <source>GT_FOURTHCORNERGRADIENT</source>
      <translation>第 4 コーナー グラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>ファイル (*.png *.jpg *.jpeg、*.bmp, *.tif, *.tiff *.mhd *.mha)</translation>
    </message>
  </context>
</TS>
