<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>ビューを反時計回りに回転します。</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>ビューを時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>反時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>フロント</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>表示をダンプします.</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>トップ ビュー</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パン</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>ページのトップへ</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心の選択</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ビューのポイント シーンの中心の周りの回転</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>パン表示]</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>左ビュー</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>ビュー フレーム内のすべてのオブジェクトに適合します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>すべてに適合します。</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRON</source>
      <translation>三面体を現在のビューの表示/非表示</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>正面から見た図</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバル パン</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>表示をダンプします</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>戻る</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRON</source>
      <translation>三面体の表示/非表示</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>下</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>リセット</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>左</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>右側のビュー</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域ビュー フレームに合わせて</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>フィット エリア</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>底面図</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>作業中のビューをイメージ ファイルに保存します</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ビューをズームします。</translation>
    </message>
    <message>
      <source>VTK_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.png *.jpg クリックした場合 if)</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>リセット ビュー ポイント</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できません。</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>右</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>[操作の表示</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>背面図</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_MarkerDlg</name>
    <message>
      <source>SET_MARKER_TLT</source>
      <translation>セット ポイント マーカー</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_MarkerWidget</name>
    <message>
      <source>STANDARD_MARKER</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>CUSTOM_MARKER</source>
      <translation>カスタム</translation>
    </message>
    <message>
      <source>TYPE</source>
      <translation>タイプ:</translation>
    </message>
    <message>
      <source>SCALE</source>
      <translation>スケール:</translation>
    </message>
    <message>
      <source>CUSTOM</source>
      <translation>テクスチャ:</translation>
    </message>
    <message>
      <source>BROWSE</source>
      <translation>参照.</translation>
    </message>
    <message>
      <source>LOAD_TEXTURE_TLT</source>
      <translation>テクスチャの読み込み</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_ViewManager</name>
    <message>
      <source>VTK_VIEW_TITLE</source>
      <translation>VTK シーン:%M - ビューアー:%V</translation>
    </message>
  </context>
  <context>
    <name>VTKViewer_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>表示をダンプします.</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示します。</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景の変更.</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>2 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_FOURTHCORNERGRADIENT</source>
      <translation>4 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.png *.jpg クリックした場合 if *.bmp *.tif *.tiff *.mhd *.mha)</translation>
    </message>
  </context>
</TS>
