<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>WRN_FILE_NOT_EXIST</source>
      <translation>ファイル %1 は存在しません。</translation>
    </message>
    <message>
      <source>ERR_ACTIVEDOC_LOAD</source>
      <translation>A study is already active in your session, but you are not connected to it. Use the Connect button to load it in the interface.
スタディはあなたのセッション内ですでにアクティブになっていますが、接続できません。インターフェイス内でそれをロードするための接続用ボタンを使用してください。</translation>
    </message>
    <message>
      <source>WRN_STUDY_LOCKED</source>
      <translation>スタディがロックされています</translation>
    </message>
    <message>
      <source>WRN_NO_STUDY_ON SERV</source>
      <translation>セッションにスタディがありません。</translation>
    </message>
    <message>
      <source>CLOSE_LOCKED_STUDY</source>
      <translation>ロックされたスタディを閉じますか。</translation>
    </message>
    <message>
      <source>PUBLISH_IN_STUDY</source>
      <translation>スタディ公開</translation>
    </message>
    <message>
      <source>MULTI_FILE_DUMP</source>
      <translation>複数ファイルの書き出し</translation>
    </message>
    <message>
      <source>BUT_NEW</source>
      <translation>新規作成(&amp;N)</translation>
    </message>
    <message>
      <source>SAVE_POINT_ROOT_NAME</source>
      <translation>HMI の状態</translation>
    </message>
    <message>
      <source>SAVE_POINT_ROOT_TOOLTIP</source>
      <translation>状態の HMI 永続的です</translation>
    </message>
    <message>
      <source>SAVE_GUI_STATE</source>
      <translation>GUIの状態を保存</translation>
    </message>
    <message>
      <source>BUT_LOAD</source>
      <translation>読み込み(&amp;L)</translation>
    </message>
    <message>
      <source>BUT_OPEN</source>
      <translation>開く(&amp;O)</translation>
    </message>
    <message>
      <source>SAVE_POINT_OBJECT_TOOLTIP</source>
      <translation>保存されたGUI状態: %1</translation>
    </message>
    <message>
      <source>SAVE_POINT_DEF_NAME</source>
      <translation>HCI の状態:</translation>
    </message>
    <message>
      <source>VALUE_COLUMN</source>
      <translation>値</translation>
    </message>
    <message>
      <source>IOR_COLUMN</source>
      <translation>IOR</translation>
    </message>
    <message>
      <source>REFENTRY_COLUMN</source>
      <translation>REFエントリ</translation>
    </message>
    <message>
      <source>ERR_INCOMPATIBLE_TYPE</source>
      <translation>変数"%1"の数値型は互換性がありません</translation>
    </message>
    <message>
      <source>ERR_INVALID_VALUE</source>
      <translation>値が検証されていません</translation>
    </message>
    <message>
      <source>ERR_NO_VARIABLE</source>
      <translation>変数"%1"は存在しません。</translation>
    </message>
    <message>
      <source>ERR_ACTIVE_STUDY_CREATE</source>
      <translation>スタディを作成できません: セッションに既にスタディがあります。
新規セッションを開始するかスタディを閉じてください。</translation>
    </message>
    <message>
      <source>ERR_ACTIVE_STUDY_OPEN</source>
      <translation>スタディを開けません: セッションに既にスタディがあります。
新規セッションを開始するかスタディを閉じてください。</translation>
    </message>
    <message>
      <source>OPEN_DOCUMENT_PROBLEM</source>
      <translation>ドキュメントオープン中に不明な問題が発生しました</translation>
    </message>
    <message>
      <source>CREATE_DOCUMENT_PROBLEM</source>
      <translation>ドキュメント作成中に不明な問題が発生しました</translation>
    </message>
    <message>
      <source>TOT_DESK_CONNECT_STUDY</source>
      <translation>スタディの接続</translation>
    </message>
    <message>
      <source>TOT_DESK_DISCONNECT_STUDY</source>
      <translation>スタディの切断</translation>
    </message>
    <message>
      <source>PRP_DESK_CONNECT</source>
      <translation>アクティブスタディの接続</translation>
    </message>
    <message>
      <source>PRP_DESK_DISCONNECT</source>
      <translation>カレントスタディの切断</translation>
    </message>
    <message>
      <source>MEN_DESK_CONNECT</source>
      <translation>接続（&amp;e）</translation>
    </message>
    <message>
      <source>MEN_DESK_DISCONNECT</source>
      <translation>切断（&amp;i）</translation>
    </message>
  </context>
  <context>
    <name>SalomeApp_Application</name>
    <message>
      <source>ALL_FILES_FILTER</source>
      <translation>すべてのファイル (*. *)</translation>
    </message>
    <message>
      <source>APPCLOSE_UNLOAD</source>
      <translation>アンロード(&amp;U)</translation>
    </message>
    <message>
      <source>APPCLOSE_UNLOAD_SAVE</source>
      <translation>保存と切断（&amp;a）</translation>
    </message>
    <message>
      <source>MEN_WINDOWS_NEW</source>
      <translation>新しいウィンドウ</translation>
    </message>
    <message>
      <source>MEN_DELETE_INVALID_REFERENCE</source>
      <translation>無効な参照を削除します。</translation>
    </message>
    <message>
      <source>TOT_FILE_DESK_PREFERENCES</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>MEN_DELETE_VS</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>MEN_OPENWITH</source>
      <translation>モジュール %1 を有効</translation>
    </message>
    <message>
      <source>MEN_DESK_REGISTRY_DISPLAY</source>
      <translation>レジストリの表示(&amp;D)</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_LOAD_SCRIPT</source>
      <translation>Python スクリプトを実行</translation>
    </message>
    <message>
      <source>PREF_PYDUMP_PUBLISH</source>
      <translation>Python scrypt の研究を公開します。</translation>
    </message>
    <message>
      <source>PREF_PYDUMP_MULTI_FILE</source>
      <translation>複数ファイルをPythonでダンプする</translation>
    </message>
    <message>
      <source>PREF_PYDUMP_SAVE_GUI</source>
      <translation>PythonダンプでGUIの状態を保存</translation>
    </message>
    <message>
      <source>PREF_STORE_VISUAL_STATE</source>
      <translation>バックアップ/リストア HCI の最後の状態</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_SAVE_GUI_STATE</source>
      <translation>ビューや表示オブジェクトなど、現在の状態を保存</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_SAVE_GUI_STATE</source>
      <translation>GUIの状態を保存</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_SAVE_GUI_STATE</source>
      <translation>GUIの状態を保存</translation>
    </message>
    <message>
      <source>MEN_RESTORE_VS</source>
      <translation>復元</translation>
    </message>
    <message>
      <source>WRN_DUMP_STUDY_FAILED</source>
      <translation>研究のスクリプトを生成できません。</translation>
    </message>
    <message>
      <source>MEN_DESK_PROPERTIES</source>
      <translation>プロパティ...(&amp;p)</translation>
    </message>
    <message>
      <source>QUE_DOC_ALREADYEXIST</source>
      <translation>ドキュメント %1 は研究のマネージャーに既に存在します。それを再読み込みしますか。</translation>
    </message>
    <message>
      <source>MEN_RENAME_VS</source>
      <translation>名前の変更</translation>
    </message>
    <message>
      <source>TOT_DESK_CATALOG_GENERATOR</source>
      <translation>カタログの生成</translation>
    </message>
    <message>
      <source>TOT_DESK_ADD_VARS_TO_NOTEBOOK</source>
      <translation>変数をレジストリに追加します。</translation>
    </message>
    <message>
      <source>PUBLISH_IN_STUDY</source>
      <translation>スタディ公開</translation>
    </message>
    <message>
      <source>PREF_OBJ_BROWSER_SETTINGS</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>PRP_DESK_REGISTRY_DISPLAY</source>
      <translation>CORBAサーバーの登録内容を表示</translation>
    </message>
    <message>
      <source>APPCLOSE_DESCRIPTION</source>
      <translation>閉じる、または閉じる前にスタディをアンロードしますか？</translation>
    </message>
    <message>
      <source>PRP_DESK_PROPERTIES</source>
      <translation>スタディのプロパティを編集</translation>
    </message>
    <message>
      <source>PREF_TAB_OBJBROWSER</source>
      <translation>オブジェクトブラウザー</translation>
    </message>
    <message>
      <source>STUDY_LOCKED</source>
      <translation>ロック</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_NAME</source>
      <translation>オブジェクト</translation>
    </message>
    <message>
      <source>TOT_DESK_REGISTRY_DISPLAY</source>
      <translation>レジストリの表示</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_COLUMN_0</source>
      <translation>エントリ</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_COLUMN_1</source>
      <translation>値</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_COLUMN_2</source>
      <translation>IOR</translation>
    </message>
    <message>
      <source>OBJ_BROWSER_COLUMN_3</source>
      <translation>参照エントリ</translation>
    </message>
    <message>
      <source>PREF_CATEGORY_SALOME</source>
      <translation>SALOME</translation>
    </message>
    <message>
      <source>PYTHON_CONSOLE</source>
      <translation>Python コンソール</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_LOAD_SCRIPT</source>
      <translation>スクリプトを読込み...(&amp;t)</translation>
    </message>
    <message>
      <source>MEN_DESK_TOOLS</source>
      <translation>ツール(&amp;T)</translation>
    </message>
    <message>
      <source>MEN_DESK_PLUGINS_TOOLS</source>
      <translation>ツール</translation>
    </message>
    <message>
      <source>MEN_DESK_PLUGINS</source>
      <translation>プラグイン</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_DUMP_STUDY</source>
      <translation>physonスクリプトを保存</translation>
    </message>
    <message>
      <source>MEN_VIEW_WNDS</source>
      <translation>Windows</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_DUMP_STUDY</source>
      <translation>スクリプトを保存(&amp;D)</translation>
    </message>
    <message>
      <source>PRP_DESK_CATALOG_GENERATOR</source>
      <translation>コンポーネントインターフェイスのXMLカタログを生成</translation>
    </message>
    <message>
      <source>PRP_DESK_ADD_VARS_TO_NOTEBOOK</source>
      <translation>スタディの変数をnotebookに追加</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_DUMP_STUDY</source>
      <translation>Pythonスクリプトにスタディをダンプする</translation>
    </message>
    <message>
      <source>TOT_DESK_FILE_NOTEBOOK</source>
      <translation>レジストリを開く</translation>
    </message>
    <message>
      <source>MEN_DESK_FILE_NOTEBOOK</source>
      <translation>Notebook...(&amp;k)</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_NOTEBOOK</source>
      <translation>レジストリを開く</translation>
    </message>
    <message>
      <source>TOT_DESK_PROPERTIES</source>
      <translation>スタディのプロパティ</translation>
    </message>
    <message>
      <source>PREF_GROUP_DEF_COLUMNS</source>
      <translation>既定の列</translation>
    </message>
    <message>
      <source>PRP_DESK_FILE_LOAD_SCRIPT</source>
      <translation>ファイルからPythonスクリプトを読込み</translation>
    </message>
    <message>
      <source>MEN_DESK_CATALOG_GENERATOR</source>
      <translation>カタログ ジェネレーター(&amp;G)</translation>
    </message>
    <message>
      <source>MEN_DESK_ADD_VARS_TO_NOTEBOOK</source>
      <translation>変数をレジストリに追加します。</translation>
    </message>
    <message>
      <source>MEN_DESK_MRU</source>
      <translation>最近のスタディ</translation>
    </message>
    <message>
      <source>TOT_DESK_MRU</source>
      <translation>最近のスタディ</translation>
    </message>
    <message>
      <source>ACTIVATE_MODULE_OP_LOAD</source>
      <translation>読込み(&amp;L)</translation>
    </message>
    <message>
      <source>ACTIVATE_MODULE_OP_SCRIPT</source>
      <translation>スクリプト読込み(&amp;S)</translation>
    </message>
    <message>
      <source>DISCONNECT_CAPTION</source>
      <translation>アクティブスタディの切断</translation>
    </message>
    <message>
      <source>DISCONNECT_DESCRIPTION</source>
      <translation>切断の前にスタディを保存しますか？</translation>
    </message>
    <message>
      <source>DISCONNECT_SAVE</source>
      <translation>保存と切断（&amp;S）</translation>
    </message>
    <message>
      <source>DISCONNECT_WO_SAVE</source>
      <translation>w/o 保存の切断（&amp;D）</translation>
    </message>
  </context>
  <context>
    <name>SalomeApp_StudyPropertiesDlg</name>
    <message>
      <source>PRP_MODE_FROM_SCRATCH</source>
      <translation>ゼロから</translation>
    </message>
    <message>
      <source>PRP_AUTHOR</source>
      <translation>作成者</translation>
    </message>
    <message>
      <source>PRP_LOCKED</source>
      <translation>ロック</translation>
    </message>
    <message>
      <source>PRP_MODIFICATIONS</source>
      <translation>変更</translation>
    </message>
    <message>
      <source>PRP_COMPONENT</source>
      <translation>コンポーネント</translation>
    </message>
    <message>
      <source>PRP_VERSION</source>
      <translation>バージョン</translation>
    </message>
    <message>
      <source>PRP_VERSIONS</source>
      <translation>格納されているデータ</translation>
    </message>
    <message>
      <source>PRP_DATE_MODIF</source>
      <translation>日付</translation>
    </message>
    <message>
      <source>PRP_UNITS</source>
      <translation>長さの単位</translation>
    </message>
    <message>
      <source>PRP_COMMENT</source>
      <translation>コメント</translation>
    </message>
    <message>
      <source>PRP_NO</source>
      <translation>いいえ</translation>
    </message>
    <message>
      <source>PRP_YES</source>
      <translation>はい</translation>
    </message>
    <message>
      <source>PRP_MODIFIED</source>
      <translation>変更</translation>
    </message>
    <message>
      <source>PRP_NOT_MODIFIED</source>
      <translation>変更無</translation>
    </message>
    <message>
      <source>PRP_DATE</source>
      <translation>作成日</translation>
    </message>
    <message>
      <source>PRP_MODE</source>
      <translation>モード</translation>
    </message>
    <message>
      <source>PRP_MODE_FROM_COPYFROM</source>
      <translation>…からコピー</translation>
    </message>
    <message>
      <source>TLT_STUDY_PROPERTIES</source>
      <translation>スタディのプロパティ</translation>
    </message>
  </context>
  <context>
    <name>SalomeApp_ExitDlg</name>
    <message>
      <source>SHUTDOWN_SERVERS</source>
      <translation>サーバーを停止します。</translation>
    </message>
  </context>
  <context>
    <name>NoteBook_Table</name>
    <message>
      <source>REMOVE_VARIABLE_IS_USED</source>
      <translation>変数"%1"は、Studyに使用されています。\n本当にそれを削除しますか？</translation>
    </message>
    <message>
      <source>RENAME_VARIABLE_IS_USED</source>
      <translation>変数"%1"は、Studyに使用されています。\n本当にその名前を変更しますか？</translation>
    </message>
    <message>
      <source>VARNAME_COLUMN</source>
      <translation>変数名</translation>
    </message>
    <message>
      <source>VARVALUE_COLUMN</source>
      <translation>値</translation>
    </message>
    <message>
      <source>VARVALUE_INCORRECT</source>
      <translation>変数の値が正しくありません: %1</translation>
    </message>
    <message>
      <source>VARNAME_INCORRECT</source>
      <translation>変数の名前が正しくありません: %1</translation>
    </message>
    <message>
      <source>VARNAME_EXISTS</source>
      <translation>変数名「%1」が存在します。</translation>
    </message>
  </context>
  <context>
    <name>SalomeApp_NoteBook</name>
    <message>
      <source>NOTEBOOK_TITLE</source>
      <translation>ノート</translation>
    </message>
    <message>
      <source>BUT_UPDATE_STUDY</source>
      <translation>スタディ更新(&amp;U)</translation>
    </message>
    <message>
      <source>BUT_REMOVE</source>
      <translation>削除(&amp;R)</translation>
    </message>
    <message>
      <source>BUT_APPLY_AND_CLOSE</source>
      <translation>適用して閉じる(&amp;p)</translation>
    </message>
    <message>
      <source>BUT_HELP</source>
      <translation>ヘルプ(&amp;H)</translation>
    </message>
    <message>
      <source>CLOSE_CAPTION</source>
      <translation>レジストリを閉じます</translation>
    </message>
    <message>
      <source>CLOSE_DESCRIPTION</source>
      <translation>レジストリに変更を保存しますか?</translation>
    </message>
    <message>
      <source>INCORRECT_DATA</source>
      <translation>少なくとも、一つの変数の定義が正しくありません。その設定を編集または一覧から削除して下さい。</translation>
    </message>
    <message>
      <source>ERR_UPDATE_STUDY_FAILED</source>
      <translation>スタディの更新に失敗しました！</translation>
    </message>
  </context>
  <context>
    <name>SalomeApp_DoubleSpinBox</name>
    <message>
      <source>VALID_RANGE_VAR_MSG</source>
      <translation>小数点以下%3桁の精度で（%1; %2）の範囲の数値または変数名を入力してください。</translation>
    </message>
    <message>
      <source>VALID_RANGE_NOVAR_MSG</source>
      <translation>%3桁の精度で（%1; %2）の範囲の浮動小数点値を入力します。</translation>
    </message>
  </context>
  <context>
    <name>SalomeApp_IntSpinBox</name>
    <message>
      <source>VALID_RANGE_VAR_MSG</source>
      <translation>変数名または整数値のいずれか (%1;%2) の範囲で指定します</translation>
    </message>
    <message>
      <source>VALID_RANGE_NOVAR_MSG</source>
      <translation>(%1;%2) の範囲の整数値を指定します。</translation>
    </message>
  </context>
</TS>
