<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>ビューを反時計回りに回転します。</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>ビューを時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>反時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>時計回りに回転します。</translation>
    </message>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>牛</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>表示をダンプします.</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>オンス ビュー</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パン</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>オンス</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心の選択</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ビューのポイント シーンの中心の周りの回転</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>パン表示]</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>+ オイ ビュー</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>ビュー フレーム内のすべてのオブジェクトに適合します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>すべてに適合します。</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRON</source>
      <translation>三面体を現在のビューの表示/非表示</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>牛ビュー</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバル パン</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>表示をダンプします</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>+ 牛</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRON</source>
      <translation>三面体の表示/非表示</translation>
    </message>
    <message>
      <source>DSC_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>回転の周り実行ポイントを変更します。</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>+ オンス</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>リセット</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>+ オイ</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>-オイ ビュー</translation>
    </message>
    <message>
      <source>MNU_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>変更回転ポイント</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>領域ビュー フレームに合わせて</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>フィット エリア</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>+ オンス ビュー</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>作業中のビューをイメージ ファイルに保存します</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ビューをズームします。</translation>
    </message>
    <message>
      <source>VTK_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.png *.jpg クリックした場合 if)</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>リセット ビュー ポイント</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できません。</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>-オイ</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>[操作の表示</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>+ 牛ビュー</translation>
    </message>
    <message>
      <source>SVTK_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.bmp *.png *.jpg クリックした場合 if *.pdf *.ps *.eps)</translation>
    </message>
    <message>
      <source>MNU_VIEWPARAMETERS_VIEW</source>
      <translation>表示パラメーターの変更</translation>
    </message>
    <message>
      <source>DSC_VIEWPARAMETERS_VIEW</source>
      <translation>ビューのパラメーターを変更します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_PARALLEL_MODE</source>
      <translation>直交モード</translation>
    </message>
    <message>
      <source>DSC_SVTK_PARALLEL_MODE</source>
      <translation>直交射影型を設定します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_PERSPECTIVE_MODE</source>
      <translation>遠近法モード</translation>
    </message>
    <message>
      <source>DSC_SVTK_PERSPECTIVE_MODE</source>
      <translation>遠近法の投影タイプを設定します。</translation>
    </message>
    <message>
      <source>DSC_SVTK_STYLE_SWITCH</source>
      <translation>相互作用のスタイルのスイッチ</translation>
    </message>
    <message>
      <source>MNU_SVTK_STYLE_SWITCH</source>
      <translation>相互作用のスタイルのスイッチ</translation>
    </message>
    <message>
      <source>DSC_SVTK_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルのスイッチ</translation>
    </message>
    <message>
      <source>MNU_SVTK_ZOOMING_STYLE_SWITCH</source>
      <translation>Zomming スタイルのスイッチ</translation>
    </message>
    <message>
      <source>DSC_SVTK_DYNAMIC_PRESLECTION_SWITCH</source>
      <translation>動的な事前選択スイッチ</translation>
    </message>
    <message>
      <source>MNU_SVTK_DYNAMIC_PRESLECTION_SWITCH</source>
      <translation>動的な事前選択スイッチ</translation>
    </message>
  </context>
  <context>
    <name>SVTK_FontWidget</name>
    <message>
      <source>ARIAL</source>
      <translation>Ms p ゴシック</translation>
    </message>
    <message>
      <source>TIMES</source>
      <translation>回</translation>
    </message>
    <message>
      <source>COURIER</source>
      <translation>宅配便</translation>
    </message>
  </context>
  <context>
    <name>SVTK_ViewWindow</name>
    <message>
      <source>DSC_SVTK_UPDATE_RATE</source>
      <translation>更新レート</translation>
    </message>
    <message>
      <source>DSC_SVTK_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>MNU_SVTK_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>MNU_SVTK_GRADUATED_AXES</source>
      <translation>卒業軸</translation>
    </message>
    <message>
      <source>DSC_SVTK_GRADUATED_AXES</source>
      <translation>卒業軸</translation>
    </message>
    <message>
      <source>MNU_SVTK_UPDATE_RATE</source>
      <translation>更新レート</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_START</source>
      <translation>記録を開始します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_START</source>
      <translation>記録を開始します。</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_PLAY</source>
      <translation>録画を続ける</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_PLAY</source>
      <translation>録画を続ける</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_PAUSE</source>
      <translation>記録の一時停止</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_PAUSE</source>
      <translation>記録の一時停止</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_STOP</source>
      <translation>録音を停止します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_STOP</source>
      <translation>録音を停止します。</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_RECORD_LABEL</source>
      <translation>記録の操作</translation>
    </message>
    <message>
      <source>MSG_NO_AVI_MAKER</source>
      <translation>ツール jpeg2yuv、avi ファイルの書き込みに必要ではありません。マニュアルを参照してください。</translation>
    </message>
  </context>
  <context>
    <name>SVTK_NonIsometricDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>MEN_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>スケーリング</translation>
    </message>
  </context>
  <context>
    <name>SVTK_RecorderDlg</name>
    <message>
      <source>ALL_DISLPAYED_FRAMES</source>
      <translation>表示を記録フレーム</translation>
    </message>
    <message>
      <source>CLOSE</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>DLG_RECORDER_TITLE</source>
      <translation>レコーダー</translation>
    </message>
    <message>
      <source>FILE_NAME</source>
      <translation>ファイルを保存します。</translation>
    </message>
    <message>
      <source>FLT_ALL_FILES</source>
      <translation>すべてのファイル (*. *)</translation>
    </message>
    <message>
      <source>FLT_AVI_FILES</source>
      <translation>AVI ファイル (*.avi)</translation>
    </message>
    <message>
      <source>FPS</source>
      <translation>FPS:</translation>
    </message>
    <message>
      <source>HELP</source>
      <translation>ヘルプ</translation>
    </message>
    <message>
      <source>PROGRESSIVE</source>
      <translation>プログレッシブ</translation>
    </message>
    <message>
      <source>QUALITY</source>
      <translation>品質:</translation>
    </message>
    <message>
      <source>RECORDING_MODE</source>
      <translation>モード:</translation>
    </message>
    <message>
      <source>SETTINGS</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>SKIPPED_FRAMES</source>
      <translation>指定した FPS で記録</translation>
    </message>
    <message>
      <source>START</source>
      <translation>開始</translation>
    </message>
  </context>
  <context>
    <name>SVTK_SetRotationPointDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>LBL_CENTER_OF_BOUNDING_BOX</source>
      <translation>境界ボックスの中心</translation>
    </message>
    <message>
      <source>RBUTTONGROUP_TITLE</source>
      <translation>回転ポイントの種類</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_ORIGIN</source>
      <translation>座標システムの原点</translation>
    </message>
    <message>
      <source>LBL_SELECTED_POINT</source>
      <translation>選択したポイント</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点に設定します。</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ポイントのビューから選択</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>回転ポイントを設定</translation>
    </message>
  </context>
  <context>
    <name>SVTK_ViewParameterDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>LBL_DX</source>
      <translation>DX:</translation>
    </message>
    <message>
      <source>LBL_DY</source>
      <translation>DY:</translation>
    </message>
    <message>
      <source>LBL_DZ</source>
      <translation>アルジェリア：</translation>
    </message>
    <message>
      <source>PROJECTION_MODE</source>
      <translation>投影モード</translation>
    </message>
    <message>
      <source>ORTHOGONAL_MODE</source>
      <translation>直交</translation>
    </message>
    <message>
      <source>PERSPECTIVE_MODE</source>
      <translation>視点</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_TOBBCENTER</source>
      <translation>ボックスの中心を境界に設定します。</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点に設定します。</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ポイントのビューから選択</translation>
    </message>
    <message>
      <source>FOCAL_POINT</source>
      <translation>フォーカル ポイント</translation>
    </message>
    <message>
      <source>CAMERA_POSITION</source>
      <translation>カメラの位置</translation>
    </message>
    <message>
      <source>WORLD_COORDINATES</source>
      <translation>絶対座標</translation>
    </message>
    <message>
      <source>FOCAL_RELATIVE</source>
      <translation>フォーカル ポイントに合わせる</translation>
    </message>
    <message>
      <source>PROJECTION_DIRECTION</source>
      <translation>投影方向:</translation>
    </message>
    <message>
      <source>FOCAL_DISTANCE</source>
      <translation>焦点距離：</translation>
    </message>
    <message>
      <source>VIEW_UP_DIRECTION</source>
      <translation>表示方向を。</translation>
    </message>
    <message>
      <source>ZOOMING</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>LBL_SCALE</source>
      <translation>スケール</translation>
    </message>
    <message>
      <source>LBL_VIEW_ANGLE</source>
      <translation>視野角</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>ビューのパラメーター</translation>
    </message>
  </context>
  <context>
    <name>SVTK_UpdateRateDlg</name>
    <message>
      <source>INFORMATION_FRAME_TITLE</source>
      <translation>レンダリング統計情報</translation>
    </message>
    <message>
      <source>STILL</source>
      <translation>率、FPS はまだ更新します。</translation>
    </message>
    <message>
      <source>INPUT_FRAME_TITLE</source>
      <translation>有効にします。</translation>
    </message>
    <message>
      <source>NUMBER_CELLS</source>
      <translation>細胞の数-</translation>
    </message>
    <message>
      <source>DESIRED</source>
      <translation>必要な更新レート、FPS</translation>
    </message>
    <message>
      <source>CURRENT_FPS</source>
      <translation>現在の更新レート FPS</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>更新レート</translation>
    </message>
  </context>
  <context>
    <name>SVTK_ViewManager</name>
    <message>
      <source>VTK_VIEW_TITLE</source>
      <translation>VTK シーン：%1 - ビューアー:%2</translation>
    </message>
  </context>
  <context>
    <name>SVTK_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>表示をダンプします.</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示します。</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景の変更.</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>2 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_FOURTHCORNERGRADIENT</source>
      <translation>4 番目のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>イメージ ファイル (*.png *.jpg クリックした場合 if *.bmp *.tif *.tiff *.mhd *.mha)</translation>
    </message>
  </context>
</TS>
