<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>DSC_ANTICLOCKWISE_VIEW</source>
      <translation>表示を左に</translation>
    </message>
    <message>
      <source>DSC_CLOCKWISE_VIEW</source>
      <translation>右のビューを回転させる</translation>
    </message>
    <message>
      <source>MNU_ANTICLOCKWISE_VIEW</source>
      <translation>表示を左に</translation>
    </message>
    <message>
      <source>MNU_CLOCKWISE_VIEW</source>
      <translation>右のビューを回転させる</translation>
    </message>
    <message>
      <source>MNU_FRONT_VIEW</source>
      <translation>-OX</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>MNU_DUMP_VIEW</source>
      <translation>表示状態の保存</translation>
    </message>
    <message>
      <source>DSC_TOP_VIEW</source>
      <translation>-OZ View</translation>
    </message>
    <message>
      <source>MNU_PAN_VIEW</source>
      <translation>パンニング</translation>
    </message>
    <message>
      <source>MNU_TOP_VIEW</source>
      <translation>-OZ</translation>
    </message>
    <message>
      <source>DSC_GLOBALPAN_VIEW</source>
      <translation>ビューの新しい中心の選択</translation>
    </message>
    <message>
      <source>DSC_ROTATE_VIEW</source>
      <translation>ステージの中心の周りを回転します。</translation>
    </message>
    <message>
      <source>MNU_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>DSC_PAN_VIEW</source>
      <translation>ビューを移動します。</translation>
    </message>
    <message>
      <source>DSC_LEFT_VIEW</source>
      <translation>+OY View</translation>
    </message>
    <message>
      <source>DSC_FITALL</source>
      <translation>すべてのオブジェクトを表示するには、ステージのサイズを変更します。</translation>
    </message>
    <message>
      <source>MNU_FITALL</source>
      <translation>全域表示</translation>
    </message>
    <message>
      <source>MNU_ROTATE_VIEW</source>
      <translation>回転</translation>
    </message>
    <message>
      <source>DSC_SHOW_TRIHEDRON</source>
      <translation>三面体をを表示</translation>
    </message>
    <message>
      <source>DSC_FRONT_VIEW</source>
      <translation>-OX View</translation>
    </message>
    <message>
      <source>MNU_GLOBALPAN_VIEW</source>
      <translation>グローバルパンニング</translation>
    </message>
    <message>
      <source>INF_APP_DUMP_VIEW</source>
      <translation>ビューを保存します。</translation>
    </message>
    <message>
      <source>MNU_BACK_VIEW</source>
      <translation>+OX</translation>
    </message>
    <message>
      <source>MNU_SHOW_TRIHEDRON</source>
      <translation>軸の表示/非表示</translation>
    </message>
    <message>
      <source>DSC_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>シーンになってポイントを変更します。</translation>
    </message>
    <message>
      <source>MNU_BOTTOM_VIEW</source>
      <translation>+OZ</translation>
    </message>
    <message>
      <source>MNU_RESET_VIEW</source>
      <translation>復元</translation>
    </message>
    <message>
      <source>MNU_LEFT_VIEW</source>
      <translation>+OY</translation>
    </message>
    <message>
      <source>DSC_RIGHT_VIEW</source>
      <translation>-OY View</translation>
    </message>
    <message>
      <source>MNU_CHANGINGROTATIONPOINT_VIEW</source>
      <translation>回転の基準点を変更</translation>
    </message>
    <message>
      <source>DSC_FITRECT</source>
      <translation>選択領域の表示</translation>
    </message>
    <message>
      <source>MNU_FITRECT</source>
      <translation>選択領域の表示</translation>
    </message>
    <message>
      <source>MNU_FITSELECTION</source>
      <translation>選択をフィット</translation>
    </message>
    <message>
      <source>DSC_FITSELECTION</source>
      <translation>ビューフレームの内側にある選択されたすべてのオブジェクトをフィット</translation>
    </message>
    <message>
      <source>DSC_BOTTOM_VIEW</source>
      <translation>+OZ View</translation>
    </message>
    <message>
      <source>DSC_DUMP_VIEW</source>
      <translation>表示状態の保存</translation>
    </message>
    <message>
      <source>DSC_ZOOM_VIEW</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>VTK_IMAGE_FILES</source>
      <translation>イメージファイル (*.bmp *.png *.jpg *.jpeg)</translation>
    </message>
    <message>
      <source>DSC_RESET_VIEW</source>
      <translation>ビューのポイントを復元します。</translation>
    </message>
    <message>
      <source>ERR_DOC_CANT_SAVE_FILE</source>
      <translation>ファイルを保存できません。</translation>
    </message>
    <message>
      <source>MNU_RIGHT_VIEW</source>
      <translation>-OY</translation>
    </message>
    <message>
      <source>DSC_BACK_VIEW</source>
      <translation>+OX View</translation>
    </message>
    <message>
      <source>SVTK_IMAGE_FILES</source>
      <translation>イメージファイル (*.bmp *.png *.jpg *.jpeg *. pdf *.ps *.eps)</translation>
    </message>
    <message>
      <source>MNU_VIEWPARAMETERS_VIEW</source>
      <translation>表示パラメーターの変更</translation>
    </message>
    <message>
      <source>DSC_VIEWPARAMETERS_VIEW</source>
      <translation>表示パラメータの変更</translation>
    </message>
    <message>
      <source>MNU_SVTK_PARALLEL_MODE</source>
      <translation>直交モード</translation>
    </message>
    <message>
      <source>DSC_SVTK_PARALLEL_MODE</source>
      <translation>直交射影を選択します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_PERSPECTIVE_MODE</source>
      <translation>遠近法</translation>
    </message>
    <message>
      <source>DSC_SVTK_PERSPECTIVE_MODE</source>
      <translation>透視投影を選択します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_STEREO_MODE</source>
      <translation>ステレオモード</translation>
    </message>
    <message>
      <source>DSC_SVTK_STEREO_MODE</source>
      <translation>ステレオ投影タイプを設定</translation>
    </message>
    <message>
      <source>DSC_SVTK_STYLE_SWITCH</source>
      <translation>相互作用のスタイルを変更します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_STYLE_SWITCH</source>
      <translation>相互作用のスタイルを変更します。</translation>
    </message>
    <message>
      <source>DSC_SVTK_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルを変更します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_ZOOMING_STYLE_SWITCH</source>
      <translation>ズームのスタイルを変更します。</translation>
    </message>
    <message>
      <source>DSC_SVTK_PRESELECTION_STANDARD</source>
      <translation>標準の事前選択モード</translation>
    </message>
    <message>
      <source>MNU_SVTK_PRESELECTION_STANDARD</source>
      <translation>標準の事前選択モード</translation>
    </message>
    <message>
      <source>DSC_SVTK_PRESELECTION_DYNAMIC</source>
      <translation>動的な事前選択モード</translation>
    </message>
    <message>
      <source>MNU_SVTK_PRESELECTION_DYNAMIC</source>
      <translation>動的な事前選択モード</translation>
    </message>
    <message>
      <source>DSC_SVTK_PRESELECTION_DISABLED</source>
      <translation>事前選択を無効にします。</translation>
    </message>
    <message>
      <source>MNU_SVTK_PRESELECTION_DISABLED</source>
      <translation>事前選択を無効にします。</translation>
    </message>
    <message>
      <source>DSC_SVTK_ENABLE_SELECTION</source>
      <translation>選択を有効/無効にします。</translation>
    </message>
    <message>
      <source>MNU_SVTK_ENABLE_SELECTION</source>
      <translation>選択を有効/無効にします。</translation>
    </message>
    <message>
      <source>WRN_SUPPORT_QUAD_BUFFER</source>
      <translation>グラフィックドライバは quad-buffer をサポートしていません</translation>
    </message>
  </context>
  <context>
    <name>SVTK_FontWidget</name>
    <message>
      <source>ARIAL</source>
      <translation>Arial</translation>
    </message>
    <message>
      <source>TIMES</source>
      <translation>Times</translation>
    </message>
    <message>
      <source>COURIER</source>
      <translation>宅配便</translation>
    </message>
  </context>
  <context>
    <name>SVTK_ViewWindow</name>
    <message>
      <source>DSC_SVTK_UPDATE_RATE</source>
      <translation>更新の頻度</translation>
    </message>
    <message>
      <source>DSC_SVTK_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>MNU_SVTK_SCALING</source>
      <translation>スケーリング</translation>
    </message>
    <message>
      <source>MNU_SVTK_GRADUATED_AXES</source>
      <translation>目盛付軸</translation>
    </message>
    <message>
      <source>DSC_SVTK_GRADUATED_AXES</source>
      <translation>目盛付軸</translation>
    </message>
    <message>
      <source>MNU_SVTK_UPDATE_RATE</source>
      <translation>更新の頻度</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_START</source>
      <translation>記録を開始します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_START</source>
      <translation>記録を開始します。</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_PLAY</source>
      <translation>記録を開始します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_PLAY</source>
      <translation>記録を開始します。</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_PAUSE</source>
      <translation>実装の一時停止の記録</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_PAUSE</source>
      <translation>実装の一時停止の記録</translation>
    </message>
    <message>
      <source>DSC_SVTK_RECORDING_STOP</source>
      <translation>記録を停止します。</translation>
    </message>
    <message>
      <source>MNU_SVTK_RECORDING_STOP</source>
      <translation>記録を停止します。</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_LABEL</source>
      <translation>表示操作</translation>
    </message>
    <message>
      <source>LBL_TOOLBAR_RECORD_LABEL</source>
      <translation>登録</translation>
    </message>
    <message>
      <source>MSG_NO_AVI_MAKER</source>
      <translation>AVI ファイルを保存するために必要な jpeg2yuv ツールは利用できません。マニュアルを参照してください。</translation>
    </message>
  </context>
  <context>
    <name>SVTK_NonIsometricDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>スケーリング</translation>
    </message>
  </context>
  <context>
    <name>SVTK_PsOptionsDlg</name>
    <message>
      <source>DLG_PSOPTIONS_TITLE</source>
      <translation>ポストスクリプト書き出しオプション</translation>
    </message>
    <message>
      <source>PS_OPTIONS</source>
      <translation>オプション</translation>
    </message>
    <message>
      <source>PS_LINE_WIDTH</source>
      <translation>線幅係数</translation>
    </message>
    <message>
      <source>PS_POINT_SIZE</source>
      <translation>点サイズオプション</translation>
    </message>
    <message>
      <source>PS_SORT_METHOD</source>
      <translation>ソート法</translation>
    </message>
    <message>
      <source>PS_NO_SORTING</source>
      <translation>ソートなし</translation>
    </message>
    <message>
      <source>PS_SIMPLE_SORTING</source>
      <translation>単純ソート</translation>
    </message>
    <message>
      <source>PS_BPS_SORTING</source>
      <translation>BSP ソート</translation>
    </message>
    <message>
      <source>PS_RASTERIZE_3D</source>
      <translation>3D ジオメトリのラスタライズ</translation>
    </message>
    <message>
      <source>PS_USE_SHFILL</source>
      <translation>shfillシェーディング操作の使用</translation>
    </message>
  </context>
  <context>
    <name>SVTK_RecorderDlg</name>
    <message>
      <source>ALL_DISLPAYED_FRAMES</source>
      <translation>表示されるすべてのフレームを保存</translation>
    </message>
    <message>
      <source>CLOSE</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>DLG_RECORDER_TITLE</source>
      <translation>磁気</translation>
    </message>
    <message>
      <source>FILE_NAME</source>
      <translation>ファイルを保存します。</translation>
    </message>
    <message>
      <source>FLT_ALL_FILES</source>
      <translation>すべてのファイル (*. *)</translation>
    </message>
    <message>
      <source>FLT_AVI_FILES</source>
      <translation>AVI (*.avi) ファイル</translation>
    </message>
    <message>
      <source>FPS</source>
      <translation>FPS:</translation>
    </message>
    <message>
      <source>HELP</source>
      <translation>ヘルプ</translation>
    </message>
    <message>
      <source>PROGRESSIVE</source>
      <translation>プログレッシブ</translation>
    </message>
    <message>
      <source>QUALITY</source>
      <translation>品質:</translation>
    </message>
    <message>
      <source>RECORDING_MODE</source>
      <translation>モード:</translation>
    </message>
    <message>
      <source>SETTINGS</source>
      <translation>設定</translation>
    </message>
    <message>
      <source>SKIPPED_FRAMES</source>
      <translation>与えられたFPSに記録しています</translation>
    </message>
    <message>
      <source>START</source>
      <translation>開始</translation>
    </message>
  </context>
  <context>
    <name>SVTK_SetRotationPointDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>LBL_CENTER_OF_BOUNDING_BOX</source>
      <translation>境界ボックスの中心</translation>
    </message>
    <message>
      <source>RBUTTONGROUP_TITLE</source>
      <translation>回転ポイントの種類</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_ORIGIN</source>
      <translation>座標システムの原点</translation>
    </message>
    <message>
      <source>LBL_SELECTED_POINT</source>
      <translation>選択したポイント</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点を設定</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ビューのポイントを選択します。</translation>
    </message>
    <message>
      <source>LBL_POINT</source>
      <translation>点</translation>
    </message>
    <message>
      <source>LBL_EDGE</source>
      <translation>エッジ</translation>
    </message>
    <message>
      <source>LBL_FACE</source>
      <translation>面</translation>
    </message>
    <message>
      <source>LBL_VOLUME</source>
      <translation>ボリューム</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>回転中心設定</translation>
    </message>
  </context>
  <context>
    <name>SVTK_ViewParameterDlg</name>
    <message>
      <source>LBL_X</source>
      <translation>X :</translation>
    </message>
    <message>
      <source>LBL_Y</source>
      <translation>Y :</translation>
    </message>
    <message>
      <source>LBL_Z</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>LBL_DX</source>
      <translation>DX:</translation>
    </message>
    <message>
      <source>LBL_DY</source>
      <translation>DY:</translation>
    </message>
    <message>
      <source>LBL_DZ</source>
      <translation>DZ :</translation>
    </message>
    <message>
      <source>PROJECTION_MODE</source>
      <translation>投影モード</translation>
    </message>
    <message>
      <source>ORTHOGONAL_MODE</source>
      <translation>直交</translation>
    </message>
    <message>
      <source>PERSPECTIVE_MODE</source>
      <translation>遠近法</translation>
    </message>
    <message>
      <source>USE_BBCENTER</source>
      <translation>境界ボックスの中心を使用します。</translation>
    </message>
    <message>
      <source>LBL_TOBBCENTER</source>
      <translation>境界ボックスの中心を設定します。</translation>
    </message>
    <message>
      <source>LBL_TOORIGIN</source>
      <translation>原点を設定</translation>
    </message>
    <message>
      <source>LBL_SELECTPOINT</source>
      <translation>ビューのポイントを選択します。</translation>
    </message>
    <message>
      <source>FOCAL_POINT</source>
      <translation>フォーカル ポイント</translation>
    </message>
    <message>
      <source>CAMERA_POSITION</source>
      <translation>カメラの位置</translation>
    </message>
    <message>
      <source>WORLD_COORDINATES</source>
      <translation>絶対座標</translation>
    </message>
    <message>
      <source>FOCAL_RELATIVE</source>
      <translation>焦点の問題</translation>
    </message>
    <message>
      <source>PROJECTION_DIRECTION</source>
      <translation>投影の方向:</translation>
    </message>
    <message>
      <source>FOCAL_DISTANCE</source>
      <translation>焦点距離:</translation>
    </message>
    <message>
      <source>VIEW_UP_DIRECTION</source>
      <translation>垂直方向のビューの管理:</translation>
    </message>
    <message>
      <source>ZOOMING</source>
      <translation>ズーム</translation>
    </message>
    <message>
      <source>LBL_SCALE</source>
      <translation>スケール</translation>
    </message>
    <message>
      <source>LBL_VIEW_ANGLE</source>
      <translation>視野角</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>表示パラメータ</translation>
    </message>
  </context>
  <context>
    <name>SVTK_UpdateRateDlg</name>
    <message>
      <source>INFORMATION_FRAME_TITLE</source>
      <translation>情報</translation>
    </message>
    <message>
      <source>STILL</source>
      <translation>更新、FPS の頻度が減少</translation>
    </message>
    <message>
      <source>INPUT_FRAME_TITLE</source>
      <translation>有効にします。</translation>
    </message>
    <message>
      <source>NUMBER_CELLS</source>
      <translation>セルの数-。</translation>
    </message>
    <message>
      <source>DESIRED</source>
      <translation>必要な更新頻度、FPS</translation>
    </message>
    <message>
      <source>CURRENT_FPS</source>
      <translation>現在の頻度更新、FPS の</translation>
    </message>
    <message>
      <source>DLG_TITLE</source>
      <translation>割合の更新</translation>
    </message>
  </context>
  <context>
    <name>SVTK_ViewManager</name>
    <message>
      <source>VTK_VIEW_TITLE</source>
      <translation>シーン VTK: %1 - ビューアー: %2</translation>
    </message>
  </context>
  <context>
    <name>SVTK_Viewer</name>
    <message>
      <source>MEN_DUMP_VIEW</source>
      <translation>ビューを保存.</translation>
    </message>
    <message>
      <source>MEN_SHOW_TOOLBAR</source>
      <translation>ツールバーを表示します。</translation>
    </message>
    <message>
      <source>MEN_CHANGE_BACKGROUND</source>
      <translation>背景を変更する.</translation>
    </message>
    <message>
      <source>GT_HORIZONTALGRADIENT</source>
      <translation>水平方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_VERTICALGRADIENT</source>
      <translation>垂直方向のグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTDIAGONALGRADIENT</source>
      <translation>最初の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDDIAGONALGRADIENT</source>
      <translation>2 番目の斜めのグラデーション</translation>
    </message>
    <message>
      <source>GT_FIRSTCORNERGRADIENT</source>
      <translation>最初のコーナーのグラデーション</translation>
    </message>
    <message>
      <source>GT_SECONDCORNERGRADIENT</source>
      <translation>グラデーションの 2 番目の角</translation>
    </message>
    <message>
      <source>GT_THIRDCORNERGRADIENT</source>
      <translation>3 番目の角勾配</translation>
    </message>
    <message>
      <source>GT_FOURTHCORNERGRADIENT</source>
      <translation>第 4 コーナー グラデーション</translation>
    </message>
    <message>
      <source>BG_IMAGE_FILES</source>
      <translation>ファイル (*.png *.jpg *.jpeg、*.bmp, *.tif, *.tiff *.mhd *.mha)</translation>
    </message>
    <message>
      <source>ST_CRYSTALEYES</source>
      <translation>水晶の目</translation>
    </message>
    <message>
      <source>ST_REDBLUE</source>
      <translation>赤-青投影</translation>
    </message>
    <message>
      <source>ST_INTERLACED</source>
      <translation>インターレース</translation>
    </message>
    <message>
      <source>ST_LEFT</source>
      <translation>左</translation>
    </message>
    <message>
      <source>ST_RIGHT</source>
      <translation>右</translation>
    </message>
    <message>
      <source>ST_DRESDEN</source>
      <translation>Dresden</translation>
    </message>
    <message>
      <source>ST_ANAGLYPH</source>
      <translation>Anaglyph</translation>
    </message>
    <message>
      <source>ST_CHECKERBOARD</source>
      <translation>Checkerboard</translation>
    </message>
    <message>
      <source>ST_SPLITVIEWPORTHORIZONTAL</source>
      <translation>ビューポートを水平に分割</translation>
    </message>
  </context>
</TS>
