<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
<context>
    <name>@default</name>
    <message>
        <source>ICON_SVTK_ROTATION_POINT</source>
        <translation>vtk_view_rotation_point.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_GRADUATED_AXES</source>
        <translation>vtk_view_graduated_axes.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_SCALING</source>
        <translation>vtk_view_scaling.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_UPDATE_RATE</source>
        <translation>vtk_view_update_rate.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_VIEW_PARAMETERS</source>
        <translation>vtk_view_parameters.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_VIEW_PARALLEL</source>
        <translation>vtk_view_parallel.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_VIEW_PERSPECTIVE</source>
        <translation>vtk_view_perspective.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_VIEW_STEREO</source>
        <translation>vtk_view_stereo.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_STYLE_SWITCH</source>
        <translation>vtk_view_style_switch.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_ZOOMING_STYLE_SWITCH</source>
        <translation>vtk_view_zooming_style_switch.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_RECORDING_START</source>
        <translation>vtk_view_recording_start.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_RECORDING_PLAY</source>
        <translation>vtk_view_recording_play.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_RECORDING_PAUSE</source>
        <translation>vtk_view_recording_pause.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_RECORDING_STOP</source>
        <translation>vtk_view_recording_stop.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_PRESELECTION_STANDARD</source>
        <translation>vtk_view_highlight_std.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_PRESELECTION_DYNAMIC</source>
        <translation>vtk_view_highlight_dyn.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_PRESELECTION_DISABLED</source>
        <translation>vtk_view_highlight_off.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_SELECTION</source>
        <translation>vtk_view_selection.png</translation>
    </message>
</context>
</TS>
